# Generated by generate-client from spec/openapi.json. Do not edit.
# ruff: noqa: E501
"""The 6 Airbnb endpoints, in awaitable and blocking form.

Each endpoint's request is built once, by the private functions below. Both
resources call the same builder, so the twins differ only in ``await``.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

from .._resource import AsyncAPIResource, Request, SyncAPIResource
from .._types import Body, NotGiven, Timeout, not_given
from ..airbnb import (
    AmenityFilterParam,
    ParsedAutocompleteResponse,
    ParsedCalendarResponse,
    ParsedDetailsResponse,
    ParsedPriceResponse,
    ParsedReviewsResponse,
    ParsedSearchResponse,
    ReviewSortParam,
)

__all__ = ["Airbnb", "SyncAirbnb"]

_PREFIX = "/v1/airbnb"


def _body(fields: Mapping[str, object]) -> Body:
    """A JSON body with every omitted argument left out, so the server applies its default."""
    return {name: value for name, value in fields.items() if value is not None}


def _get_calendar(
    *, month: int, room_id: str, year: int, count: int = 12, currency: str = "USD"
) -> Request[ParsedCalendarResponse]:
    return Request(
        _PREFIX + "/calendar",
        ParsedCalendarResponse,
        method="POST",
        json=_body(
            {"month": month, "room_id": room_id, "year": year, "count": count, "currency": currency}
        ),
    )


def _get_details(*, room_id: str) -> Request[ParsedDetailsResponse]:
    return Request(
        _PREFIX + "/details", ParsedDetailsResponse, method="POST", json=_body({"room_id": room_id})
    )


def _search_locations(*, query: str, language: str = "en") -> Request[ParsedAutocompleteResponse]:
    return Request(
        _PREFIX + "/locations", ParsedAutocompleteResponse, {"query": query, "language": language}
    )


def _get_price(
    *, check_in: str, check_out: str, room_id: str, adults: int = 1, currency: str = "USD"
) -> Request[ParsedPriceResponse]:
    return Request(
        _PREFIX + "/price",
        ParsedPriceResponse,
        method="POST",
        json=_body(
            {
                "check_in": check_in,
                "check_out": check_out,
                "room_id": room_id,
                "adults": adults,
                "currency": currency,
            }
        ),
    )


def _get_reviews(
    *, room_id: str, limit: int = 50, offset: int = 0, sort: ReviewSortParam | None = None
) -> Request[ParsedReviewsResponse]:
    return Request(
        _PREFIX + "/reviews",
        ParsedReviewsResponse,
        method="POST",
        json=_body({"room_id": room_id, "limit": limit, "offset": offset, "sort": sort}),
    )


def _search(
    *,
    adults: int | None = None,
    amenities: Sequence[AmenityFilterParam] | None = None,
    check_in: str | None = None,
    check_out: str | None = None,
    children: int | None = None,
    currency: str = "USD",
    cursor: str = "",
    free_cancellation: bool = False,
    infants: int | None = None,
    lat: float | None = None,
    lon: float | None = None,
    min_bathrooms: int | None = None,
    min_bedrooms: int | None = None,
    min_beds: int | None = None,
    ne_lat: float | None = None,
    ne_long: float | None = None,
    place_id: str | None = None,
    price_max: int | None = None,
    price_min: int | None = None,
    query: str | None = None,
    radius_km: float | None = None,
    sw_lat: float | None = None,
    sw_long: float | None = None,
    zoom: int | None = None,
) -> Request[ParsedSearchResponse]:
    return Request(
        _PREFIX + "/search",
        ParsedSearchResponse,
        method="POST",
        json=_body(
            {
                "adults": adults,
                "amenities": amenities,
                "check_in": check_in,
                "check_out": check_out,
                "children": children,
                "currency": currency,
                "cursor": cursor,
                "free_cancellation": free_cancellation,
                "infants": infants,
                "lat": lat,
                "lon": lon,
                "min_bathrooms": min_bathrooms,
                "min_bedrooms": min_bedrooms,
                "min_beds": min_beds,
                "ne_lat": ne_lat,
                "ne_long": ne_long,
                "place_id": place_id,
                "price_max": price_max,
                "price_min": price_min,
                "query": query,
                "radius_km": radius_km,
                "sw_lat": sw_lat,
                "sw_long": sw_long,
                "zoom": zoom,
            }
        ),
    )


class Airbnb(AsyncAPIResource):
    """The Airbnb endpoints, awaitable.

    Reached as :attr:`~tapline.TaplineClient.airbnb`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    async def get_calendar(
        self,
        *,
        month: int,
        room_id: str,
        year: int,
        count: int = 12,
        currency: str = "USD",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedCalendarResponse:
        """Check the availability of an Airbnb listing by month. Costs 1 credit.

        Args:
            month: Starting month (1-12)
            room_id: Airbnb listing ID
            year: Starting year
            count: Number of months to fetch
            currency: ISO 4217 currency code (default USD). Any valid ISO 4217 code
                is accepted, but Airbnb only renders prices natively in a subset and
                silently falls back to USD for the rest, so the response `currency`
                field is authoritative and may differ from the request. The
                natively-supported codes are enumerated in the `SupportedCurrency`
                schema (and machine-readably under this field's `x-supported-
                currencies`).
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedCalendarResponse`.
        """
        return await self._send(
            _get_calendar(month=month, room_id=room_id, year=year, count=count, currency=currency),
            timeout=timeout,
        )

    async def get_details(
        self,
        *,
        room_id: str,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedDetailsResponse:
        """Get details about an Airbnb listing. Costs 5 credits.

        Args:
            room_id: Airbnb listing ID. Listings get delisted, so any given ID
                (including the example) can stop resolving.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedDetailsResponse`.
        """
        return await self._send(_get_details(room_id=room_id), timeout=timeout)

    async def search_locations(
        self,
        *,
        query: str,
        language: str = "en",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedAutocompleteResponse:
        """Find Airbnb locations matching a text query. Costs 1 credit.

        Args:
            query: Free-text location query (e.g. 'London', 'Rio de Janeiro')
            language: ISO 639-1 language code (2-letter, e.g. 'en', 'pt', 'fr')
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedAutocompleteResponse`.
        """
        return await self._send(_search_locations(query=query, language=language), timeout=timeout)

    async def get_price(
        self,
        *,
        check_in: str,
        check_out: str,
        room_id: str,
        adults: int = 1,
        currency: str = "USD",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedPriceResponse:
        """Get the price for an Airbnb listing over a date range. Costs 2 credits.

        Args:
            check_in: Check-in date (YYYY-MM-DD)
            check_out: Check-out date (YYYY-MM-DD)
            room_id: Airbnb listing ID
            adults: Number of adults
            currency: ISO 4217 currency code (default USD). Any valid ISO 4217 code
                is accepted, but Airbnb only renders prices natively in a subset and
                silently falls back to USD for the rest, so the response `currency`
                field is authoritative and may differ from the request. The
                natively-supported codes are enumerated in the `SupportedCurrency`
                schema (and machine-readably under this field's `x-supported-
                currencies`).
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedPriceResponse`.
        """
        return await self._send(
            _get_price(
                check_in=check_in,
                check_out=check_out,
                room_id=room_id,
                adults=adults,
                currency=currency,
            ),
            timeout=timeout,
        )

    async def get_reviews(
        self,
        *,
        room_id: str,
        limit: int = 50,
        offset: int = 0,
        sort: ReviewSortParam | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedReviewsResponse:
        """Get reviews for an Airbnb listing. Costs 2 credits.

        Args:
            room_id: Airbnb listing ID
            limit: Number of reviews per page (max 50)
            offset: Pagination offset
            sort: Sort order (MOST_RECENT, RATING_DESC, RATING_ASC)
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedReviewsResponse`.
        """
        return await self._send(
            _get_reviews(room_id=room_id, limit=limit, offset=offset, sort=sort), timeout=timeout
        )

    async def search(
        self,
        *,
        adults: int | None = None,
        amenities: Sequence[AmenityFilterParam] | None = None,
        check_in: str | None = None,
        check_out: str | None = None,
        children: int | None = None,
        currency: str = "USD",
        cursor: str = "",
        free_cancellation: bool = False,
        infants: int | None = None,
        lat: float | None = None,
        lon: float | None = None,
        min_bathrooms: int | None = None,
        min_bedrooms: int | None = None,
        min_beds: int | None = None,
        ne_lat: float | None = None,
        ne_long: float | None = None,
        place_id: str | None = None,
        price_max: int | None = None,
        price_min: int | None = None,
        query: str | None = None,
        radius_km: float | None = None,
        sw_lat: float | None = None,
        sw_long: float | None = None,
        zoom: int | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedSearchResponse:
        """Search for Airbnb listings within a radius, by place ID, or by text query. Costs 5 credits.

        Args:
            adults: Number of adults
            amenities: Amenities to filter by, as readable slugs (e.g. "wifi",
                "kitchen", "tv", "self_check_in"). Unknown values are rejected with
                422; the enum lists every accepted slug. Translated to Airbnb's
                numeric filter IDs internally.
            check_in: Check-in date (YYYY-MM-DD)
            check_out: Check-out date (YYYY-MM-DD)
            children: Number of children
            currency: ISO 4217 currency code (default USD). Any valid ISO 4217 code
                is accepted, but Airbnb only renders prices natively in a subset and
                silently falls back to USD for the rest, so the response `currency`
                field is authoritative and may differ from the request. The
                natively-supported codes are enumerated in the `SupportedCurrency`
                schema (and machine-readably under this field's `x-supported-
                currencies`).
            cursor: Pagination cursor from previous response
            free_cancellation: Filter for free cancellation listings
            infants: Number of infants
            lat: Center latitude for radius search
            lon: Center longitude for radius search
            min_bathrooms: Minimum number of bathrooms
            min_bedrooms: Minimum number of bedrooms
            min_beds: Minimum number of beds
            ne_lat: Northeast latitude of bounding box
            ne_long: Northeast longitude of bounding box
            place_id: Google Place ID for the search area, from the `GET
                /v1/airbnb/locations` endpoint (`suggestions[].place_id`).
            price_max: Maximum price filter
            price_min: Minimum price filter
            query: Text location query (e.g. 'London, United Kingdom')
            radius_km: Search radius in km around (lat, lon). Recommended way to set
                the area — the bounding box and map zoom are derived automatically.
            sw_lat: Southwest latitude of bounding box
            sw_long: Southwest longitude of bounding box
            zoom: Map zoom level, 1–20 (1 ≈ whole world, ~12 ≈ city, ~16 ≈ street,
                20 ≈ building), same scale as Google Maps. Advanced: only needed
                with an explicit bounding box; auto-derived from `radius_km`
                otherwise.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedSearchResponse`.
        """
        return await self._send(
            _search(
                adults=adults,
                amenities=amenities,
                check_in=check_in,
                check_out=check_out,
                children=children,
                currency=currency,
                cursor=cursor,
                free_cancellation=free_cancellation,
                infants=infants,
                lat=lat,
                lon=lon,
                min_bathrooms=min_bathrooms,
                min_bedrooms=min_bedrooms,
                min_beds=min_beds,
                ne_lat=ne_lat,
                ne_long=ne_long,
                place_id=place_id,
                price_max=price_max,
                price_min=price_min,
                query=query,
                radius_km=radius_km,
                sw_lat=sw_lat,
                sw_long=sw_long,
                zoom=zoom,
            ),
            timeout=timeout,
        )


class SyncAirbnb(SyncAPIResource):
    """The Airbnb endpoints, blocking.

    Reached as :attr:`~tapline.SyncTaplineClient.airbnb`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    def get_calendar(
        self,
        *,
        month: int,
        room_id: str,
        year: int,
        count: int = 12,
        currency: str = "USD",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedCalendarResponse:
        """Check the availability of an Airbnb listing by month. Costs 1 credit.

        Args:
            month: Starting month (1-12)
            room_id: Airbnb listing ID
            year: Starting year
            count: Number of months to fetch
            currency: ISO 4217 currency code (default USD). Any valid ISO 4217 code
                is accepted, but Airbnb only renders prices natively in a subset and
                silently falls back to USD for the rest, so the response `currency`
                field is authoritative and may differ from the request. The
                natively-supported codes are enumerated in the `SupportedCurrency`
                schema (and machine-readably under this field's `x-supported-
                currencies`).
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedCalendarResponse`.
        """
        return self._send(
            _get_calendar(month=month, room_id=room_id, year=year, count=count, currency=currency),
            timeout=timeout,
        )

    def get_details(
        self,
        *,
        room_id: str,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedDetailsResponse:
        """Get details about an Airbnb listing. Costs 5 credits.

        Args:
            room_id: Airbnb listing ID. Listings get delisted, so any given ID
                (including the example) can stop resolving.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedDetailsResponse`.
        """
        return self._send(_get_details(room_id=room_id), timeout=timeout)

    def search_locations(
        self,
        *,
        query: str,
        language: str = "en",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedAutocompleteResponse:
        """Find Airbnb locations matching a text query. Costs 1 credit.

        Args:
            query: Free-text location query (e.g. 'London', 'Rio de Janeiro')
            language: ISO 639-1 language code (2-letter, e.g. 'en', 'pt', 'fr')
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedAutocompleteResponse`.
        """
        return self._send(_search_locations(query=query, language=language), timeout=timeout)

    def get_price(
        self,
        *,
        check_in: str,
        check_out: str,
        room_id: str,
        adults: int = 1,
        currency: str = "USD",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedPriceResponse:
        """Get the price for an Airbnb listing over a date range. Costs 2 credits.

        Args:
            check_in: Check-in date (YYYY-MM-DD)
            check_out: Check-out date (YYYY-MM-DD)
            room_id: Airbnb listing ID
            adults: Number of adults
            currency: ISO 4217 currency code (default USD). Any valid ISO 4217 code
                is accepted, but Airbnb only renders prices natively in a subset and
                silently falls back to USD for the rest, so the response `currency`
                field is authoritative and may differ from the request. The
                natively-supported codes are enumerated in the `SupportedCurrency`
                schema (and machine-readably under this field's `x-supported-
                currencies`).
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedPriceResponse`.
        """
        return self._send(
            _get_price(
                check_in=check_in,
                check_out=check_out,
                room_id=room_id,
                adults=adults,
                currency=currency,
            ),
            timeout=timeout,
        )

    def get_reviews(
        self,
        *,
        room_id: str,
        limit: int = 50,
        offset: int = 0,
        sort: ReviewSortParam | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedReviewsResponse:
        """Get reviews for an Airbnb listing. Costs 2 credits.

        Args:
            room_id: Airbnb listing ID
            limit: Number of reviews per page (max 50)
            offset: Pagination offset
            sort: Sort order (MOST_RECENT, RATING_DESC, RATING_ASC)
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedReviewsResponse`.
        """
        return self._send(
            _get_reviews(room_id=room_id, limit=limit, offset=offset, sort=sort), timeout=timeout
        )

    def search(
        self,
        *,
        adults: int | None = None,
        amenities: Sequence[AmenityFilterParam] | None = None,
        check_in: str | None = None,
        check_out: str | None = None,
        children: int | None = None,
        currency: str = "USD",
        cursor: str = "",
        free_cancellation: bool = False,
        infants: int | None = None,
        lat: float | None = None,
        lon: float | None = None,
        min_bathrooms: int | None = None,
        min_bedrooms: int | None = None,
        min_beds: int | None = None,
        ne_lat: float | None = None,
        ne_long: float | None = None,
        place_id: str | None = None,
        price_max: int | None = None,
        price_min: int | None = None,
        query: str | None = None,
        radius_km: float | None = None,
        sw_lat: float | None = None,
        sw_long: float | None = None,
        zoom: int | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ParsedSearchResponse:
        """Search for Airbnb listings within a radius, by place ID, or by text query. Costs 5 credits.

        Args:
            adults: Number of adults
            amenities: Amenities to filter by, as readable slugs (e.g. "wifi",
                "kitchen", "tv", "self_check_in"). Unknown values are rejected with
                422; the enum lists every accepted slug. Translated to Airbnb's
                numeric filter IDs internally.
            check_in: Check-in date (YYYY-MM-DD)
            check_out: Check-out date (YYYY-MM-DD)
            children: Number of children
            currency: ISO 4217 currency code (default USD). Any valid ISO 4217 code
                is accepted, but Airbnb only renders prices natively in a subset and
                silently falls back to USD for the rest, so the response `currency`
                field is authoritative and may differ from the request. The
                natively-supported codes are enumerated in the `SupportedCurrency`
                schema (and machine-readably under this field's `x-supported-
                currencies`).
            cursor: Pagination cursor from previous response
            free_cancellation: Filter for free cancellation listings
            infants: Number of infants
            lat: Center latitude for radius search
            lon: Center longitude for radius search
            min_bathrooms: Minimum number of bathrooms
            min_bedrooms: Minimum number of bedrooms
            min_beds: Minimum number of beds
            ne_lat: Northeast latitude of bounding box
            ne_long: Northeast longitude of bounding box
            place_id: Google Place ID for the search area, from the `GET
                /v1/airbnb/locations` endpoint (`suggestions[].place_id`).
            price_max: Maximum price filter
            price_min: Minimum price filter
            query: Text location query (e.g. 'London, United Kingdom')
            radius_km: Search radius in km around (lat, lon). Recommended way to set
                the area — the bounding box and map zoom are derived automatically.
            sw_lat: Southwest latitude of bounding box
            sw_long: Southwest longitude of bounding box
            zoom: Map zoom level, 1–20 (1 ≈ whole world, ~12 ≈ city, ~16 ≈ street,
                20 ≈ building), same scale as Google Maps. Advanced: only needed
                with an explicit bounding box; auto-derived from `radius_km`
                otherwise.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.airbnb.ParsedSearchResponse`.
        """
        return self._send(
            _search(
                adults=adults,
                amenities=amenities,
                check_in=check_in,
                check_out=check_out,
                children=children,
                currency=currency,
                cursor=cursor,
                free_cancellation=free_cancellation,
                infants=infants,
                lat=lat,
                lon=lon,
                min_bathrooms=min_bathrooms,
                min_bedrooms=min_bedrooms,
                min_beds=min_beds,
                ne_lat=ne_lat,
                ne_long=ne_long,
                place_id=place_id,
                price_max=price_max,
                price_min=price_min,
                query=query,
                radius_km=radius_km,
                sw_lat=sw_lat,
                sw_long=sw_long,
                zoom=zoom,
            ),
            timeout=timeout,
        )
