# Generated by generate-client from spec/openapi.json. Do not edit.
# ruff: noqa: E501
"""The 16 Birdeye endpoints, in awaitable and blocking form.

Each endpoint's request is built once, by the private functions below. Both
resources call the same builder, so the twins differ only in ``await``.
"""

from __future__ import annotations

from collections.abc import Mapping

from .._base_client import encode_path
from .._resource import AsyncAPIResource, Request, SyncAPIResource
from .._types import Body, NotGiven, Timeout, not_given
from ..birdeye import (
    BirdeyeCandleIntervalParam,
    BirdeyeFirstBuyers,
    BirdeyeLeaderboardIntervalParam,
    BirdeyeLeaderboardPage,
    BirdeyeLeaderboardSortParam,
    BirdeyeListingStageParam,
    BirdeyeMarketSortParam,
    BirdeyeNetWorthHistory,
    BirdeyeNetWorthIntervalParam,
    BirdeyeNewListings,
    BirdeyeOhlcv,
    BirdeyePnlPeriodParam,
    BirdeyeSortOrderParam,
    BirdeyeTokenHolders,
    BirdeyeTokenMarkets,
    BirdeyeTokenOverview,
    BirdeyeTokenSecurity,
    BirdeyeTokenTradesPage,
    BirdeyeTopTradersPage,
    BirdeyeTraderSortParam,
    BirdeyeTradeSideParam,
    BirdeyeTrendingTokens,
    BirdeyeWalletPnlSummary,
    BirdeyeWalletPortfolioPage,
    BirdeyeWalletTokenSortParam,
    BirdeyeWalletTokensPage,
    BirdeyeWalletTransactionsPage,
)

__all__ = ["Birdeye", "SyncBirdeye"]

_PREFIX = "/v1/birdeye"


def _body(fields: Mapping[str, object]) -> Body:
    """A JSON body with every omitted argument left out, so the server applies its default."""
    return {name: value for name, value in fields.items() if value is not None}


def _list_new_listings(
    chain: str, *, stage: BirdeyeListingStageParam = "new"
) -> Request[BirdeyeNewListings]:
    return Request(
        encode_path(_PREFIX + "/chains/{chain}/new-listings", chain=chain),
        BirdeyeNewListings,
        {"stage": stage},
    )


def _list_token_markets(
    chain: str,
    address: str,
    *,
    order: BirdeyeSortOrderParam = "desc",
    sort_by: BirdeyeMarketSortParam = "volume_24h",
) -> Request[BirdeyeTokenMarkets]:
    return Request(
        encode_path(
            _PREFIX + "/chains/{chain}/tokens/{address}/markets", chain=chain, address=address
        ),
        BirdeyeTokenMarkets,
        {"order": order, "sort_by": sort_by},
    )


def _get_token_ohlcv(
    chain: str,
    address: str,
    *,
    count: int = 300,
    interval: BirdeyeCandleIntervalParam = "15m",
    to: int | None = None,
) -> Request[BirdeyeOhlcv]:
    return Request(
        encode_path(
            _PREFIX + "/chains/{chain}/tokens/{address}/ohlcv", chain=chain, address=address
        ),
        BirdeyeOhlcv,
        {"count": count, "interval": interval, "to": to},
    )


def _get_token_overview(chain: str, address: str) -> Request[BirdeyeTokenOverview]:
    return Request(
        encode_path(
            _PREFIX + "/chains/{chain}/tokens/{address}/overview", chain=chain, address=address
        ),
        BirdeyeTokenOverview,
    )


def _get_token_security(chain: str, address: str) -> Request[BirdeyeTokenSecurity]:
    return Request(
        encode_path(
            _PREFIX + "/chains/{chain}/tokens/{address}/security", chain=chain, address=address
        ),
        BirdeyeTokenSecurity,
    )


def _list_top_traders(
    chain: str,
    address: str,
    *,
    cursor: str = "",
    limit: int = 20,
    order: BirdeyeSortOrderParam = "desc",
    sort_by: BirdeyeTraderSortParam = "total_pnl",
) -> Request[BirdeyeTopTradersPage]:
    return Request(
        encode_path(
            _PREFIX + "/chains/{chain}/tokens/{address}/top-traders", chain=chain, address=address
        ),
        BirdeyeTopTradersPage,
        {"cursor": cursor, "limit": limit, "order": order, "sort_by": sort_by},
    )


def _list_token_trades(
    chain: str,
    address: str,
    *,
    cursor: str = "",
    limit: int = 50,
    side: BirdeyeTradeSideParam = "all",
) -> Request[BirdeyeTokenTradesPage]:
    return Request(
        encode_path(
            _PREFIX + "/chains/{chain}/tokens/{address}/trades", chain=chain, address=address
        ),
        BirdeyeTokenTradesPage,
        {"cursor": cursor, "limit": limit, "side": side},
    )


def _list_leaderboard(
    chain: str,
    *,
    cursor: str = "",
    interval: BirdeyeLeaderboardIntervalParam = "7d",
    limit: int = 20,
    order: BirdeyeSortOrderParam = "desc",
    sort_by: BirdeyeLeaderboardSortParam = "total_pnl",
) -> Request[BirdeyeLeaderboardPage]:
    return Request(
        encode_path(_PREFIX + "/chains/{chain}/traders/leaderboard", chain=chain),
        BirdeyeLeaderboardPage,
        {
            "cursor": cursor,
            "interval": interval,
            "limit": limit,
            "order": order,
            "sort_by": sort_by,
        },
    )


def _list_trending_tokens(chain: str) -> Request[BirdeyeTrendingTokens]:
    return Request(
        encode_path(_PREFIX + "/chains/{chain}/trending", chain=chain), BirdeyeTrendingTokens
    )


def _get_wallet_pnl_summary(
    chain: str, wallet: str, *, period: BirdeyePnlPeriodParam = "30d"
) -> Request[BirdeyeWalletPnlSummary]:
    return Request(
        encode_path(
            _PREFIX + "/chains/{chain}/wallets/{wallet}/pnl-summary", chain=chain, wallet=wallet
        ),
        BirdeyeWalletPnlSummary,
        {"period": period},
    )


def _list_wallet_tokens(
    chain: str,
    wallet: str,
    *,
    cursor: str = "",
    limit: int = 20,
    order: BirdeyeSortOrderParam = "desc",
    sort_by: BirdeyeWalletTokenSortParam = "last_trade",
) -> Request[BirdeyeWalletTokensPage]:
    return Request(
        encode_path(
            _PREFIX + "/chains/{chain}/wallets/{wallet}/tokens", chain=chain, wallet=wallet
        ),
        BirdeyeWalletTokensPage,
        {"cursor": cursor, "limit": limit, "order": order, "sort_by": sort_by},
    )


def _list_wallet_transactions(
    chain: str, wallet: str, *, cursor: str = "", limit: int = 20, token: str | None = None
) -> Request[BirdeyeWalletTransactionsPage]:
    return Request(
        encode_path(
            _PREFIX + "/chains/{chain}/wallets/{wallet}/transactions", chain=chain, wallet=wallet
        ),
        BirdeyeWalletTransactionsPage,
        {"cursor": cursor, "limit": limit, "token": token},
    )


def _list_first_buyers(address: str) -> Request[BirdeyeFirstBuyers]:
    return Request(
        encode_path(_PREFIX + "/solana/tokens/{address}/first-buyers", address=address),
        BirdeyeFirstBuyers,
    )


def _list_token_holders(address: str) -> Request[BirdeyeTokenHolders]:
    return Request(
        encode_path(_PREFIX + "/solana/tokens/{address}/holders", address=address),
        BirdeyeTokenHolders,
    )


def _get_net_worth_history(
    wallet: str, *, count: int = 30, interval: BirdeyeNetWorthIntervalParam = "1d"
) -> Request[BirdeyeNetWorthHistory]:
    return Request(
        encode_path(_PREFIX + "/solana/wallets/{wallet}/net-worth-history", wallet=wallet),
        BirdeyeNetWorthHistory,
        {"count": count, "interval": interval},
    )


def _get_wallet_portfolio(
    wallet: str, *, cursor: str = "", limit: int = 50
) -> Request[BirdeyeWalletPortfolioPage]:
    return Request(
        encode_path(_PREFIX + "/solana/wallets/{wallet}/portfolio", wallet=wallet),
        BirdeyeWalletPortfolioPage,
        {"cursor": cursor, "limit": limit},
    )


class Birdeye(AsyncAPIResource):
    """The Birdeye endpoints, awaitable.

    Reached as :attr:`~tapline.TaplineClient.birdeye`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    async def list_new_listings(
        self,
        chain: str,
        *,
        stage: BirdeyeListingStageParam = "new",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeNewListings:
        """Up to 30 launchpad tokens at one stage: `new` (newest first), `final_curve` (closest to graduating first, by `progress`), `migrated` (most recently graduated first). Costs 1 credit.

        Args:
            chain: See the API reference.
            stage: Launch stage.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeNewListings`.
        """
        return await self._send(_list_new_listings(chain, stage=stage), timeout=timeout)

    async def list_token_markets(
        self,
        chain: str,
        address: str,
        *,
        order: BirdeyeSortOrderParam = "desc",
        sort_by: BirdeyeMarketSortParam = "volume_24h",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenMarkets:
        """Every pool trading the token (up to 300): pool address, pair name (such as `JUP-SOL`), venue, liquidity and 24h volume. Pools without liquidity data sort first in ascending order. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            order: Sort direction.
            sort_by: Pool ordering.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenMarkets`.
        """
        return await self._send(
            _list_token_markets(chain, address, order=order, sort_by=sort_by), timeout=timeout
        )

    async def get_token_ohlcv(
        self,
        chain: str,
        address: str,
        *,
        count: int = 300,
        interval: BirdeyeCandleIntervalParam = "15m",
        to: int | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeOhlcv:
        """USD candles as parallel arrays, oldest first: `o`, `h`, `l`, `c`, `v` and unix seconds in `t`. Up to `count` bars ending before `to` (exclusive), or now when `to` is omitted. Intervals with no trades have no bar. An unknown token answers empty arrays. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            count: Number of candles.
            interval: Candle size.
            to: Last candle's unix time in seconds.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeOhlcv`.
        """
        return await self._send(
            _get_token_ohlcv(chain, address, count=count, interval=interval, to=to), timeout=timeout
        )

    async def get_token_overview(
        self,
        chain: str,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenOverview:
        """A token's market overview from birdeye: price, market cap, liquidity, supply, holder count, social links, and buy, sell, volume, wallet and view counts with change percentages over 30m to 24h windows. Some windows (6h, 12h) appear on Solana only. An address birdeye does not know answers 404. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenOverview`.
        """
        return await self._send(_get_token_overview(chain, address), timeout=timeout)

    async def get_token_security(
        self,
        chain: str,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenSecurity:
        """birdeye's token security checklist. `groups` lists the checks by severity group (Critical, High risk, Medium risk, Neutral); each row's `index` keys its result in the `birdeye` and `goplus` maps (value, level, message). birdeye computes the checks on first request: if it has none yet the route answers 503 (not charged); retry in a minute. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenSecurity`.
        """
        return await self._send(_get_token_security(chain, address), timeout=timeout)

    async def list_top_traders(
        self,
        chain: str,
        address: str,
        *,
        cursor: str = "",
        limit: int = 20,
        order: BirdeyeSortOrderParam = "desc",
        sort_by: BirdeyeTraderSortParam = "total_pnl",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTopTradersPage:
        """Wallets that traded the token ranked by PnL on it: realized and unrealized PnL, volumes, average buy and sell prices, current balance and birdeye's wallet tags. birdeye omits fields that are zero, false or empty. Costs 2 credits.

        Args:
            chain: See the API reference.
            address: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Traders per page.
            order: Sort direction.
            sort_by: Ranking field.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTopTradersPage`.
        """
        return await self._send(
            _list_top_traders(
                chain, address, cursor=cursor, limit=limit, order=order, sort_by=sort_by
            ),
            timeout=timeout,
        )

    async def list_token_trades(
        self,
        chain: str,
        address: str,
        *,
        cursor: str = "",
        limit: int = 50,
        side: BirdeyeTradeSideParam = "all",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenTradesPage:
        """A token's trades and liquidity events across every pool, newest first, with USD volume, price, wallet, venue and birdeye's wallet tags. The tape moves while you page, so a trade can repeat on the next page: dedupe by `id`. Pages stop before offset 10,000. An unknown token answers an empty page. Priced per page, not per trade. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Trades per page.
            side: Keep one kind of event: `buy`, `sell`, `trade` (buys and sells),
                `add`, `remove`, `liquidity` (adds and removes), or `all`.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenTradesPage`.
        """
        return await self._send(
            _list_token_trades(chain, address, cursor=cursor, limit=limit, side=side),
            timeout=timeout,
        )

    async def list_leaderboard(
        self,
        chain: str,
        *,
        cursor: str = "",
        interval: BirdeyeLeaderboardIntervalParam = "7d",
        limit: int = 20,
        order: BirdeyeSortOrderParam = "desc",
        sort_by: BirdeyeLeaderboardSortParam = "total_pnl",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeLeaderboardPage:
        """birdeye's trader leaderboard for a period: realized, unrealized and total PnL, volume, trade counts and wallet tags. birdeye omits fields that are zero, false or empty. Costs 2 credits.

        Args:
            chain: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            interval: Ranking period.
            limit: Traders per page.
            order: Sort direction.
            sort_by: Ranking field.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeLeaderboardPage`.
        """
        return await self._send(
            _list_leaderboard(
                chain, cursor=cursor, interval=interval, limit=limit, order=order, sort_by=sort_by
            ),
            timeout=timeout,
        )

    async def list_trending_tokens(
        self,
        chain: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTrendingTokens:
        """birdeye's 20 trending tokens on a chain, or across chains with `all`, with price, liquidity, volume and token metadata. `all` can include chains this API does not serve on other routes (such as `robinhood`); check each item's `network`. Costs 1 credit.

        Args:
            chain: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTrendingTokens`.
        """
        return await self._send(_list_trending_tokens(chain), timeout=timeout)

    async def get_wallet_pnl_summary(
        self,
        chain: str,
        wallet: str,
        *,
        period: BirdeyePnlPeriodParam = "30d",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeWalletPnlSummary:
        """A wallet's trading summary over `period`: realized, unrealized and total PnL, volumes, trade counts, average trade size, the distribution of returns per token and, when birdeye has them, win rate and average win and loss size. birdeye omits fields that are zero, false or empty. A wallet with no trades in the period answers 404. Costs 2 credits.

        Args:
            chain: See the API reference.
            wallet: See the API reference.
            period: Window the summary covers.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeWalletPnlSummary`.
        """
        return await self._send(
            _get_wallet_pnl_summary(chain, wallet, period=period), timeout=timeout
        )

    async def list_wallet_tokens(
        self,
        chain: str,
        wallet: str,
        *,
        cursor: str = "",
        limit: int = 20,
        order: BirdeyeSortOrderParam = "desc",
        sort_by: BirdeyeWalletTokenSortParam = "last_trade",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeWalletTokensPage:
        """Per-token PnL for every token a wallet traded: trade counts, volumes, realized and unrealized PnL, average prices and holding. birdeye omits fields that are zero, false or empty. Costs 2 credits.

        Args:
            chain: See the API reference.
            wallet: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Tokens per page.
            order: Sort direction.
            sort_by: Token ordering.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeWalletTokensPage`.
        """
        return await self._send(
            _list_wallet_tokens(
                chain, wallet, cursor=cursor, limit=limit, order=order, sort_by=sort_by
            ),
            timeout=timeout,
        )

    async def list_wallet_transactions(
        self,
        chain: str,
        wallet: str,
        *,
        cursor: str = "",
        limit: int = 20,
        token: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeWalletTransactionsPage:
        """A wallet's swaps, newest first, with both legs (token, amount, price) and USD value. A transaction that swaps through several tokens appears once per leg, so `tx_hash` can repeat. Pass `token` to keep swaps of one token. birdeye omits fields that are zero, false or empty. Costs 2 credits.

        Args:
            chain: See the API reference.
            wallet: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Swaps per page.
            token: Keep swaps of this token address only, in the chain's address
                format.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeWalletTransactionsPage`.
        """
        return await self._send(
            _list_wallet_transactions(chain, wallet, cursor=cursor, limit=limit, token=token),
            timeout=timeout,
        )

    async def list_first_buyers(
        self,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeFirstBuyers:
        """A Solana token's first buyers and what each did since: bought more, sold part, sold all or held, with amounts and PnL, plus a summary of the cohort. An unknown token answers an empty `buyers` list. Costs 2 credits.

        Args:
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeFirstBuyers`.
        """
        return await self._send(_list_first_buyers(address), timeout=timeout)

    async def list_token_holders(
        self,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenHolders:
        """A Solana token's top 100 holders with balance, USD value, the holder's net worth, SOL balance, first transaction time, funding source and wallet tags. An unknown token answers an empty `items` list. Costs 2 credits.

        Args:
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenHolders`.
        """
        return await self._send(_list_token_holders(address), timeout=timeout)

    async def get_net_worth_history(
        self,
        wallet: str,
        *,
        count: int = 30,
        interval: BirdeyeNetWorthIntervalParam = "1d",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeNetWorthHistory:
        """A Solana wallet's net worth over time, newest point first, one point per `interval` (at most 90). Points where birdeye has no value carry only `timestamp`. `net_worth_change_percent` is 999999 when the window starts at zero. An unknown wallet answers an empty `history` list. Costs 2 credits.

        Args:
            wallet: See the API reference.
            count: Number of points.
            interval: Spacing of the points.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeNetWorthHistory`.
        """
        return await self._send(
            _get_net_worth_history(wallet, count=count, interval=interval), timeout=timeout
        )

    async def get_wallet_portfolio(
        self,
        wallet: str,
        *,
        cursor: str = "",
        limit: int = 50,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeWalletPortfolioPage:
        """A Solana wallet's current token holdings by USD value, largest first, with the wallet's total value. An empty wallet answers an empty `items` list. Costs 2 credits.

        Args:
            wallet: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Holdings per page.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeWalletPortfolioPage`.
        """
        return await self._send(
            _get_wallet_portfolio(wallet, cursor=cursor, limit=limit), timeout=timeout
        )


class SyncBirdeye(SyncAPIResource):
    """The Birdeye endpoints, blocking.

    Reached as :attr:`~tapline.SyncTaplineClient.birdeye`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    def list_new_listings(
        self,
        chain: str,
        *,
        stage: BirdeyeListingStageParam = "new",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeNewListings:
        """Up to 30 launchpad tokens at one stage: `new` (newest first), `final_curve` (closest to graduating first, by `progress`), `migrated` (most recently graduated first). Costs 1 credit.

        Args:
            chain: See the API reference.
            stage: Launch stage.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeNewListings`.
        """
        return self._send(_list_new_listings(chain, stage=stage), timeout=timeout)

    def list_token_markets(
        self,
        chain: str,
        address: str,
        *,
        order: BirdeyeSortOrderParam = "desc",
        sort_by: BirdeyeMarketSortParam = "volume_24h",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenMarkets:
        """Every pool trading the token (up to 300): pool address, pair name (such as `JUP-SOL`), venue, liquidity and 24h volume. Pools without liquidity data sort first in ascending order. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            order: Sort direction.
            sort_by: Pool ordering.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenMarkets`.
        """
        return self._send(
            _list_token_markets(chain, address, order=order, sort_by=sort_by), timeout=timeout
        )

    def get_token_ohlcv(
        self,
        chain: str,
        address: str,
        *,
        count: int = 300,
        interval: BirdeyeCandleIntervalParam = "15m",
        to: int | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeOhlcv:
        """USD candles as parallel arrays, oldest first: `o`, `h`, `l`, `c`, `v` and unix seconds in `t`. Up to `count` bars ending before `to` (exclusive), or now when `to` is omitted. Intervals with no trades have no bar. An unknown token answers empty arrays. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            count: Number of candles.
            interval: Candle size.
            to: Last candle's unix time in seconds.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeOhlcv`.
        """
        return self._send(
            _get_token_ohlcv(chain, address, count=count, interval=interval, to=to), timeout=timeout
        )

    def get_token_overview(
        self,
        chain: str,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenOverview:
        """A token's market overview from birdeye: price, market cap, liquidity, supply, holder count, social links, and buy, sell, volume, wallet and view counts with change percentages over 30m to 24h windows. Some windows (6h, 12h) appear on Solana only. An address birdeye does not know answers 404. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenOverview`.
        """
        return self._send(_get_token_overview(chain, address), timeout=timeout)

    def get_token_security(
        self,
        chain: str,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenSecurity:
        """birdeye's token security checklist. `groups` lists the checks by severity group (Critical, High risk, Medium risk, Neutral); each row's `index` keys its result in the `birdeye` and `goplus` maps (value, level, message). birdeye computes the checks on first request: if it has none yet the route answers 503 (not charged); retry in a minute. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenSecurity`.
        """
        return self._send(_get_token_security(chain, address), timeout=timeout)

    def list_top_traders(
        self,
        chain: str,
        address: str,
        *,
        cursor: str = "",
        limit: int = 20,
        order: BirdeyeSortOrderParam = "desc",
        sort_by: BirdeyeTraderSortParam = "total_pnl",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTopTradersPage:
        """Wallets that traded the token ranked by PnL on it: realized and unrealized PnL, volumes, average buy and sell prices, current balance and birdeye's wallet tags. birdeye omits fields that are zero, false or empty. Costs 2 credits.

        Args:
            chain: See the API reference.
            address: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Traders per page.
            order: Sort direction.
            sort_by: Ranking field.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTopTradersPage`.
        """
        return self._send(
            _list_top_traders(
                chain, address, cursor=cursor, limit=limit, order=order, sort_by=sort_by
            ),
            timeout=timeout,
        )

    def list_token_trades(
        self,
        chain: str,
        address: str,
        *,
        cursor: str = "",
        limit: int = 50,
        side: BirdeyeTradeSideParam = "all",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenTradesPage:
        """A token's trades and liquidity events across every pool, newest first, with USD volume, price, wallet, venue and birdeye's wallet tags. The tape moves while you page, so a trade can repeat on the next page: dedupe by `id`. Pages stop before offset 10,000. An unknown token answers an empty page. Priced per page, not per trade. Costs 1 credit.

        Args:
            chain: See the API reference.
            address: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Trades per page.
            side: Keep one kind of event: `buy`, `sell`, `trade` (buys and sells),
                `add`, `remove`, `liquidity` (adds and removes), or `all`.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenTradesPage`.
        """
        return self._send(
            _list_token_trades(chain, address, cursor=cursor, limit=limit, side=side),
            timeout=timeout,
        )

    def list_leaderboard(
        self,
        chain: str,
        *,
        cursor: str = "",
        interval: BirdeyeLeaderboardIntervalParam = "7d",
        limit: int = 20,
        order: BirdeyeSortOrderParam = "desc",
        sort_by: BirdeyeLeaderboardSortParam = "total_pnl",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeLeaderboardPage:
        """birdeye's trader leaderboard for a period: realized, unrealized and total PnL, volume, trade counts and wallet tags. birdeye omits fields that are zero, false or empty. Costs 2 credits.

        Args:
            chain: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            interval: Ranking period.
            limit: Traders per page.
            order: Sort direction.
            sort_by: Ranking field.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeLeaderboardPage`.
        """
        return self._send(
            _list_leaderboard(
                chain, cursor=cursor, interval=interval, limit=limit, order=order, sort_by=sort_by
            ),
            timeout=timeout,
        )

    def list_trending_tokens(
        self,
        chain: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTrendingTokens:
        """birdeye's 20 trending tokens on a chain, or across chains with `all`, with price, liquidity, volume and token metadata. `all` can include chains this API does not serve on other routes (such as `robinhood`); check each item's `network`. Costs 1 credit.

        Args:
            chain: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTrendingTokens`.
        """
        return self._send(_list_trending_tokens(chain), timeout=timeout)

    def get_wallet_pnl_summary(
        self,
        chain: str,
        wallet: str,
        *,
        period: BirdeyePnlPeriodParam = "30d",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeWalletPnlSummary:
        """A wallet's trading summary over `period`: realized, unrealized and total PnL, volumes, trade counts, average trade size, the distribution of returns per token and, when birdeye has them, win rate and average win and loss size. birdeye omits fields that are zero, false or empty. A wallet with no trades in the period answers 404. Costs 2 credits.

        Args:
            chain: See the API reference.
            wallet: See the API reference.
            period: Window the summary covers.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeWalletPnlSummary`.
        """
        return self._send(_get_wallet_pnl_summary(chain, wallet, period=period), timeout=timeout)

    def list_wallet_tokens(
        self,
        chain: str,
        wallet: str,
        *,
        cursor: str = "",
        limit: int = 20,
        order: BirdeyeSortOrderParam = "desc",
        sort_by: BirdeyeWalletTokenSortParam = "last_trade",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeWalletTokensPage:
        """Per-token PnL for every token a wallet traded: trade counts, volumes, realized and unrealized PnL, average prices and holding. birdeye omits fields that are zero, false or empty. Costs 2 credits.

        Args:
            chain: See the API reference.
            wallet: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Tokens per page.
            order: Sort direction.
            sort_by: Token ordering.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeWalletTokensPage`.
        """
        return self._send(
            _list_wallet_tokens(
                chain, wallet, cursor=cursor, limit=limit, order=order, sort_by=sort_by
            ),
            timeout=timeout,
        )

    def list_wallet_transactions(
        self,
        chain: str,
        wallet: str,
        *,
        cursor: str = "",
        limit: int = 20,
        token: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeWalletTransactionsPage:
        """A wallet's swaps, newest first, with both legs (token, amount, price) and USD value. A transaction that swaps through several tokens appears once per leg, so `tx_hash` can repeat. Pass `token` to keep swaps of one token. birdeye omits fields that are zero, false or empty. Costs 2 credits.

        Args:
            chain: See the API reference.
            wallet: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Swaps per page.
            token: Keep swaps of this token address only, in the chain's address
                format.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeWalletTransactionsPage`.
        """
        return self._send(
            _list_wallet_transactions(chain, wallet, cursor=cursor, limit=limit, token=token),
            timeout=timeout,
        )

    def list_first_buyers(
        self,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeFirstBuyers:
        """A Solana token's first buyers and what each did since: bought more, sold part, sold all or held, with amounts and PnL, plus a summary of the cohort. An unknown token answers an empty `buyers` list. Costs 2 credits.

        Args:
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeFirstBuyers`.
        """
        return self._send(_list_first_buyers(address), timeout=timeout)

    def list_token_holders(
        self,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeTokenHolders:
        """A Solana token's top 100 holders with balance, USD value, the holder's net worth, SOL balance, first transaction time, funding source and wallet tags. An unknown token answers an empty `items` list. Costs 2 credits.

        Args:
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeTokenHolders`.
        """
        return self._send(_list_token_holders(address), timeout=timeout)

    def get_net_worth_history(
        self,
        wallet: str,
        *,
        count: int = 30,
        interval: BirdeyeNetWorthIntervalParam = "1d",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeNetWorthHistory:
        """A Solana wallet's net worth over time, newest point first, one point per `interval` (at most 90). Points where birdeye has no value carry only `timestamp`. `net_worth_change_percent` is 999999 when the window starts at zero. An unknown wallet answers an empty `history` list. Costs 2 credits.

        Args:
            wallet: See the API reference.
            count: Number of points.
            interval: Spacing of the points.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeNetWorthHistory`.
        """
        return self._send(
            _get_net_worth_history(wallet, count=count, interval=interval), timeout=timeout
        )

    def get_wallet_portfolio(
        self,
        wallet: str,
        *,
        cursor: str = "",
        limit: int = 50,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> BirdeyeWalletPortfolioPage:
        """A Solana wallet's current token holdings by USD value, largest first, with the wallet's total value. An empty wallet answers an empty `items` list. Costs 2 credits.

        Args:
            wallet: See the API reference.
            cursor: `pagination.next_cursor` from the previous page; empty for the
                first page. A cursor holds only a position, so send it with the same
                sort and filters as the page it came from. `pagination.completion`
                is `exhausted` at the last page and `depth_limit` where birdeye
                stops serving deeper pages.
            limit: Holdings per page.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.birdeye.BirdeyeWalletPortfolioPage`.
        """
        return self._send(
            _get_wallet_portfolio(wallet, cursor=cursor, limit=limit), timeout=timeout
        )
