# Generated by generate-client from spec/openapi.json. Do not edit.
# ruff: noqa: E501
"""The 2 Goplus endpoints, in awaitable and blocking form.

Each endpoint's request is built once, by the private functions below. Both
resources call the same builder, so the twins differ only in ``await``.
"""

from __future__ import annotations

from collections.abc import Mapping

from .._base_client import encode_path
from .._resource import AsyncAPIResource, Request, SyncAPIResource
from .._types import Body, NotGiven, Timeout, not_given
from ..goplus import (
    GetEvmTokenSecurityResponse,
    GetSolanaTokenSecurityResponse,
)

__all__ = ["Goplus", "SyncGoplus"]

_PREFIX = "/api/v1/goplus"


def _body(fields: Mapping[str, object]) -> Body:
    """A JSON body with every omitted argument left out, so the server applies its default."""
    return {name: value for name, value in fields.items() if value is not None}


def _get_evm_token_security(chain_id: str, address: str) -> Request[GetEvmTokenSecurityResponse]:
    return Request(
        encode_path(
            _PREFIX + "/evm/{chain_id}/tokens/{address}/security",
            chain_id=chain_id,
            address=address,
        ),
        GetEvmTokenSecurityResponse,
    )


def _get_solana_token_security(mint: str) -> Request[GetSolanaTokenSecurityResponse]:
    return Request(
        encode_path(_PREFIX + "/solana/tokens/{mint}/security", mint=mint),
        GetSolanaTokenSecurityResponse,
    )


class Goplus(AsyncAPIResource):
    """The Goplus endpoints, awaitable.

    Reached as :attr:`~tapline.TaplineClient.goplus`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    async def get_evm_token_security(
        self,
        chain_id: str,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetEvmTokenSecurityResponse:
        """GoPlus token security for one EVM token: honeypot, tax, owner and mint flags, top holders and liquidity. The GoPlus envelope is returned unchanged; read `code` (1 complete, 2 partial, 3 no contract code) and `result`, which is keyed by the lowercased address. Powered by GoPlus Security.

        Args:
            chain_id: See the API reference.
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.goplus.GetEvmTokenSecurityResponse`.
        """
        return await self._send(_get_evm_token_security(chain_id, address), timeout=timeout)

    async def get_solana_token_security(
        self,
        mint: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetSolanaTokenSecurityResponse:
        """GoPlus token security for one Solana mint: mint, freeze, close and metadata authorities, Token-2022 transfer fee and hook, top holders and liquidity. The GoPlus envelope is returned unchanged; read `code` and `result`, which is keyed by the mint. Powered by GoPlus Security.

        Args:
            mint: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.goplus.GetSolanaTokenSecurityResponse`.
        """
        return await self._send(_get_solana_token_security(mint), timeout=timeout)


class SyncGoplus(SyncAPIResource):
    """The Goplus endpoints, blocking.

    Reached as :attr:`~tapline.SyncTaplineClient.goplus`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    def get_evm_token_security(
        self,
        chain_id: str,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetEvmTokenSecurityResponse:
        """GoPlus token security for one EVM token: honeypot, tax, owner and mint flags, top holders and liquidity. The GoPlus envelope is returned unchanged; read `code` (1 complete, 2 partial, 3 no contract code) and `result`, which is keyed by the lowercased address. Powered by GoPlus Security.

        Args:
            chain_id: See the API reference.
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.goplus.GetEvmTokenSecurityResponse`.
        """
        return self._send(_get_evm_token_security(chain_id, address), timeout=timeout)

    def get_solana_token_security(
        self,
        mint: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetSolanaTokenSecurityResponse:
        """GoPlus token security for one Solana mint: mint, freeze, close and metadata authorities, Token-2022 transfer fee and hook, top holders and liquidity. The GoPlus envelope is returned unchanged; read `code` and `result`, which is keyed by the mint. Powered by GoPlus Security.

        Args:
            mint: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.goplus.GetSolanaTokenSecurityResponse`.
        """
        return self._send(_get_solana_token_security(mint), timeout=timeout)
