# Generated by generate-client from spec/openapi.json. Do not edit.
# ruff: noqa: E501
"""The 12 Instagram endpoints, in awaitable and blocking form.

Each endpoint's request is built once, by the private functions below. Both
resources call the same builder, so the twins differ only in ``await``.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Literal

from .._resource import AsyncAPIResource, Request, SyncAPIResource
from .._types import Body, NotGiven, Timeout, not_given
from ..instagram import (
    InstagramAudioReelsResponse,
    InstagramBasicProfileResponse,
    InstagramCommentsResponse,
    InstagramEmbedResponse,
    InstagramHighlightDetailResponse,
    InstagramHighlightsResponse,
    InstagramPopularSearchResponse,
    InstagramPostCountResponse,
    InstagramPostResponse,
    InstagramProfileResponse,
    InstagramUserPostsResponse,
    InstagramUserReelsResponse,
)

__all__ = ["Instagram", "SyncInstagram"]

_PREFIX = "/v"


def _body(fields: Mapping[str, object]) -> Body:
    """A JSON body with every omitted argument left out, so the server applies its default."""
    return {name: value for name, value in fields.items() if value is not None}


def _get_audio_reels(
    *, audio_id: str, cursor: str | None = None
) -> Request[InstagramAudioReelsResponse]:
    return Request(
        _PREFIX + "1/instagram/audio/reels",
        InstagramAudioReelsResponse,
        {"audio_id": audio_id, "cursor": cursor},
    )


def _get_basic_profile(
    *, user_id: str, cache_max_age: Literal["1d", "3d", "7d", "14d", "30d"] | None = None
) -> Request[InstagramBasicProfileResponse]:
    return Request(
        _PREFIX + "1/instagram/basic-profile",
        InstagramBasicProfileResponse,
        {"userId": user_id, "cache_max_age": cache_max_age},
    )


def _get_post(
    *,
    url: str,
    cache_max_age: Literal["1d", "3d", "7d", "14d", "30d"] | None = None,
    download_media: Literal[False] | None = None,
    include_play_count: bool = True,
    region: str | None = None,
    trim: bool = False,
) -> Request[InstagramPostResponse]:
    return Request(
        _PREFIX + "1/instagram/post",
        InstagramPostResponse,
        {
            "url": url,
            "cache_max_age": cache_max_age,
            "download_media": download_media,
            "include_play_count": include_play_count,
            "region": region,
            "trim": trim,
        },
    )


def _get_profile(
    *,
    handle: str,
    cache_max_age: Literal["1d", "3d", "7d", "14d", "30d"] | None = None,
    trim: bool = False,
) -> Request[InstagramProfileResponse]:
    return Request(
        _PREFIX + "1/instagram/profile",
        InstagramProfileResponse,
        {"handle": handle, "cache_max_age": cache_max_age, "trim": trim},
    )


def _get_post_count(
    *, handle: str, allow_estimated: bool | None = None
) -> Request[InstagramPostCountResponse]:
    return Request(
        _PREFIX + "1/instagram/profile/post-count",
        InstagramPostCountResponse,
        {"handle": handle, "allow_estimated": allow_estimated},
    )


def _search_popular(
    *, query: str, cursor: str | None = None
) -> Request[InstagramPopularSearchResponse]:
    return Request(
        _PREFIX + "1/instagram/search/popular",
        InstagramPopularSearchResponse,
        {"query": query, "cursor": cursor},
    )


def _get_embed(*, handle: str) -> Request[InstagramEmbedResponse]:
    return Request(_PREFIX + "1/instagram/user/embed", InstagramEmbedResponse, {"handle": handle})


def _get_highlight_detail(*, id: str) -> Request[InstagramHighlightDetailResponse]:
    return Request(
        _PREFIX + "1/instagram/user/highlight/detail", InstagramHighlightDetailResponse, {"id": id}
    )


def _get_highlights(
    *, handle: str | None = None, user_id: str | None = None
) -> Request[InstagramHighlightsResponse]:
    if handle is None and user_id is None:
        raise ValueError("one of handle, user_id is required")
    return Request(
        _PREFIX + "1/instagram/user/highlights",
        InstagramHighlightsResponse,
        {"handle": handle, "user_id": user_id},
    )


def _get_user_reels(
    *,
    handle: str | None = None,
    max_id: str | None = None,
    trim: bool = False,
    user_id: str | None = None,
) -> Request[InstagramUserReelsResponse]:
    if handle is None and user_id is None:
        raise ValueError("one of handle, user_id is required")
    return Request(
        _PREFIX + "1/instagram/user/reels",
        InstagramUserReelsResponse,
        {"handle": handle, "max_id": max_id, "trim": trim, "user_id": user_id},
    )


def _get_post_comments(
    *, url: str, cursor: str | None = None, include_replies: Literal[False] | None = None
) -> Request[InstagramCommentsResponse]:
    return Request(
        _PREFIX + "2/instagram/post/comments",
        InstagramCommentsResponse,
        {"url": url, "cursor": cursor, "include_replies": include_replies},
    )


def _get_user_posts(
    *, handle: str, next_max_id: str | None = None, trim: bool = False
) -> Request[InstagramUserPostsResponse]:
    return Request(
        _PREFIX + "2/instagram/user/posts",
        InstagramUserPostsResponse,
        {"handle": handle, "next_max_id": next_max_id, "trim": trim},
    )


class Instagram(AsyncAPIResource):
    """The Instagram endpoints, awaitable.

    Reached as :attr:`~tapline.TaplineClient.instagram`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    async def get_audio_reels(
        self,
        *,
        audio_id: str,
        cursor: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramAudioReelsResponse:
        """Reels that use an audio track, from instagram.com/reels/audio/<audio_id>/: Instagram's media objects with play counts, video versions and creators. Pass `cursor` back while `has_more` is true. Costs 1 credit.

        Args:
            audio_id: The audio id from an audio page URL,
                instagram.com/reels/audio/<audio_id>/.
            cursor: The `cursor` from the previous page. Omit it for the first page.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramAudioReelsResponse`.
        """
        return await self._send(_get_audio_reels(audio_id=audio_id, cursor=cursor), timeout=timeout)

    async def get_basic_profile(
        self,
        *,
        user_id: str,
        cache_max_age: Literal["1d", "3d", "7d", "14d", "30d"] | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramBasicProfileResponse:
        """A profile summary by numeric user id: username, full name, biography, bio links, profile picture (standard and HD), verification, privacy, follower and following counts and account type. The body is Instagram's profile object at the top level. Costs 1 credit.

        Args:
            user_id: Numeric Instagram user id.
            cache_max_age: Accepted for Scrape Creators compatibility. It has no
                effect: every request fetches a live answer and is charged.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramBasicProfileResponse`.
        """
        return await self._send(
            _get_basic_profile(user_id=user_id, cache_max_age=cache_max_age), timeout=timeout
        )

    async def get_post(
        self,
        *,
        url: str,
        cache_max_age: Literal["1d", "3d", "7d", "14d", "30d"] | None = None,
        download_media: Literal[False] | None = None,
        include_play_count: bool = True,
        region: str | None = None,
        trim: bool = False,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramPostResponse:
        """One post or reel in Scrape Creators' `xdt_shortcode_media` shape: caption, like and comment counts, image and video URLs, owner, tagged users, carousel children, the first page of comments and, for videos, `video_play_count` (Instagram-only plays) and `video_duration`. `created_at` is ISO 8601 and `taken_at_timestamp` the Unix time. `include_play_count=false` skips the play-count lookup. `trim=true` answers `xdt_shortcode_media` at the top level with Scrape Creators' trimmed fields. Costs 2 credits.

        Args:
            url: Instagram post or reel URL:
                https://www.instagram.com/p/<shortcode>/, /reel/<shortcode>/,
                /reels/<shortcode>/ or /tv/<shortcode>/, on instagram.com or
                instagr.am. Query strings are allowed.
            cache_max_age: Accepted for Scrape Creators compatibility. It has no
                effect: every request fetches a live answer and is charged.
            download_media: Accepted for Scrape Creators compatibility only as
                false: Tapline does not re-host media.
            include_play_count: Set to false to omit `video_play_count` and skip the
                extra lookup it needs. Defaults to true. Only videos carry a play
                count.
            region: Two-letter country code for the exit the request leaves from.
                Defaults to US, where Instagram shows licensed music.
            trim: Set to true for Scrape Creators' trimmed answer: fewer fields per
                item, same values.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramPostResponse`.
        """
        return await self._send(
            _get_post(
                url=url,
                cache_max_age=cache_max_age,
                download_media=download_media,
                include_play_count=include_play_count,
                region=region,
                trim=trim,
            ),
            timeout=timeout,
        )

    async def get_profile(
        self,
        *,
        handle: str,
        cache_max_age: Literal["1d", "3d", "7d", "14d", "30d"] | None = None,
        trim: bool = False,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramProfileResponse:
        """A public Instagram profile in Scrape Creators' `/v1/instagram/profile` shape: biography, bio links, follower and following counts, verification, profile pictures and the 12 newest posts under `data.user.edge_owner_to_timeline_media` (pinned first). `edge_owner_to_timeline_media.count` is the size of that batch, not the account's post total; use `/v1/instagram/profile/post-count` for the total. Fields the logged-out web does not show (business contact details, category, highlight count) carry Scrape Creators' defaults. A private account answers its profile with an empty timeline. With `trim=true` the user object keeps Scrape Creators' trimmed field set. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @.
            cache_max_age: Accepted for Scrape Creators compatibility. It has no
                effect: every request fetches a live answer and is charged.
            trim: Set to true for Scrape Creators' trimmed answer: fewer fields per
                item, same values.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramProfileResponse`.
        """
        return await self._send(
            _get_profile(handle=handle, cache_max_age=cache_max_age, trim=trim), timeout=timeout
        )

    async def get_post_count(
        self,
        *,
        handle: str,
        allow_estimated: bool | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramPostCountResponse:
        """The exact number of posts on a public profile. `is_estimated` is always false: Tapline reads the exact count, so `allow_estimated` has no effect. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @.
            allow_estimated: Accepted for Scrape Creators compatibility. It has no
                effect: Tapline always answers the exact count.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramPostCountResponse`.
        """
        return await self._send(
            _get_post_count(handle=handle, allow_estimated=allow_estimated), timeout=timeout
        )

    async def search_popular(
        self,
        *,
        query: str,
        cursor: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramPopularSearchResponse:
        """Instagram's public popular page for a topic. The first page carries the topic title, Instagram's generated description, suggested related searches and 12 posts; pass `cursor` back for 12 more. Instagram no longer publishes a post total or the description's sources there, so `total_media_count` is null and `source_uris` empty. Costs 2 credits.

        Args:
            query: The topic to look up, such as basketball.
            cursor: The `cursor` from the previous page. Omit it for the first page.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramPopularSearchResponse`.
        """
        return await self._send(_search_popular(query=query, cursor=cursor), timeout=timeout)

    async def get_embed(
        self,
        *,
        handle: str,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramEmbedResponse:
        """The HTML of Instagram's embeddable profile widget, instagram.com/<handle>/embed/, as one string. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramEmbedResponse`.
        """
        return await self._send(_get_embed(handle=handle), timeout=timeout)

    async def get_highlight_detail(
        self,
        *,
        id: str,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramHighlightDetailResponse:
        """Everything in one story highlight: cover, title, owner and every story item with its media type, image and video versions, dimensions, timestamps and stickers. The body is Instagram's reel object at the top level. Costs 1 credit.

        Args:
            id: The highlight id from `/v1/instagram/user/highlights`, with or
                without the `highlight:` prefix.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramHighlightDetailResponse`.
        """
        return await self._send(_get_highlight_detail(id=id), timeout=timeout)

    async def get_highlights(
        self,
        *,
        handle: str | None = None,
        user_id: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramHighlightsResponse:
        """The story highlight albums a logged-out visitor sees on a profile: id, title, cover image and owner. Send `handle` or `user_id`; `handle` answers faster here, `user_id` costs one extra lookup. Instagram shows logged-out visitors only some albums and no way to page through the rest. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @. Send this or
                `user_id`.
            user_id: Numeric Instagram user id. Send this or `handle`; when both are
                sent, `user_id` wins.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramHighlightsResponse`.
        """
        return await self._send(_get_highlights(handle=handle, user_id=user_id), timeout=timeout)

    async def get_user_reels(
        self,
        *,
        handle: str | None = None,
        max_id: str | None = None,
        trim: bool = False,
        user_id: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramUserReelsResponse:
        """A page of a user's reels: each `items[].media` is Instagram's media object with play, like and comment counts, video versions, thumbnails, `url` and an ISO 8601 `created_at`. Instagram leaves the caption out of this list. Pass `paging_info.max_id` back as `max_id` for the next page. Send `user_id` for a faster answer: `handle` costs one extra lookup. `trim=true` answers flat items and a top-level `max_id`. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @. Send this or
                `user_id`.
            max_id: The `paging_info.max_id` (or trimmed `max_id`) from the previous
                page. Omit it for the first page. It is base64, so percent-encode
                `+` and `/` in a hand-built URL.
            trim: Set to true for Scrape Creators' trimmed answer: fewer fields per
                item, same values.
            user_id: Numeric Instagram user id. Send this or `handle`; when both are
                sent, `user_id` wins.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramUserReelsResponse`.
        """
        return await self._send(
            _get_user_reels(handle=handle, max_id=max_id, trim=trim, user_id=user_id),
            timeout=timeout,
        )

    async def get_post_comments(
        self,
        *,
        url: str,
        cursor: str | None = None,
        include_replies: Literal[False] | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramCommentsResponse:
        """A page of up to 15 comments on a public post or reel: text, ISO 8601 `created_at`, like count and the commenter's id, username, verification and profile picture. Instagram does not show reply counts to logged-out visitors, so `child_comment_count` is null. Pass `cursor` back for the next page; it is null on the last one. Costs 1 credit.

        Args:
            url: Instagram post or reel URL:
                https://www.instagram.com/p/<shortcode>/, /reel/<shortcode>/,
                /reels/<shortcode>/ or /tv/<shortcode>/, on instagram.com or
                instagr.am. Query strings are allowed.
            cursor: The `cursor` from the previous page. Omit it for the first page.
            include_replies: Accepted for Scrape Creators compatibility only as
                false: Instagram does not show replies to logged-out visitors.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramCommentsResponse`.
        """
        return await self._send(
            _get_post_comments(url=url, cursor=cursor, include_replies=include_replies),
            timeout=timeout,
        )

    async def get_user_posts(
        self,
        *,
        handle: str,
        next_max_id: str | None = None,
        trim: bool = False,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramUserPostsResponse:
        """A page of 12 of a user's posts, newest first, as Instagram's feed returns them: media type, shortcode, caption, like, comment and play counts, image and video versions, tagged users, `url` and an ISO 8601 `created_at` (`taken_at` stays the Unix time). Pass `next_max_id` back for the next page while `more_available` is true. An unknown handle answers an empty page; a private account answers 404. `trim=true` keeps Scrape Creators' trimmed item fields. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @.
            next_max_id: The `next_max_id` from the previous page, or the
                `end_cursor` of `/v1/instagram/profile`'s timeline. Omit it for the
                first page.
            trim: Set to true for Scrape Creators' trimmed answer: fewer fields per
                item, same values.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramUserPostsResponse`.
        """
        return await self._send(
            _get_user_posts(handle=handle, next_max_id=next_max_id, trim=trim), timeout=timeout
        )


class SyncInstagram(SyncAPIResource):
    """The Instagram endpoints, blocking.

    Reached as :attr:`~tapline.SyncTaplineClient.instagram`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    def get_audio_reels(
        self,
        *,
        audio_id: str,
        cursor: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramAudioReelsResponse:
        """Reels that use an audio track, from instagram.com/reels/audio/<audio_id>/: Instagram's media objects with play counts, video versions and creators. Pass `cursor` back while `has_more` is true. Costs 1 credit.

        Args:
            audio_id: The audio id from an audio page URL,
                instagram.com/reels/audio/<audio_id>/.
            cursor: The `cursor` from the previous page. Omit it for the first page.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramAudioReelsResponse`.
        """
        return self._send(_get_audio_reels(audio_id=audio_id, cursor=cursor), timeout=timeout)

    def get_basic_profile(
        self,
        *,
        user_id: str,
        cache_max_age: Literal["1d", "3d", "7d", "14d", "30d"] | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramBasicProfileResponse:
        """A profile summary by numeric user id: username, full name, biography, bio links, profile picture (standard and HD), verification, privacy, follower and following counts and account type. The body is Instagram's profile object at the top level. Costs 1 credit.

        Args:
            user_id: Numeric Instagram user id.
            cache_max_age: Accepted for Scrape Creators compatibility. It has no
                effect: every request fetches a live answer and is charged.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramBasicProfileResponse`.
        """
        return self._send(
            _get_basic_profile(user_id=user_id, cache_max_age=cache_max_age), timeout=timeout
        )

    def get_post(
        self,
        *,
        url: str,
        cache_max_age: Literal["1d", "3d", "7d", "14d", "30d"] | None = None,
        download_media: Literal[False] | None = None,
        include_play_count: bool = True,
        region: str | None = None,
        trim: bool = False,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramPostResponse:
        """One post or reel in Scrape Creators' `xdt_shortcode_media` shape: caption, like and comment counts, image and video URLs, owner, tagged users, carousel children, the first page of comments and, for videos, `video_play_count` (Instagram-only plays) and `video_duration`. `created_at` is ISO 8601 and `taken_at_timestamp` the Unix time. `include_play_count=false` skips the play-count lookup. `trim=true` answers `xdt_shortcode_media` at the top level with Scrape Creators' trimmed fields. Costs 2 credits.

        Args:
            url: Instagram post or reel URL:
                https://www.instagram.com/p/<shortcode>/, /reel/<shortcode>/,
                /reels/<shortcode>/ or /tv/<shortcode>/, on instagram.com or
                instagr.am. Query strings are allowed.
            cache_max_age: Accepted for Scrape Creators compatibility. It has no
                effect: every request fetches a live answer and is charged.
            download_media: Accepted for Scrape Creators compatibility only as
                false: Tapline does not re-host media.
            include_play_count: Set to false to omit `video_play_count` and skip the
                extra lookup it needs. Defaults to true. Only videos carry a play
                count.
            region: Two-letter country code for the exit the request leaves from.
                Defaults to US, where Instagram shows licensed music.
            trim: Set to true for Scrape Creators' trimmed answer: fewer fields per
                item, same values.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramPostResponse`.
        """
        return self._send(
            _get_post(
                url=url,
                cache_max_age=cache_max_age,
                download_media=download_media,
                include_play_count=include_play_count,
                region=region,
                trim=trim,
            ),
            timeout=timeout,
        )

    def get_profile(
        self,
        *,
        handle: str,
        cache_max_age: Literal["1d", "3d", "7d", "14d", "30d"] | None = None,
        trim: bool = False,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramProfileResponse:
        """A public Instagram profile in Scrape Creators' `/v1/instagram/profile` shape: biography, bio links, follower and following counts, verification, profile pictures and the 12 newest posts under `data.user.edge_owner_to_timeline_media` (pinned first). `edge_owner_to_timeline_media.count` is the size of that batch, not the account's post total; use `/v1/instagram/profile/post-count` for the total. Fields the logged-out web does not show (business contact details, category, highlight count) carry Scrape Creators' defaults. A private account answers its profile with an empty timeline. With `trim=true` the user object keeps Scrape Creators' trimmed field set. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @.
            cache_max_age: Accepted for Scrape Creators compatibility. It has no
                effect: every request fetches a live answer and is charged.
            trim: Set to true for Scrape Creators' trimmed answer: fewer fields per
                item, same values.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramProfileResponse`.
        """
        return self._send(
            _get_profile(handle=handle, cache_max_age=cache_max_age, trim=trim), timeout=timeout
        )

    def get_post_count(
        self,
        *,
        handle: str,
        allow_estimated: bool | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramPostCountResponse:
        """The exact number of posts on a public profile. `is_estimated` is always false: Tapline reads the exact count, so `allow_estimated` has no effect. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @.
            allow_estimated: Accepted for Scrape Creators compatibility. It has no
                effect: Tapline always answers the exact count.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramPostCountResponse`.
        """
        return self._send(
            _get_post_count(handle=handle, allow_estimated=allow_estimated), timeout=timeout
        )

    def search_popular(
        self,
        *,
        query: str,
        cursor: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramPopularSearchResponse:
        """Instagram's public popular page for a topic. The first page carries the topic title, Instagram's generated description, suggested related searches and 12 posts; pass `cursor` back for 12 more. Instagram no longer publishes a post total or the description's sources there, so `total_media_count` is null and `source_uris` empty. Costs 2 credits.

        Args:
            query: The topic to look up, such as basketball.
            cursor: The `cursor` from the previous page. Omit it for the first page.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramPopularSearchResponse`.
        """
        return self._send(_search_popular(query=query, cursor=cursor), timeout=timeout)

    def get_embed(
        self,
        *,
        handle: str,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramEmbedResponse:
        """The HTML of Instagram's embeddable profile widget, instagram.com/<handle>/embed/, as one string. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramEmbedResponse`.
        """
        return self._send(_get_embed(handle=handle), timeout=timeout)

    def get_highlight_detail(
        self,
        *,
        id: str,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramHighlightDetailResponse:
        """Everything in one story highlight: cover, title, owner and every story item with its media type, image and video versions, dimensions, timestamps and stickers. The body is Instagram's reel object at the top level. Costs 1 credit.

        Args:
            id: The highlight id from `/v1/instagram/user/highlights`, with or
                without the `highlight:` prefix.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramHighlightDetailResponse`.
        """
        return self._send(_get_highlight_detail(id=id), timeout=timeout)

    def get_highlights(
        self,
        *,
        handle: str | None = None,
        user_id: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramHighlightsResponse:
        """The story highlight albums a logged-out visitor sees on a profile: id, title, cover image and owner. Send `handle` or `user_id`; `handle` answers faster here, `user_id` costs one extra lookup. Instagram shows logged-out visitors only some albums and no way to page through the rest. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @. Send this or
                `user_id`.
            user_id: Numeric Instagram user id. Send this or `handle`; when both are
                sent, `user_id` wins.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramHighlightsResponse`.
        """
        return self._send(_get_highlights(handle=handle, user_id=user_id), timeout=timeout)

    def get_user_reels(
        self,
        *,
        handle: str | None = None,
        max_id: str | None = None,
        trim: bool = False,
        user_id: str | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramUserReelsResponse:
        """A page of a user's reels: each `items[].media` is Instagram's media object with play, like and comment counts, video versions, thumbnails, `url` and an ISO 8601 `created_at`. Instagram leaves the caption out of this list. Pass `paging_info.max_id` back as `max_id` for the next page. Send `user_id` for a faster answer: `handle` costs one extra lookup. `trim=true` answers flat items and a top-level `max_id`. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @. Send this or
                `user_id`.
            max_id: The `paging_info.max_id` (or trimmed `max_id`) from the previous
                page. Omit it for the first page. It is base64, so percent-encode
                `+` and `/` in a hand-built URL.
            trim: Set to true for Scrape Creators' trimmed answer: fewer fields per
                item, same values.
            user_id: Numeric Instagram user id. Send this or `handle`; when both are
                sent, `user_id` wins.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramUserReelsResponse`.
        """
        return self._send(
            _get_user_reels(handle=handle, max_id=max_id, trim=trim, user_id=user_id),
            timeout=timeout,
        )

    def get_post_comments(
        self,
        *,
        url: str,
        cursor: str | None = None,
        include_replies: Literal[False] | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramCommentsResponse:
        """A page of up to 15 comments on a public post or reel: text, ISO 8601 `created_at`, like count and the commenter's id, username, verification and profile picture. Instagram does not show reply counts to logged-out visitors, so `child_comment_count` is null. Pass `cursor` back for the next page; it is null on the last one. Costs 1 credit.

        Args:
            url: Instagram post or reel URL:
                https://www.instagram.com/p/<shortcode>/, /reel/<shortcode>/,
                /reels/<shortcode>/ or /tv/<shortcode>/, on instagram.com or
                instagr.am. Query strings are allowed.
            cursor: The `cursor` from the previous page. Omit it for the first page.
            include_replies: Accepted for Scrape Creators compatibility only as
                false: Instagram does not show replies to logged-out visitors.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramCommentsResponse`.
        """
        return self._send(
            _get_post_comments(url=url, cursor=cursor, include_replies=include_replies),
            timeout=timeout,
        )

    def get_user_posts(
        self,
        *,
        handle: str,
        next_max_id: str | None = None,
        trim: bool = False,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> InstagramUserPostsResponse:
        """A page of 12 of a user's posts, newest first, as Instagram's feed returns them: media type, shortcode, caption, like, comment and play counts, image and video versions, tagged users, `url` and an ISO 8601 `created_at` (`taken_at` stays the Unix time). Pass `next_max_id` back for the next page while `more_available` is true. An unknown handle answers an empty page; a private account answers 404. `trim=true` keeps Scrape Creators' trimmed item fields. Costs 1 credit.

        Args:
            handle: Instagram handle, with or without a leading @.
            next_max_id: The `next_max_id` from the previous page, or the
                `end_cursor` of `/v1/instagram/profile`'s timeline. Omit it for the
                first page.
            trim: Set to true for Scrape Creators' trimmed answer: fewer fields per
                item, same values.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.instagram.InstagramUserPostsResponse`.
        """
        return self._send(
            _get_user_posts(handle=handle, next_max_id=next_max_id, trim=trim), timeout=timeout
        )
