# Generated by generate-client from spec/openapi.json. Do not edit.
# ruff: noqa: E501
"""The 37 Ponsfamily endpoints, in awaitable and blocking form.

Each endpoint's request is built once, by the private functions below. Both
resources call the same builder, so the twins differ only in ``await``.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

from .._base_client import encode_path
from .._resource import AsyncAPIResource, Request, SyncAPIResource
from .._types import Body, NotGiven, Timeout, not_given
from ..ponsfamily import (
    ChartRangeParam,
    CommunityRankParam,
    CreatorHoldingPair,
    GetAnalyticsResponse,
    GetCreatorHoldingsResponse,
    GetDeveloperTradesResponse,
    GetEthPriceResponse,
    GetFeeSharingResponse,
    GetForumCommunityResponse,
    GetForumHoldingResponse,
    GetForumMarketResponse,
    GetForumPostCommentsResponse,
    GetForumPostResponse,
    GetMarketAthResponse,
    GetMarketBurnedResponse,
    GetMarketChartResponse,
    GetMarketHoldersResponse,
    GetMarketOrderDepthResponse,
    GetMarketResponse,
    GetMarketTipResponse,
    GetPortfolioChartResponse,
    GetProfileResponse,
    GetTokenImagesResponse,
    GetTokenResponse,
    GetV2CreatorFeesResponse,
    GetV2DistributorResponse,
    GetV2MarketChartResponse,
    GetV2MarketHoldersResponse,
    GetV2MarketTradesResponse,
    GetWalletIdentitiesResponse,
    GetWalletPositionsResponse,
    Graduation,
    Launch,
    LaunchAgeParam,
    LaunchSearchSortParam,
    LaunchSortParam,
    LaunchVersionParam,
    ListCtoMigrationsResponse,
    ListForumCommunitiesResponse,
    ListForumPostsResponse,
    ListLaunchesResponse,
    LiveMarket,
    MarketTrade,
    PortfolioRangeParam,
    PostSortParam,
    SearchLaunchesResponse,
)

__all__ = ["Ponsfamily", "SyncPonsfamily"]

_PREFIX = "/api/v1/ponsfamily"


def _body(fields: Mapping[str, object]) -> Body:
    """A JSON body with every omitted argument left out, so the server applies its default."""
    return {name: value for name, value in fields.items() if value is not None}


def _get_analytics() -> Request[GetAnalyticsResponse]:
    return Request(_PREFIX + "/analytics", GetAnalyticsResponse)


def _list_cto_migrations() -> Request[ListCtoMigrationsResponse]:
    return Request(_PREFIX + "/cto-migrations", ListCtoMigrationsResponse)


def _get_eth_price() -> Request[GetEthPriceResponse]:
    return Request(_PREFIX + "/eth-price", GetEthPriceResponse)


def _list_forum_communities(
    *, limit: int = 10, rank: CommunityRankParam = "marketCap"
) -> Request[ListForumCommunitiesResponse]:
    return Request(
        _PREFIX + "/forum/communities", ListForumCommunitiesResponse, {"limit": limit, "rank": rank}
    )


def _get_forum_community(slug: str) -> Request[GetForumCommunityResponse]:
    return Request(
        encode_path(_PREFIX + "/forum/communities/{slug}", slug=slug), GetForumCommunityResponse
    )


def _get_forum_holding(token: str, wallet: str) -> Request[GetForumHoldingResponse]:
    return Request(
        encode_path(_PREFIX + "/forum/holdings/{token}/{wallet}", token=token, wallet=wallet),
        GetForumHoldingResponse,
    )


def _get_forum_market() -> Request[GetForumMarketResponse]:
    return Request(_PREFIX + "/forum/market", GetForumMarketResponse)


def _list_forum_posts(
    *, community: str | None = None, sort: PostSortParam = "hot"
) -> Request[ListForumPostsResponse]:
    return Request(
        _PREFIX + "/forum/posts", ListForumPostsResponse, {"community": community, "sort": sort}
    )


def _get_forum_post(post_id: str) -> Request[GetForumPostResponse]:
    return Request(
        encode_path(_PREFIX + "/forum/posts/{post_id}", post_id=post_id), GetForumPostResponse
    )


def _get_forum_post_comments(
    post_id: str, *, sort: PostSortParam = "hot"
) -> Request[GetForumPostCommentsResponse]:
    return Request(
        encode_path(_PREFIX + "/forum/posts/{post_id}/comments", post_id=post_id),
        GetForumPostCommentsResponse,
        {"sort": sort},
    )


def _list_launches(
    *,
    age: LaunchAgeParam = "all",
    graduated_page: int = 1,
    graduated_page_size: int = 10,
    include_graduated: bool = True,
    page: int = 1,
    page_size: int = 50,
    sort: LaunchSortParam = "recentBuys",
    version: LaunchVersionParam = "all",
) -> Request[ListLaunchesResponse]:
    return Request(
        _PREFIX + "/launches",
        ListLaunchesResponse,
        {
            "age": age,
            "graduated_page": graduated_page,
            "graduated_page_size": graduated_page_size,
            "include_graduated": include_graduated,
            "page": page,
            "page_size": page_size,
            "sort": sort,
            "version": version,
        },
    )


def _list_graduated_catalog() -> Request[list[Launch]]:
    return Request(_PREFIX + "/launches/graduated", list[Launch])


def _list_graduations() -> Request[list[Graduation]]:
    return Request(_PREFIX + "/launches/graduations", list[Graduation])


def _list_live_markets(*, markets: Sequence[str] | None = None) -> Request[list[LiveMarket]]:
    return Request(_PREFIX + "/launches/live-markets", list[LiveMarket], {"markets": markets})


def _search_launches(
    *,
    age: LaunchAgeParam = "all",
    page: int = 1,
    q: str = "",
    sort: LaunchSearchSortParam = "relevance",
) -> Request[SearchLaunchesResponse]:
    return Request(
        _PREFIX + "/launches/search",
        SearchLaunchesResponse,
        {"age": age, "page": page, "q": q, "sort": sort},
    )


def _get_market(token: str, *, include_holders: bool = False) -> Request[GetMarketResponse]:
    return Request(
        encode_path(_PREFIX + "/markets/{token}", token=token),
        GetMarketResponse,
        {"include_holders": include_holders},
    )


def _get_market_ath(token: str) -> Request[GetMarketAthResponse]:
    return Request(encode_path(_PREFIX + "/markets/{token}/ath", token=token), GetMarketAthResponse)


def _get_market_burned(token: str) -> Request[GetMarketBurnedResponse]:
    return Request(
        encode_path(_PREFIX + "/markets/{token}/burned", token=token), GetMarketBurnedResponse
    )


def _get_market_chart(
    token: str, *, range: ChartRangeParam = "1h"
) -> Request[GetMarketChartResponse]:
    return Request(
        encode_path(_PREFIX + "/markets/{token}/chart", token=token),
        GetMarketChartResponse,
        {"range": range},
    )


def _get_developer_trades(token: str, *, deployer: str) -> Request[GetDeveloperTradesResponse]:
    return Request(
        encode_path(_PREFIX + "/markets/{token}/dev-trades", token=token),
        GetDeveloperTradesResponse,
        {"deployer": deployer},
    )


def _get_market_holders(token: str) -> Request[GetMarketHoldersResponse]:
    return Request(
        encode_path(_PREFIX + "/markets/{token}/holders", token=token), GetMarketHoldersResponse
    )


def _get_market_order_depth(token: str) -> Request[GetMarketOrderDepthResponse]:
    return Request(
        encode_path(_PREFIX + "/markets/{token}/order-depth", token=token),
        GetMarketOrderDepthResponse,
    )


def _get_market_tip(token: str) -> Request[GetMarketTipResponse]:
    return Request(encode_path(_PREFIX + "/markets/{token}/tip", token=token), GetMarketTipResponse)


def _get_market_trades(token: str) -> Request[list[MarketTrade]]:
    return Request(encode_path(_PREFIX + "/markets/{token}/trades", token=token), list[MarketTrade])


def _get_creator_holdings(
    *, pairs: Sequence[CreatorHoldingPair]
) -> Request[GetCreatorHoldingsResponse]:
    return Request(
        _PREFIX + "/tokens/creator-holdings",
        GetCreatorHoldingsResponse,
        method="POST",
        json=_body({"pairs": pairs}),
    )


def _get_fee_sharing(*, tokens: Sequence[str]) -> Request[GetFeeSharingResponse]:
    return Request(_PREFIX + "/tokens/fee-sharing", GetFeeSharingResponse, {"tokens": tokens})


def _get_token_images(*, tokens: Sequence[str]) -> Request[GetTokenImagesResponse]:
    return Request(_PREFIX + "/tokens/images", GetTokenImagesResponse, {"tokens": tokens})


def _get_token(token: str) -> Request[GetTokenResponse]:
    return Request(encode_path(_PREFIX + "/tokens/{token}", token=token), GetTokenResponse)


def _get_v2_market_chart(
    token: str, *, range: ChartRangeParam = "1h"
) -> Request[GetV2MarketChartResponse]:
    return Request(
        encode_path(_PREFIX + "/v2-markets/{token}/chart", token=token),
        GetV2MarketChartResponse,
        {"range": range},
    )


def _get_v2_creator_fees(token: str) -> Request[GetV2CreatorFeesResponse]:
    return Request(
        encode_path(_PREFIX + "/v2-markets/{token}/creator-fees", token=token),
        GetV2CreatorFeesResponse,
    )


def _get_v2_distributor(token: str) -> Request[GetV2DistributorResponse]:
    return Request(
        encode_path(_PREFIX + "/v2-markets/{token}/distributor", token=token),
        GetV2DistributorResponse,
    )


def _get_v2_market_holders(token: str) -> Request[GetV2MarketHoldersResponse]:
    return Request(
        encode_path(_PREFIX + "/v2-markets/{token}/holders", token=token),
        GetV2MarketHoldersResponse,
    )


def _get_v2_market_trades(token: str) -> Request[GetV2MarketTradesResponse]:
    return Request(
        encode_path(_PREFIX + "/v2-markets/{token}/trades", token=token), GetV2MarketTradesResponse
    )


def _get_wallet_identities(*, addresses: Sequence[str]) -> Request[GetWalletIdentitiesResponse]:
    return Request(
        _PREFIX + "/wallets/identities", GetWalletIdentitiesResponse, {"addresses": addresses}
    )


def _get_portfolio_chart(
    address: str, *, range: PortfolioRangeParam = "1d"
) -> Request[GetPortfolioChartResponse]:
    return Request(
        encode_path(_PREFIX + "/wallets/{address}/portfolio-chart", address=address),
        GetPortfolioChartResponse,
        {"range": range},
    )


def _get_wallet_positions(address: str) -> Request[GetWalletPositionsResponse]:
    return Request(
        encode_path(_PREFIX + "/wallets/{address}/positions", address=address),
        GetWalletPositionsResponse,
    )


def _get_profile(address: str) -> Request[GetProfileResponse]:
    return Request(
        encode_path(_PREFIX + "/wallets/{address}/profile", address=address), GetProfileResponse
    )


class Ponsfamily(AsyncAPIResource):
    """The Ponsfamily endpoints, awaitable.

    Reached as :attr:`~tapline.TaplineClient.ponsfamily`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    async def get_analytics(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetAnalyticsResponse:
        """Protocol-wide launch, volume, trade and revenue totals plus the daily series behind them. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetAnalyticsResponse`.
        """
        return await self._send(_get_analytics(), timeout=timeout)

    async def list_cto_migrations(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ListCtoMigrationsResponse:
        """Community-takeover migrations: the old and new token, the deposit/claim schedule and how much has been migrated. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.ListCtoMigrationsResponse`.
        """
        return await self._send(_list_cto_migrations(), timeout=timeout)

    async def get_eth_price(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetEthPriceResponse:
        """The ETH/USD rate pons prices every launch with. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetEthPriceResponse`.
        """
        return await self._send(_get_eth_price(), timeout=timeout)

    async def list_forum_communities(
        self,
        *,
        limit: int = 10,
        rank: CommunityRankParam = "marketCap",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ListForumCommunitiesResponse:
        """Token communities ranked by market cap, burn share or real market cap. Costs 2 credits.

        Args:
            limit: Number of communities to return.
            rank: Ranking column.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.ListForumCommunitiesResponse`.
        """
        return await self._send(_list_forum_communities(limit=limit, rank=rank), timeout=timeout)

    async def get_forum_community(
        self,
        slug: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumCommunityResponse:
        """One token community with its supply, burn and market-cap figures. Costs 2 credits.

        Args:
            slug: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumCommunityResponse`.
        """
        return await self._send(_get_forum_community(slug), timeout=timeout)

    async def get_forum_holding(
        self,
        token: str,
        wallet: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumHoldingResponse:
        """A wallet's balance in a community token and the posting tier that balance earns it. Costs 2 credits.

        Args:
            token: See the API reference.
            wallet: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumHoldingResponse`.
        """
        return await self._send(_get_forum_holding(token, wallet), timeout=timeout)

    async def get_forum_market(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumMarketResponse:
        """The memestock board: US market session state, the community ticker rows and the equities they track. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumMarketResponse`.
        """
        return await self._send(_get_forum_market(), timeout=timeout)

    async def list_forum_posts(
        self,
        *,
        community: str | None = None,
        sort: PostSortParam = "hot",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ListForumPostsResponse:
        """The memestock forum feed, optionally narrowed to one token community. Costs 2 credits.

        Args:
            community: Restrict the feed to one community slug.
            sort: Feed ranking.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.ListForumPostsResponse`.
        """
        return await self._send(_list_forum_posts(community=community, sort=sort), timeout=timeout)

    async def get_forum_post(
        self,
        post_id: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumPostResponse:
        """One forum post with its vote counts and community metadata. Costs 2 credits.

        Args:
            post_id: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumPostResponse`.
        """
        return await self._send(_get_forum_post(post_id), timeout=timeout)

    async def get_forum_post_comments(
        self,
        post_id: str,
        *,
        sort: PostSortParam = "hot",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumPostCommentsResponse:
        """The comment thread under a forum post. Costs 2 credits.

        Args:
            post_id: See the API reference.
            sort: Comment ranking.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumPostCommentsResponse`.
        """
        return await self._send(_get_forum_post_comments(post_id, sort=sort), timeout=timeout)

    async def list_launches(
        self,
        *,
        age: LaunchAgeParam = "all",
        graduated_page: int = 1,
        graduated_page_size: int = 10,
        include_graduated: bool = True,
        page: int = 1,
        page_size: int = 50,
        sort: LaunchSortParam = "recentBuys",
        version: LaunchVersionParam = "all",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ListLaunchesResponse:
        """The pons launchpad explore board: tokens still climbing the bonding curve plus a page of graduated tokens. Costs 2 credits.

        Args:
            age: Only include launches from this window.
            graduated_page: Page of graduated launches.
            graduated_page_size: Graduated launches per page.
            include_graduated: Include the graduated board in the response.
            page: Page of active launches.
            page_size: Active launches per page.
            sort: Ranking column for the active board.
            version: Restrict to a launchpad version.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.ListLaunchesResponse`.
        """
        return await self._send(
            _list_launches(
                age=age,
                graduated_page=graduated_page,
                graduated_page_size=graduated_page_size,
                include_graduated=include_graduated,
                page=page,
                page_size=page_size,
                sort=sort,
                version=version,
            ),
            timeout=timeout,
        )

    async def list_graduated_catalog(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> list[Launch]:
        """The graduated tokens as full launch records, the catalog view of the graduations feed. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A list of :class:`~tapline.ponsfamily.Launch`.
        """
        return await self._send(_list_graduated_catalog(), timeout=timeout)

    async def list_graduations(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> list[Graduation]:
        """Every graduation event pons has observed, as token address and graduation block. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A list of :class:`~tapline.ponsfamily.Graduation`.
        """
        return await self._send(_list_graduations(), timeout=timeout)

    async def list_live_markets(
        self,
        *,
        markets: Sequence[str] | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> list[LiveMarket]:
        """Live price and graduation-progress snapshot for the launches currently trading. Costs 2 credits.

        Args:
            markets: Restrict the live-market snapshot to these token addresses, at
                most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A list of :class:`~tapline.ponsfamily.LiveMarket`.
        """
        return await self._send(_list_live_markets(markets=markets), timeout=timeout)

    async def search_launches(
        self,
        *,
        age: LaunchAgeParam = "all",
        page: int = 1,
        q: str = "",
        sort: LaunchSearchSortParam = "relevance",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> SearchLaunchesResponse:
        """Search every pons launch by name, symbol or contract address. Costs 2 credits.

        Args:
            age: Only include launches from this window.
            page: Result page.
            q: Free-text query matched against token name, symbol and address.
            sort: Ranking column for the result set.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.SearchLaunchesResponse`.
        """
        return await self._send(
            _search_launches(age=age, page=page, q=q, sort=sort), timeout=timeout
        )

    async def get_market(
        self,
        token: str,
        *,
        include_holders: bool = False,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketResponse:
        """Price, market cap, liquidity, recent trades and price points for one v1 token. Costs 2 credits.

        Args:
            token: See the API reference.
            include_holders: Include the holder list in the snapshot.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketResponse`.
        """
        return await self._send(
            _get_market(token, include_holders=include_holders), timeout=timeout
        )

    async def get_market_ath(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketAthResponse:
        """All-time-high price for a token and the block it was set in. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketAthResponse`.
        """
        return await self._send(_get_market_ath(token), timeout=timeout)

    async def get_market_burned(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketBurnedResponse:
        """Supply burned for a token, in wei. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketBurnedResponse`.
        """
        return await self._send(_get_market_burned(token), timeout=timeout)

    async def get_market_chart(
        self,
        token: str,
        *,
        range: ChartRangeParam = "1h",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketChartResponse:
        """Bucketed price and volume points for a token, at the resolution the range implies. Costs 2 credits.

        Args:
            token: See the API reference.
            range: Chart window.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketChartResponse`.
        """
        return await self._send(_get_market_chart(token, range=range), timeout=timeout)

    async def get_developer_trades(
        self,
        token: str,
        *,
        deployer: str,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetDeveloperTradesResponse:
        """What the deployer did with its own allocation: buys, sells, transfers, burns, and the dumped/moved/burned verdicts. Costs 2 credits.

        Args:
            token: See the API reference.
            deployer: Deployer wallet that launched the token.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetDeveloperTradesResponse`.
        """
        return await self._send(_get_developer_trades(token, deployer=deployer), timeout=timeout)

    async def get_market_holders(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketHoldersResponse:
        """Ranked token holders with balance, supply share and per-holder PnL where pons can compute it. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketHoldersResponse`.
        """
        return await self._send(_get_market_holders(token), timeout=timeout)

    async def get_market_order_depth(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketOrderDepthResponse:
        """Resting limit-order depth around the current price, bucketed into price bands. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketOrderDepthResponse`.
        """
        return await self._send(_get_market_order_depth(token), timeout=timeout)

    async def get_market_tip(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketTipResponse:
        """The latest observed pool price, the cheap poll the launchpad UI uses. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketTipResponse`.
        """
        return await self._send(_get_market_tip(token), timeout=timeout)

    async def get_market_trades(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> list[MarketTrade]:
        """The most recent buys and sells against a token's pool. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A list of :class:`~tapline.ponsfamily.MarketTrade`.
        """
        return await self._send(_get_market_trades(token), timeout=timeout)

    async def get_creator_holdings(
        self,
        *,
        pairs: Sequence[CreatorHoldingPair],
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetCreatorHoldingsResponse:
        """The share of supply each deployer still holds of the token it launched. Costs 2 credits.

        Args:
            pairs: Token/deployer pairs to resolve, at most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetCreatorHoldingsResponse`.
        """
        return await self._send(_get_creator_holdings(pairs=pairs), timeout=timeout)

    async def get_fee_sharing(
        self,
        *,
        tokens: Sequence[str],
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetFeeSharingResponse:
        """Whether each token routes its creator fees to holders. Costs 2 credits.

        Args:
            tokens: Token contract addresses to resolve, at most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetFeeSharingResponse`.
        """
        return await self._send(_get_fee_sharing(tokens=tokens), timeout=timeout)

    async def get_token_images(
        self,
        *,
        tokens: Sequence[str],
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetTokenImagesResponse:
        """Resolved logo URLs keyed by lower-cased token address. Costs 2 credits.

        Args:
            tokens: Token contract addresses to resolve, at most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetTokenImagesResponse`.
        """
        return await self._send(_get_token_images(tokens=tokens), timeout=timeout)

    async def get_token(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetTokenResponse:
        """Static token metadata: supply, socials, pool wiring and the deployer that launched it. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetTokenResponse`.
        """
        return await self._send(_get_token(token), timeout=timeout)

    async def get_v2_market_chart(
        self,
        token: str,
        *,
        range: ChartRangeParam = "1h",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2MarketChartResponse:
        """Bucketed price and volume points for a v2 launch, with the quote asset's USD rate. Costs 2 credits.

        Args:
            token: See the API reference.
            range: Chart window.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2MarketChartResponse`.
        """
        return await self._send(_get_v2_market_chart(token, range=range), timeout=timeout)

    async def get_v2_creator_fees(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2CreatorFeesResponse:
        """Creator-fee escrow for a v2 launch: recipient, quote asset and what has been earned so far. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2CreatorFeesResponse`.
        """
        return await self._send(_get_v2_creator_fees(token), timeout=timeout)

    async def get_v2_distributor(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2DistributorResponse:
        """Holder fee-sharing distributor state for a v2 launch, including the latest payout epoch. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2DistributorResponse`.
        """
        return await self._send(_get_v2_distributor(token), timeout=timeout)

    async def get_v2_market_holders(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2MarketHoldersResponse:
        """Ranked holders of a v2 launch. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2MarketHoldersResponse`.
        """
        return await self._send(_get_v2_market_holders(token), timeout=timeout)

    async def get_v2_market_trades(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2MarketTradesResponse:
        """Trades against a v2 (curve) launch, quoted in the launch's own quote asset. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2MarketTradesResponse`.
        """
        return await self._send(_get_v2_market_trades(token), timeout=timeout)

    async def get_wallet_identities(
        self,
        *,
        addresses: Sequence[str],
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetWalletIdentitiesResponse:
        """Public pons profiles (username, avatar, bio) for the given wallets. Costs 2 credits.

        Args:
            addresses: Wallet addresses to resolve, at most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetWalletIdentitiesResponse`.
        """
        return await self._send(_get_wallet_identities(addresses=addresses), timeout=timeout)

    async def get_portfolio_chart(
        self,
        address: str,
        *,
        range: PortfolioRangeParam = "1d",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetPortfolioChartResponse:
        """Portfolio value over time for a wallet, with the change over the requested window. Costs 2 credits.

        Args:
            address: See the API reference.
            range: Chart window.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetPortfolioChartResponse`.
        """
        return await self._send(_get_portfolio_chart(address, range=range), timeout=timeout)

    async def get_wallet_positions(
        self,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetWalletPositionsResponse:
        """A wallet's open and closed positions, its trade activity, and realized/unrealized PnL totals. Costs 2 credits.

        Args:
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetWalletPositionsResponse`.
        """
        return await self._send(_get_wallet_positions(address), timeout=timeout)

    async def get_profile(
        self,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetProfileResponse:
        """The launches a wallet deployed or earns fees from, with its claimed and claimable fees on each, alongside the ETH/USD rate pons priced them with. Costs 2 credits.

        Args:
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetProfileResponse`.
        """
        return await self._send(_get_profile(address), timeout=timeout)


class SyncPonsfamily(SyncAPIResource):
    """The Ponsfamily endpoints, blocking.

    Reached as :attr:`~tapline.SyncTaplineClient.ponsfamily`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    def get_analytics(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetAnalyticsResponse:
        """Protocol-wide launch, volume, trade and revenue totals plus the daily series behind them. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetAnalyticsResponse`.
        """
        return self._send(_get_analytics(), timeout=timeout)

    def list_cto_migrations(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ListCtoMigrationsResponse:
        """Community-takeover migrations: the old and new token, the deposit/claim schedule and how much has been migrated. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.ListCtoMigrationsResponse`.
        """
        return self._send(_list_cto_migrations(), timeout=timeout)

    def get_eth_price(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetEthPriceResponse:
        """The ETH/USD rate pons prices every launch with. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetEthPriceResponse`.
        """
        return self._send(_get_eth_price(), timeout=timeout)

    def list_forum_communities(
        self,
        *,
        limit: int = 10,
        rank: CommunityRankParam = "marketCap",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ListForumCommunitiesResponse:
        """Token communities ranked by market cap, burn share or real market cap. Costs 2 credits.

        Args:
            limit: Number of communities to return.
            rank: Ranking column.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.ListForumCommunitiesResponse`.
        """
        return self._send(_list_forum_communities(limit=limit, rank=rank), timeout=timeout)

    def get_forum_community(
        self,
        slug: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumCommunityResponse:
        """One token community with its supply, burn and market-cap figures. Costs 2 credits.

        Args:
            slug: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumCommunityResponse`.
        """
        return self._send(_get_forum_community(slug), timeout=timeout)

    def get_forum_holding(
        self,
        token: str,
        wallet: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumHoldingResponse:
        """A wallet's balance in a community token and the posting tier that balance earns it. Costs 2 credits.

        Args:
            token: See the API reference.
            wallet: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumHoldingResponse`.
        """
        return self._send(_get_forum_holding(token, wallet), timeout=timeout)

    def get_forum_market(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumMarketResponse:
        """The memestock board: US market session state, the community ticker rows and the equities they track. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumMarketResponse`.
        """
        return self._send(_get_forum_market(), timeout=timeout)

    def list_forum_posts(
        self,
        *,
        community: str | None = None,
        sort: PostSortParam = "hot",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ListForumPostsResponse:
        """The memestock forum feed, optionally narrowed to one token community. Costs 2 credits.

        Args:
            community: Restrict the feed to one community slug.
            sort: Feed ranking.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.ListForumPostsResponse`.
        """
        return self._send(_list_forum_posts(community=community, sort=sort), timeout=timeout)

    def get_forum_post(
        self,
        post_id: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumPostResponse:
        """One forum post with its vote counts and community metadata. Costs 2 credits.

        Args:
            post_id: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumPostResponse`.
        """
        return self._send(_get_forum_post(post_id), timeout=timeout)

    def get_forum_post_comments(
        self,
        post_id: str,
        *,
        sort: PostSortParam = "hot",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetForumPostCommentsResponse:
        """The comment thread under a forum post. Costs 2 credits.

        Args:
            post_id: See the API reference.
            sort: Comment ranking.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetForumPostCommentsResponse`.
        """
        return self._send(_get_forum_post_comments(post_id, sort=sort), timeout=timeout)

    def list_launches(
        self,
        *,
        age: LaunchAgeParam = "all",
        graduated_page: int = 1,
        graduated_page_size: int = 10,
        include_graduated: bool = True,
        page: int = 1,
        page_size: int = 50,
        sort: LaunchSortParam = "recentBuys",
        version: LaunchVersionParam = "all",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> ListLaunchesResponse:
        """The pons launchpad explore board: tokens still climbing the bonding curve plus a page of graduated tokens. Costs 2 credits.

        Args:
            age: Only include launches from this window.
            graduated_page: Page of graduated launches.
            graduated_page_size: Graduated launches per page.
            include_graduated: Include the graduated board in the response.
            page: Page of active launches.
            page_size: Active launches per page.
            sort: Ranking column for the active board.
            version: Restrict to a launchpad version.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.ListLaunchesResponse`.
        """
        return self._send(
            _list_launches(
                age=age,
                graduated_page=graduated_page,
                graduated_page_size=graduated_page_size,
                include_graduated=include_graduated,
                page=page,
                page_size=page_size,
                sort=sort,
                version=version,
            ),
            timeout=timeout,
        )

    def list_graduated_catalog(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> list[Launch]:
        """The graduated tokens as full launch records, the catalog view of the graduations feed. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A list of :class:`~tapline.ponsfamily.Launch`.
        """
        return self._send(_list_graduated_catalog(), timeout=timeout)

    def list_graduations(
        self,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> list[Graduation]:
        """Every graduation event pons has observed, as token address and graduation block. Costs 2 credits.

        Args:
            timeout: Overrides the client's timeout for this request.

        Returns:
            A list of :class:`~tapline.ponsfamily.Graduation`.
        """
        return self._send(_list_graduations(), timeout=timeout)

    def list_live_markets(
        self,
        *,
        markets: Sequence[str] | None = None,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> list[LiveMarket]:
        """Live price and graduation-progress snapshot for the launches currently trading. Costs 2 credits.

        Args:
            markets: Restrict the live-market snapshot to these token addresses, at
                most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A list of :class:`~tapline.ponsfamily.LiveMarket`.
        """
        return self._send(_list_live_markets(markets=markets), timeout=timeout)

    def search_launches(
        self,
        *,
        age: LaunchAgeParam = "all",
        page: int = 1,
        q: str = "",
        sort: LaunchSearchSortParam = "relevance",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> SearchLaunchesResponse:
        """Search every pons launch by name, symbol or contract address. Costs 2 credits.

        Args:
            age: Only include launches from this window.
            page: Result page.
            q: Free-text query matched against token name, symbol and address.
            sort: Ranking column for the result set.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.SearchLaunchesResponse`.
        """
        return self._send(_search_launches(age=age, page=page, q=q, sort=sort), timeout=timeout)

    def get_market(
        self,
        token: str,
        *,
        include_holders: bool = False,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketResponse:
        """Price, market cap, liquidity, recent trades and price points for one v1 token. Costs 2 credits.

        Args:
            token: See the API reference.
            include_holders: Include the holder list in the snapshot.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketResponse`.
        """
        return self._send(_get_market(token, include_holders=include_holders), timeout=timeout)

    def get_market_ath(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketAthResponse:
        """All-time-high price for a token and the block it was set in. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketAthResponse`.
        """
        return self._send(_get_market_ath(token), timeout=timeout)

    def get_market_burned(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketBurnedResponse:
        """Supply burned for a token, in wei. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketBurnedResponse`.
        """
        return self._send(_get_market_burned(token), timeout=timeout)

    def get_market_chart(
        self,
        token: str,
        *,
        range: ChartRangeParam = "1h",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketChartResponse:
        """Bucketed price and volume points for a token, at the resolution the range implies. Costs 2 credits.

        Args:
            token: See the API reference.
            range: Chart window.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketChartResponse`.
        """
        return self._send(_get_market_chart(token, range=range), timeout=timeout)

    def get_developer_trades(
        self,
        token: str,
        *,
        deployer: str,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetDeveloperTradesResponse:
        """What the deployer did with its own allocation: buys, sells, transfers, burns, and the dumped/moved/burned verdicts. Costs 2 credits.

        Args:
            token: See the API reference.
            deployer: Deployer wallet that launched the token.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetDeveloperTradesResponse`.
        """
        return self._send(_get_developer_trades(token, deployer=deployer), timeout=timeout)

    def get_market_holders(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketHoldersResponse:
        """Ranked token holders with balance, supply share and per-holder PnL where pons can compute it. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketHoldersResponse`.
        """
        return self._send(_get_market_holders(token), timeout=timeout)

    def get_market_order_depth(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketOrderDepthResponse:
        """Resting limit-order depth around the current price, bucketed into price bands. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketOrderDepthResponse`.
        """
        return self._send(_get_market_order_depth(token), timeout=timeout)

    def get_market_tip(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetMarketTipResponse:
        """The latest observed pool price, the cheap poll the launchpad UI uses. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetMarketTipResponse`.
        """
        return self._send(_get_market_tip(token), timeout=timeout)

    def get_market_trades(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> list[MarketTrade]:
        """The most recent buys and sells against a token's pool. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A list of :class:`~tapline.ponsfamily.MarketTrade`.
        """
        return self._send(_get_market_trades(token), timeout=timeout)

    def get_creator_holdings(
        self,
        *,
        pairs: Sequence[CreatorHoldingPair],
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetCreatorHoldingsResponse:
        """The share of supply each deployer still holds of the token it launched. Costs 2 credits.

        Args:
            pairs: Token/deployer pairs to resolve, at most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetCreatorHoldingsResponse`.
        """
        return self._send(_get_creator_holdings(pairs=pairs), timeout=timeout)

    def get_fee_sharing(
        self,
        *,
        tokens: Sequence[str],
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetFeeSharingResponse:
        """Whether each token routes its creator fees to holders. Costs 2 credits.

        Args:
            tokens: Token contract addresses to resolve, at most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetFeeSharingResponse`.
        """
        return self._send(_get_fee_sharing(tokens=tokens), timeout=timeout)

    def get_token_images(
        self,
        *,
        tokens: Sequence[str],
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetTokenImagesResponse:
        """Resolved logo URLs keyed by lower-cased token address. Costs 2 credits.

        Args:
            tokens: Token contract addresses to resolve, at most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetTokenImagesResponse`.
        """
        return self._send(_get_token_images(tokens=tokens), timeout=timeout)

    def get_token(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetTokenResponse:
        """Static token metadata: supply, socials, pool wiring and the deployer that launched it. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetTokenResponse`.
        """
        return self._send(_get_token(token), timeout=timeout)

    def get_v2_market_chart(
        self,
        token: str,
        *,
        range: ChartRangeParam = "1h",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2MarketChartResponse:
        """Bucketed price and volume points for a v2 launch, with the quote asset's USD rate. Costs 2 credits.

        Args:
            token: See the API reference.
            range: Chart window.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2MarketChartResponse`.
        """
        return self._send(_get_v2_market_chart(token, range=range), timeout=timeout)

    def get_v2_creator_fees(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2CreatorFeesResponse:
        """Creator-fee escrow for a v2 launch: recipient, quote asset and what has been earned so far. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2CreatorFeesResponse`.
        """
        return self._send(_get_v2_creator_fees(token), timeout=timeout)

    def get_v2_distributor(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2DistributorResponse:
        """Holder fee-sharing distributor state for a v2 launch, including the latest payout epoch. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2DistributorResponse`.
        """
        return self._send(_get_v2_distributor(token), timeout=timeout)

    def get_v2_market_holders(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2MarketHoldersResponse:
        """Ranked holders of a v2 launch. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2MarketHoldersResponse`.
        """
        return self._send(_get_v2_market_holders(token), timeout=timeout)

    def get_v2_market_trades(
        self,
        token: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetV2MarketTradesResponse:
        """Trades against a v2 (curve) launch, quoted in the launch's own quote asset. Costs 2 credits.

        Args:
            token: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetV2MarketTradesResponse`.
        """
        return self._send(_get_v2_market_trades(token), timeout=timeout)

    def get_wallet_identities(
        self,
        *,
        addresses: Sequence[str],
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetWalletIdentitiesResponse:
        """Public pons profiles (username, avatar, bio) for the given wallets. Costs 2 credits.

        Args:
            addresses: Wallet addresses to resolve, at most 100 per call.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetWalletIdentitiesResponse`.
        """
        return self._send(_get_wallet_identities(addresses=addresses), timeout=timeout)

    def get_portfolio_chart(
        self,
        address: str,
        *,
        range: PortfolioRangeParam = "1d",
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetPortfolioChartResponse:
        """Portfolio value over time for a wallet, with the change over the requested window. Costs 2 credits.

        Args:
            address: See the API reference.
            range: Chart window.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetPortfolioChartResponse`.
        """
        return self._send(_get_portfolio_chart(address, range=range), timeout=timeout)

    def get_wallet_positions(
        self,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetWalletPositionsResponse:
        """A wallet's open and closed positions, its trade activity, and realized/unrealized PnL totals. Costs 2 credits.

        Args:
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetWalletPositionsResponse`.
        """
        return self._send(_get_wallet_positions(address), timeout=timeout)

    def get_profile(
        self,
        address: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> GetProfileResponse:
        """The launches a wallet deployed or earns fees from, with its claimed and claimable fees on each, alongside the ETH/USD rate pons priced them with. Costs 2 credits.

        Args:
            address: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.ponsfamily.GetProfileResponse`.
        """
        return self._send(_get_profile(address), timeout=timeout)
