# Generated by generate-client from spec/openapi.json. Do not edit.
# ruff: noqa: E501
"""The 4 Twitter endpoints, in awaitable and blocking form.

Each endpoint's request is built once, by the private functions below. Both
resources call the same builder, so the twins differ only in ``await``.
"""

from __future__ import annotations

from collections.abc import Mapping

from .._base_client import encode_path
from .._resource import AsyncAPIResource, Request, SyncAPIResource
from .._types import Body, NotGiven, Timeout, not_given
from ..twitter import (
    TwitterCommunityResponse,
    TwitterProfileResponse,
    TwitterTweetDetailResponse,
)

__all__ = ["SyncTwitter", "Twitter"]

_PREFIX = "/api/v1/twitter"


def _body(fields: Mapping[str, object]) -> Body:
    """A JSON body with every omitted argument left out, so the server applies its default."""
    return {name: value for name, value in fields.items() if value is not None}


def _get_community(community_id: str) -> Request[TwitterCommunityResponse]:
    return Request(
        encode_path(_PREFIX + "/communities/{community_id}", community_id=community_id),
        TwitterCommunityResponse,
    )


def _get_tweet(tweet_id: str) -> Request[TwitterTweetDetailResponse]:
    return Request(
        encode_path(_PREFIX + "/tweets/{tweet_id}", tweet_id=tweet_id), TwitterTweetDetailResponse
    )


def _get_user_profile_by_id(user_id: str) -> Request[TwitterProfileResponse]:
    return Request(
        encode_path(_PREFIX + "/users/by-id/{user_id}", user_id=user_id), TwitterProfileResponse
    )


def _get_user_profile(screen_name: str) -> Request[TwitterProfileResponse]:
    return Request(
        encode_path(_PREFIX + "/users/{screen_name}", screen_name=screen_name),
        TwitterProfileResponse,
    )


class Twitter(AsyncAPIResource):
    """The Twitter endpoints, awaitable.

    Reached as :attr:`~tapline.TaplineClient.twitter`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    async def get_community(
        self,
        community_id: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> TwitterCommunityResponse:
        """An X (Twitter) Community as x.com shows it to logged-out visitors: id, name, description, member count, created time, join policy, topic, banner, rules and creator, plus the 20 community posts x.com ranks by likes. This is a fixed window: x.com offers no latest feed and no further pages logged-out. Costs 2 credits.

        Args:
            community_id: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.twitter.TwitterCommunityResponse`.
        """
        return await self._send(_get_community(community_id), timeout=timeout)

    async def get_tweet(
        self,
        tweet_id: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> TwitterTweetDetailResponse:
        """One X (Twitter) post as x.com shows it to logged-out visitors: full text (long posts included), every t.co link in it mapped to its expanded URL in `urls` (the media link maps to the media page; the text itself keeps the t.co links), created time, likes, replies, reposts, quotes, bookmarks, views when X shows them, media with video variants and bitrates, the article an article post links to, and the quoted post. `parent_tweets` holds the posts above a reply that x.com shows logged-out, oldest first; in samples that is only the post it replies to, so follow `in_reply_to_tweet_id` to walk further up. `replies` holds the top replies x.com shows logged-out (0 to 4 in samples, not every reply); x.com offers no further reply pages logged-out. Each `author` holds only the fields x.com embeds with posts: bio, join date, bio link, location and banner can be null there, so use the profile route for those. Costs 1 credit.

        Args:
            tweet_id: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.twitter.TwitterTweetDetailResponse`.
        """
        return await self._send(_get_tweet(tweet_id), timeout=timeout)

    async def get_user_profile_by_id(
        self,
        user_id: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> TwitterProfileResponse:
        """An X (Twitter) account's public profile as x.com shows it to logged-out visitors: id, handle, name, bio with its links and mentions, bio link, location, avatar, banner, join date, follower, following and post counts, blue check and protected flag. It also carries the pinned post and the newest original posts x.com shows logged-out (4 or 5 in samples), from the same page fetch. This is a fixed window: x.com offers no further pages logged-out, so there is no cursor. A protected account returns its profile with no posts. Each post's `author` holds only the fields x.com embeds with posts: bio, join date, bio link, location and banner can be null there even when the profile has them. Looks the account up by its numeric user id. Costs 1 credit.

        Args:
            user_id: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.twitter.TwitterProfileResponse`.
        """
        return await self._send(_get_user_profile_by_id(user_id), timeout=timeout)

    async def get_user_profile(
        self,
        screen_name: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> TwitterProfileResponse:
        """An X (Twitter) account's public profile as x.com shows it to logged-out visitors: id, handle, name, bio with its links and mentions, bio link, location, avatar, banner, join date, follower, following and post counts, blue check and protected flag. It also carries the pinned post and the newest original posts x.com shows logged-out (4 or 5 in samples), from the same page fetch. This is a fixed window: x.com offers no further pages logged-out, so there is no cursor. A protected account returns its profile with no posts. Each post's `author` holds only the fields x.com embeds with posts: bio, join date, bio link, location and banner can be null there even when the profile has them. Looks the account up by its handle. Costs 1 credit.

        Args:
            screen_name: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.twitter.TwitterProfileResponse`.
        """
        return await self._send(_get_user_profile(screen_name), timeout=timeout)


class SyncTwitter(SyncAPIResource):
    """The Twitter endpoints, blocking.

    Reached as :attr:`~tapline.SyncTaplineClient.twitter`. Anywhere a method takes an
    enum it also takes that enum's value as a plain string.

    Every method raises ``AuthenticationError`` when the API key is rejected,
    ``InsufficientCreditsError`` when the account cannot pay for the call,
    ``RateLimitError`` once automatic retries are exhausted, and
    ``InternalServerError`` when Tapline or the upstream site fails.
    """

    def get_community(
        self,
        community_id: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> TwitterCommunityResponse:
        """An X (Twitter) Community as x.com shows it to logged-out visitors: id, name, description, member count, created time, join policy, topic, banner, rules and creator, plus the 20 community posts x.com ranks by likes. This is a fixed window: x.com offers no latest feed and no further pages logged-out. Costs 2 credits.

        Args:
            community_id: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.twitter.TwitterCommunityResponse`.
        """
        return self._send(_get_community(community_id), timeout=timeout)

    def get_tweet(
        self,
        tweet_id: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> TwitterTweetDetailResponse:
        """One X (Twitter) post as x.com shows it to logged-out visitors: full text (long posts included), every t.co link in it mapped to its expanded URL in `urls` (the media link maps to the media page; the text itself keeps the t.co links), created time, likes, replies, reposts, quotes, bookmarks, views when X shows them, media with video variants and bitrates, the article an article post links to, and the quoted post. `parent_tweets` holds the posts above a reply that x.com shows logged-out, oldest first; in samples that is only the post it replies to, so follow `in_reply_to_tweet_id` to walk further up. `replies` holds the top replies x.com shows logged-out (0 to 4 in samples, not every reply); x.com offers no further reply pages logged-out. Each `author` holds only the fields x.com embeds with posts: bio, join date, bio link, location and banner can be null there, so use the profile route for those. Costs 1 credit.

        Args:
            tweet_id: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.twitter.TwitterTweetDetailResponse`.
        """
        return self._send(_get_tweet(tweet_id), timeout=timeout)

    def get_user_profile_by_id(
        self,
        user_id: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> TwitterProfileResponse:
        """An X (Twitter) account's public profile as x.com shows it to logged-out visitors: id, handle, name, bio with its links and mentions, bio link, location, avatar, banner, join date, follower, following and post counts, blue check and protected flag. It also carries the pinned post and the newest original posts x.com shows logged-out (4 or 5 in samples), from the same page fetch. This is a fixed window: x.com offers no further pages logged-out, so there is no cursor. A protected account returns its profile with no posts. Each post's `author` holds only the fields x.com embeds with posts: bio, join date, bio link, location and banner can be null there even when the profile has them. Looks the account up by its numeric user id. Costs 1 credit.

        Args:
            user_id: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.twitter.TwitterProfileResponse`.
        """
        return self._send(_get_user_profile_by_id(user_id), timeout=timeout)

    def get_user_profile(
        self,
        screen_name: str,
        *,
        timeout: float | Timeout | NotGiven | None = not_given,
    ) -> TwitterProfileResponse:
        """An X (Twitter) account's public profile as x.com shows it to logged-out visitors: id, handle, name, bio with its links and mentions, bio link, location, avatar, banner, join date, follower, following and post counts, blue check and protected flag. It also carries the pinned post and the newest original posts x.com shows logged-out (4 or 5 in samples), from the same page fetch. This is a fixed window: x.com offers no further pages logged-out, so there is no cursor. A protected account returns its profile with no posts. Each post's `author` holds only the fields x.com embeds with posts: bio, join date, bio link, location and banner can be null there even when the profile has them. Looks the account up by its handle. Costs 1 credit.

        Args:
            screen_name: See the API reference.
            timeout: Overrides the client's timeout for this request.

        Returns:
            A :class:`~tapline.twitter.TwitterProfileResponse`.
        """
        return self._send(_get_user_profile(screen_name), timeout=timeout)
