# Generated by generate-client from spec/openapi.json. Do not edit.
"""Every captured twitter payload, validated as the response type its method declares.

A payload that parses with nothing in ``model_extra`` and survives a round trip
proves the response types still describe what the API sends.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import pydantic
import pytest

from conftest import extras
from tapline.twitter import (
    TwitterCommunityResponse,
    TwitterProfileResponse,
    TwitterTweetDetailResponse,
)

FIXTURES = (
    Path(
        os.environ.get("GENERATE_CLIENT_FIXTURES")
        or Path(__file__).resolve().parents[2] / "fixtures"
    )
    / "twitter"
)


def cases(negative: bool) -> list[str]:
    """Fixture stems on disk, positive or negative, in a stable order."""
    stems = sorted(
        p.name[: -len(".request.json")]
        for p in FIXTURES.glob("*.request.json")
        if (".neg." in p.name) is negative
    )
    return stems


RESPONSES: dict[str, type[Any]] = {
    "get_community": TwitterCommunityResponse,
    "get_tweet": TwitterTweetDetailResponse,
    "get_user_profile_by_id": TwitterProfileResponse,
    "get_user_profile": TwitterProfileResponse,
}
METHODS = ["get_community", "get_tweet", "get_user_profile_by_id", "get_user_profile"]


def test_every_method_has_a_default_fixture() -> None:
    missing = [m for m in METHODS if not (FIXTURES / f"{m}.default.json").exists()]

    assert missing == [], f"run the generate-client capture step for {missing}"


@pytest.mark.parametrize("stem", cases(negative=False))
def test_a_captured_payload_parses_and_declares_every_field(stem: str) -> None:
    payload = json.loads((FIXTURES / f"{stem}.json").read_text())
    method = stem.split(".", 1)[0]
    adapter: pydantic.TypeAdapter[Any] = pydantic.TypeAdapter(RESPONSES[method])
    parsed = adapter.validate_python(payload)

    assert extras(parsed, method) == []
    assert adapter.dump_python(parsed, mode="json", exclude_unset=True, by_alias=True) == payload
