# Generated by generate-client from spec/openapi.json. Do not edit.
"""Every captured gmgn payload, replayed through the model that has to hold it.

A payload that parses with nothing in ``model_extra`` and survives a round trip
proves the model still describes what the API sends.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from conftest import extras
from tapline import BaseModel
from tapline.gmgn import (
    GetActivityRankInfoResponse,
    GetAggedTokenTradesResponse,
    GetAggedTokenTransfersResponse,
    GetBluechipRankResponse,
    GetDevCreatedTokensResponse,
    GetDexTradesPollingResponse,
    GetGasPriceListResponse,
    GetHotSearchesResponse,
    GetLaunchpadTaxPolicyResponse,
    GetLiveTokenPreviewResponse,
    GetLiveTwitchKolResponse,
    GetMajorCoinPricesResponse,
    GetMultiTokenFullInfoResponse,
    GetMultiTokenInfoResponse,
    GetMultiWindowTokenInfoResponse,
    GetNativeTransferResponse,
    GetNewPairsResponse,
    GetRecommendSlippageResponse,
    GetSimilarCoinExtremesResponse,
    GetSimilarCoinsResponse,
    GetSmartMoneyWalletInfoResponse,
    GetSmartMoneyWalletResponse,
    GetSwapRankingsResponse,
    GetTokenAiNarrativeResponse,
    GetTokenBundlerStatResponse,
    GetTokenCandlesResponse,
    GetTokenCommunityMessagesResponse,
    GetTokenDevInfoResponse,
    GetTokenFeeDistributionResponse,
    GetTokenFeeInfoResponse,
    GetTokenHolderExtraInfoResponse,
    GetTokenHoldersResponse,
    GetTokenHolderStatResponse,
    GetTokenInfoBriefResponse,
    GetTokenLiquidityResponse,
    GetTokenLiquidityStatsResponse,
    GetTokenLiquidityTrendResponse,
    GetTokenLogoHistoryResponse,
    GetTokenMcapCandlesResponse,
    GetTokenPoolFeeInfoResponse,
    GetTokenPricesResponse,
    GetTokenSecurityResponse,
    GetTokenSignalsResponse,
    GetTokenSocialsResponse,
    GetTokenStatsResponse,
    GetTokenTradersResponse,
    GetTokenTraderStatResponse,
    GetTokenTradesResponse,
    GetTokenTradesV2Response,
    GetTokenTrendsResponse,
    GetTokenWalletTagsStatResponse,
    GetTopBuyersResponse,
    GetTopCallersResponse,
    GetTrendingTokensResponse,
    GetWalletActivityResponse,
    GetWalletChainBalancesResponse,
    GetWalletCommonStatResponse,
    GetWalletRankingsResponse,
    GetWalletStatResponse,
    GetWebsiteInfoResponse,
    SearchTokensResponse,
)

FIXTURES = (
    Path(
        os.environ.get("GENERATE_CLIENT_FIXTURES")
        or Path(__file__).resolve().parents[2] / "fixtures"
    )
    / "gmgn"
)


def cases(negative: bool) -> list[str]:
    """Fixture stems on disk, positive or negative, in a stable order."""
    stems = sorted(
        p.name[: -len(".request.json")]
        for p in FIXTURES.glob("*.request.json")
        if (".neg." in p.name) is negative
    )
    return stems


MODELS: dict[str, type[BaseModel]] = {
    "gas_price_list": GetGasPriceListResponse,
    "hot_searches": GetHotSearchesResponse,
    "live_twitch_kol": GetLiveTwitchKolResponse,
    "major_coin_prices": GetMajorCoinPricesResponse,
    "trending_tokens": GetTrendingTokensResponse,
    "activity_rank_info": GetActivityRankInfoResponse,
    "agged_token_transfers": GetAggedTokenTransfersResponse,
    "bluechip_rank": GetBluechipRankResponse,
    "dev_created_tokens": GetDevCreatedTokensResponse,
    "dex_trades_polling": GetDexTradesPollingResponse,
    "launchpad_tax_policy": GetLaunchpadTaxPolicyResponse,
    "multi_token_full_info": GetMultiTokenFullInfoResponse,
    "multi_token_info": GetMultiTokenInfoResponse,
    "multi_window_token_info": GetMultiWindowTokenInfoResponse,
    "native_transfer": GetNativeTransferResponse,
    "new_pairs": GetNewPairsResponse,
    "search": SearchTokensResponse,
    "similar_coin_extremes": GetSimilarCoinExtremesResponse,
    "similar_coins": GetSimilarCoinsResponse,
    "smart_money_wallet_info": GetSmartMoneyWalletInfoResponse,
    "swap_rankings": GetSwapRankingsResponse,
    "token_info_brief": GetTokenInfoBriefResponse,
    "token_prices": GetTokenPricesResponse,
    "token_signals": GetTokenSignalsResponse,
    "agged_token_trades": GetAggedTokenTradesResponse,
    "token_ai_narrative": GetTokenAiNarrativeResponse,
    "token_bundler_stat": GetTokenBundlerStatResponse,
    "token_candles": GetTokenCandlesResponse,
    "token_community_messages": GetTokenCommunityMessagesResponse,
    "token_dev_info": GetTokenDevInfoResponse,
    "token_fee_distribution": GetTokenFeeDistributionResponse,
    "token_fee_info": GetTokenFeeInfoResponse,
    "token_holder_extra_info": GetTokenHolderExtraInfoResponse,
    "holder_stat": GetTokenHolderStatResponse,
    "holders": GetTokenHoldersResponse,
    "liquidity": GetTokenLiquidityResponse,
    "token_liquidity_stats": GetTokenLiquidityStatsResponse,
    "token_liquidity_trend": GetTokenLiquidityTrendResponse,
    "live_preview": GetLiveTokenPreviewResponse,
    "token_logo_history": GetTokenLogoHistoryResponse,
    "mcap_candles": GetTokenMcapCandlesResponse,
    "pool_fee_info": GetTokenPoolFeeInfoResponse,
    "recommend_slippage": GetRecommendSlippageResponse,
    "security": GetTokenSecurityResponse,
    "socials": GetTokenSocialsResponse,
    "stats": GetTokenStatsResponse,
    "top_buyers": GetTopBuyersResponse,
    "trader_stat": GetTokenTraderStatResponse,
    "traders": GetTokenTradersResponse,
    "trades": GetTokenTradesResponse,
    "token_trades_v2": GetTokenTradesV2Response,
    "token_trends": GetTokenTrendsResponse,
    "wallet_tags_stat": GetTokenWalletTagsStatResponse,
    "website_info": GetWebsiteInfoResponse,
    "top_callers": GetTopCallersResponse,
    "wallet_activity": GetWalletActivityResponse,
    "wallet_chain_balances": GetWalletChainBalancesResponse,
    "wallet_common_stat": GetWalletCommonStatResponse,
    "wallet_pnl": GetSmartMoneyWalletResponse,
    "wallet_rankings": GetWalletRankingsResponse,
    "wallet_stat": GetWalletStatResponse,
}
METHODS = [
    "gas_price_list",
    "hot_searches",
    "live_twitch_kol",
    "major_coin_prices",
    "trending_tokens",
    "activity_rank_info",
    "agged_token_transfers",
    "bluechip_rank",
    "dev_created_tokens",
    "dex_trades_polling",
    "launchpad_tax_policy",
    "multi_token_full_info",
    "multi_token_info",
    "multi_window_token_info",
    "native_transfer",
    "new_pairs",
    "search",
    "similar_coin_extremes",
    "similar_coins",
    "smart_money_wallet_info",
    "swap_rankings",
    "token_info_brief",
    "token_prices",
    "token_signals",
    "agged_token_trades",
    "token_ai_narrative",
    "token_bundler_stat",
    "token_candles",
    "token_community_messages",
    "token_dev_info",
    "token_fee_distribution",
    "token_fee_info",
    "token_holder_extra_info",
    "holder_stat",
    "holders",
    "liquidity",
    "token_liquidity_stats",
    "token_liquidity_trend",
    "live_preview",
    "token_logo_history",
    "mcap_candles",
    "pool_fee_info",
    "recommend_slippage",
    "security",
    "socials",
    "stats",
    "top_buyers",
    "trader_stat",
    "traders",
    "trades",
    "token_trades_v2",
    "token_trends",
    "wallet_tags_stat",
    "website_info",
    "top_callers",
    "wallet_activity",
    "wallet_chain_balances",
    "wallet_common_stat",
    "wallet_pnl",
    "wallet_rankings",
    "wallet_stat",
]


def test_every_method_has_a_default_fixture() -> None:
    missing = [m for m in METHODS if not (FIXTURES / f"{m}.default.json").exists()]

    assert missing == [], f"run the generate-client capture step for {missing}"


@pytest.mark.parametrize("stem", cases(negative=False))
def test_a_captured_payload_parses_and_declares_every_field(stem: str) -> None:
    payload = json.loads((FIXTURES / f"{stem}.json").read_text())
    model = MODELS[stem.split(".", 1)[0]]
    parsed = model.model_validate(payload)

    assert extras(parsed, model.__name__) == []
    assert parsed.model_dump(mode="json", exclude_unset=True, by_alias=True) == payload
