# Generated by generate-client from spec/openapi.json. Do not edit.
"""Every captured ponsfamily payload, replayed through the model that has to hold it.

A payload that parses with nothing in ``model_extra`` and survives a round trip
proves the model still describes what the API sends.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import pydantic
import pytest

from conftest import extras
from tapline.ponsfamily import (
    GetAnalyticsResponse,
    GetCreatorHoldingsResponse,
    GetDeveloperTradesResponse,
    GetEthPriceResponse,
    GetFeeSharingResponse,
    GetForumCommunityResponse,
    GetForumHoldingResponse,
    GetForumMarketResponse,
    GetForumPostCommentsResponse,
    GetForumPostResponse,
    GetMarketAthResponse,
    GetMarketBurnedResponse,
    GetMarketChartResponse,
    GetMarketHoldersResponse,
    GetMarketOrderDepthResponse,
    GetMarketResponse,
    GetMarketTipResponse,
    GetPortfolioChartResponse,
    GetProfileResponse,
    GetTokenImagesResponse,
    GetTokenResponse,
    GetV2CreatorFeesResponse,
    GetV2DistributorResponse,
    GetV2MarketChartResponse,
    GetV2MarketHoldersResponse,
    GetV2MarketTradesResponse,
    GetWalletIdentitiesResponse,
    GetWalletPositionsResponse,
    Graduation,
    Launch,
    ListCtoMigrationsResponse,
    ListForumCommunitiesResponse,
    ListForumPostsResponse,
    ListLaunchesResponse,
    LiveMarket,
    MarketTrade,
    SearchLaunchesResponse,
)

FIXTURES = (
    Path(
        os.environ.get("GENERATE_CLIENT_FIXTURES")
        or Path(__file__).resolve().parents[2] / "fixtures"
    )
    / "ponsfamily"
)


def cases(negative: bool) -> list[str]:
    """Fixture stems on disk, positive or negative, in a stable order."""
    stems = sorted(
        p.name[: -len(".request.json")]
        for p in FIXTURES.glob("*.request.json")
        if (".neg." in p.name) is negative
    )
    return stems


RESPONSES: dict[str, type[Any]] = {
    "get_analytics": GetAnalyticsResponse,
    "list_cto_migrations": ListCtoMigrationsResponse,
    "get_eth_price": GetEthPriceResponse,
    "list_forum_communities": ListForumCommunitiesResponse,
    "get_forum_community": GetForumCommunityResponse,
    "get_forum_holding": GetForumHoldingResponse,
    "get_forum_market": GetForumMarketResponse,
    "list_forum_posts": ListForumPostsResponse,
    "get_forum_post": GetForumPostResponse,
    "get_forum_post_comments": GetForumPostCommentsResponse,
    "list_launches": ListLaunchesResponse,
    "list_graduated_catalog": list[Launch],
    "list_graduations": list[Graduation],
    "list_live_markets": list[LiveMarket],
    "search_launches": SearchLaunchesResponse,
    "get_market": GetMarketResponse,
    "get_market_ath": GetMarketAthResponse,
    "get_market_burned": GetMarketBurnedResponse,
    "get_market_chart": GetMarketChartResponse,
    "get_developer_trades": GetDeveloperTradesResponse,
    "get_market_holders": GetMarketHoldersResponse,
    "get_market_order_depth": GetMarketOrderDepthResponse,
    "get_market_tip": GetMarketTipResponse,
    "get_market_trades": list[MarketTrade],
    "get_creator_holdings": GetCreatorHoldingsResponse,
    "get_fee_sharing": GetFeeSharingResponse,
    "get_token_images": GetTokenImagesResponse,
    "get_token": GetTokenResponse,
    "get_v2_market_chart": GetV2MarketChartResponse,
    "get_v2_creator_fees": GetV2CreatorFeesResponse,
    "get_v2_distributor": GetV2DistributorResponse,
    "get_v2_market_holders": GetV2MarketHoldersResponse,
    "get_v2_market_trades": GetV2MarketTradesResponse,
    "get_wallet_identities": GetWalletIdentitiesResponse,
    "get_portfolio_chart": GetPortfolioChartResponse,
    "get_wallet_positions": GetWalletPositionsResponse,
    "get_profile": GetProfileResponse,
}
METHODS = [
    "get_analytics",
    "list_cto_migrations",
    "get_eth_price",
    "list_forum_communities",
    "get_forum_community",
    "get_forum_holding",
    "get_forum_market",
    "list_forum_posts",
    "get_forum_post",
    "get_forum_post_comments",
    "list_launches",
    "list_graduated_catalog",
    "list_graduations",
    "list_live_markets",
    "search_launches",
    "get_market",
    "get_market_ath",
    "get_market_burned",
    "get_market_chart",
    "get_developer_trades",
    "get_market_holders",
    "get_market_order_depth",
    "get_market_tip",
    "get_market_trades",
    "get_creator_holdings",
    "get_fee_sharing",
    "get_token_images",
    "get_token",
    "get_v2_market_chart",
    "get_v2_creator_fees",
    "get_v2_distributor",
    "get_v2_market_holders",
    "get_v2_market_trades",
    "get_wallet_identities",
    "get_portfolio_chart",
    "get_wallet_positions",
    "get_profile",
]


def test_every_method_has_a_default_fixture() -> None:
    missing = [m for m in METHODS if not (FIXTURES / f"{m}.default.json").exists()]

    assert missing == [], f"run the generate-client capture step for {missing}"


@pytest.mark.parametrize("stem", cases(negative=False))
def test_a_captured_payload_parses_and_declares_every_field(stem: str) -> None:
    payload = json.loads((FIXTURES / f"{stem}.json").read_text())
    method = stem.split(".", 1)[0]
    adapter: pydantic.TypeAdapter[Any] = pydantic.TypeAdapter(RESPONSES[method])
    parsed = adapter.validate_python(payload)

    assert extras(parsed, method) == []
    assert adapter.dump_python(parsed, mode="json", exclude_unset=True, by_alias=True) == payload
