# Generated by generate-client from spec/openapi.json. Do not edit.
# ruff: noqa: E501
"""Every type the twitter endpoints send and accept."""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, TypeAlias

from pydantic import Field

from tapline._models import PREFER_ENUM, BaseModel


class PublicError(str, Enum):
    BLOCKED = "blocked"
    CONCURRENCY_EXCEEDED = "concurrency_exceeded"
    TIMEOUT = "timeout"
    EXTRACTION_FAILED = "extraction_failed"
    UPSTREAM_BLOCKED = "upstream_blocked"
    UPSTREAM_UNAVAILABLE = "upstream_unavailable"
    UPSTREAM_RESPONSE_INVALID = "upstream_response_invalid"
    INVALID_URL_SCHEME = "invalid_url_scheme"
    INVALID_URL_HOST = "invalid_url_host"
    UNAUTHENTICATED = "unauthenticated"
    FORBIDDEN = "forbidden"
    RESOURCE_FORBIDDEN = "resource_forbidden"
    NOT_FOUND = "not_found"
    RATE_LIMITED = "rate_limited"
    INVALID_REQUEST = "invalid_request"
    INVALID_CURSOR = "invalid_cursor"
    INSUFFICIENT_CREDITS = "insufficient_credits"
    INTERNAL_ERROR = "internal_error"


class ErrorDetail(BaseModel):
    ctx: dict[str, Any] | None = None
    input: Any = None
    loc: list[str | int] | None = None
    msg: str | None = None
    type: str | None = None


class ErrorResponse(BaseModel):
    code: PublicErrorValue
    details: list[ErrorDetail] | None = None
    domain: str | None = None
    message: str
    request_id: str
    upgrade_url: str | None = None


class GetCommunityParams(BaseModel):
    community_id: Annotated[str, Field(examples=["1493446837214187523"], pattern="^[0-9]{1,19}$")]
    """
    Numeric X Community id, the digits after /i/communities/ in a community URL.
    """


class GetTweetParams(BaseModel):
    tweet_id: Annotated[str, Field(examples=["2106870968048386134"], pattern="^[0-9]{1,19}$")]
    """
    Numeric post (tweet) id, the digits after /status/ in a post URL.
    """


class GetUserProfileByIdParams(BaseModel):
    user_id: Annotated[str, Field(examples=["1952858158382428160"], pattern="^[0-9]{1,19}$")]
    """
    Numeric X user id (the account's rest_id).
    """


class GetUserProfileParams(BaseModel):
    screen_name: Annotated[str, Field(examples=["shivanipod"], pattern="^[A-Za-z0-9_]{1,15}$")]
    """
    X handle without the @: 1 to 15 letters, digits or underscores. x.com's own page names (explore, home, search, ...) are rejected.
    """


class TwitterArticle(BaseModel):
    cover_image_url: str | None
    id: str
    plain_text: str | None
    preview_text: str | None
    title: str


class TwitterCommunity(BaseModel):
    banner_url: str | None
    created_at: str
    creator: TwitterCommunityCreator | None
    description: str | None
    id: str
    is_nsfw: bool
    join_policy: str | None
    member_count: int
    name: str
    rules: list[TwitterCommunityRule]
    topic: str | None
    url: str


class TwitterCommunityCreator(BaseModel):
    id: str
    is_blue_verified: bool
    name: str | None
    screen_name: str


class TwitterCommunityResponse(BaseModel):
    community: TwitterCommunity
    tweets: list[TwitterTweet]


class TwitterCommunityRule(BaseModel):
    description: str | None
    name: str


class TwitterMedia(BaseModel):
    duration_ms: int | None
    expanded_url: str | None
    height: int | None
    id: str | None
    media_url: str
    type: str
    variants: list[TwitterVideoVariant]
    width: int | None


class TwitterMention(BaseModel):
    id: str | None
    screen_name: str


class TwitterProfileResponse(BaseModel):
    pinned_tweet: TwitterTweet | None
    tweets: list[TwitterTweet]
    user: TwitterUser


class TwitterTweet(BaseModel):
    article: TwitterArticle | None
    author: TwitterUser
    bookmark_count: int | None
    cashtags: list[str]
    created_at: str
    hashtags: list[str]
    id: str
    in_reply_to_screen_name: str | None
    in_reply_to_tweet_id: str | None
    lang: str | None
    like_count: int
    media: list[TwitterMedia]
    mentions: list[TwitterMention]
    quote_count: int
    quoted_tweet: TwitterTweet | None
    reply_count: int
    retweet_count: int
    text: str
    url: str
    urls: list[TwitterUrlEntity]
    view_count: int | None


class TwitterTweetDetailResponse(BaseModel):
    parent_tweets: list[TwitterTweet]
    replies: list[TwitterTweet]
    tweet: TwitterTweet


class TwitterUrlEntity(BaseModel):
    display_url: str | None
    expanded_url: str
    url: str


class TwitterUser(BaseModel):
    avatar_url: str | None
    banner_url: str | None
    bio_url: str | None
    created_at: str | None
    description: str | None
    description_mentions: list[TwitterMention]
    description_urls: list[TwitterUrlEntity]
    followers_count: int | None
    following_count: int | None
    id: str
    is_blue_verified: bool
    is_protected: bool
    location: str | None
    name: str | None
    profile_url: str
    screen_name: str
    tweet_count: int | None
    verified_type: str | None


class TwitterVideoVariant(BaseModel):
    bitrate: int | None
    content_type: str
    url: str


TwitterTweet.model_rebuild()


PublicErrorValue: TypeAlias = Annotated[PublicError | str, PREFER_ENUM]
