# Generated by generate-client from spec/openapi.json. Do not edit.
"""Every type the ponsfamily endpoints send and accept."""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, TypeAlias

from pydantic import Field, RootModel

from tapline._models import PREFER_ENUM, BaseModel


class ChartRange(str, Enum):
    FIELD_5M = "5m"
    FIELD_1H = "1h"
    FIELD_6H = "6h"
    FIELD_1D = "1d"
    ALL = "all"


class CommunityRank(str, Enum):
    MARKET_CAP = "marketCap"
    BURN_PCT = "burnPct"
    REAL_MCAP = "realMcap"


class LaunchAge(str, Enum):
    ALL = "all"
    FIELD_24H = "24h"
    FIELD_7D = "7d"


class LaunchSearchSort(str, Enum):
    RELEVANCE = "relevance"
    MARKET_CAP = "marketCap"
    VOLUME = "volume"
    NEWEST = "newest"
    OLDEST = "oldest"


class LaunchSort(str, Enum):
    RECENT_BUYS = "recentBuys"
    NEWEST = "newest"
    OLDEST = "oldest"
    MARKET_CAP = "marketCap"
    VOLUME = "volume"


class LaunchVersion(str, Enum):
    ALL = "all"
    V1 = "v1"
    V2 = "v2"


class PortfolioRange(str, Enum):
    FIELD_1D = "1d"
    FIELD_7D = "7d"
    FIELD_30D = "30d"


class PostSort(str, Enum):
    HOT = "hot"
    NEW = "new"
    TOP = "top"


class PublicError(str, Enum):
    BLOCKED = "blocked"
    CONCURRENCY_EXCEEDED = "concurrency_exceeded"
    TIMEOUT = "timeout"
    EXTRACTION_FAILED = "extraction_failed"
    UPSTREAM_BLOCKED = "upstream_blocked"
    UPSTREAM_UNAVAILABLE = "upstream_unavailable"
    UPSTREAM_RESPONSE_INVALID = "upstream_response_invalid"
    INVALID_URL_SCHEME = "invalid_url_scheme"
    INVALID_URL_HOST = "invalid_url_host"
    UNAUTHENTICATED = "unauthenticated"
    FORBIDDEN = "forbidden"
    RESOURCE_FORBIDDEN = "resource_forbidden"
    NOT_FOUND = "not_found"
    RATE_LIMITED = "rate_limited"
    INVALID_REQUEST = "invalid_request"
    INVALID_CURSOR = "invalid_cursor"
    INSUFFICIENT_CREDITS = "insufficient_credits"
    INTERNAL_ERROR = "internal_error"


class AnalyticsDay(BaseModel):
    launches: int | None = None
    timestamp: int | None = None
    trades: int | None = None
    volumeUsd: float | None = None


class AnalyticsTotals(BaseModel):
    creatorEarningsUsd: float | None = None
    launches24h: int | None = None
    launchesAllTime: int | None = None
    protocolRevenueUsd: float | None = None
    trades24h: int | None = None
    tradesAllTime: int | None = None
    uniqueDevelopers: int | None = None
    volumeUsd24h: float | None = None
    volumeUsdAllTime: float | None = None


class CommunityMarketCap(BaseModel):
    quote: float | None = None
    quoteSymbol: str | None = None
    usd: float | None = None


class CreatorHolding(BaseModel):
    deployer: str | None = None
    fraction: float | None = None
    token: str | None = None


class CreatorHoldingPair(BaseModel):
    deployer: Annotated[str, Field(examples=["0xB9F5f4Ea1AF1F5d3678470eb98e8FBdcadEb24b0"])]
    """
    Deployer wallet that launched the token.
    """
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address.
    """


class CreatorHoldingsRequest(BaseModel):
    pairs: Annotated[list[CreatorHoldingPair], Field(max_length=100, min_length=1)]
    """
    Token/deployer pairs to resolve, at most 100 per call.
    """


class CtoMigration(BaseModel):
    creditPot: str | None = None
    decimals: int | None = None
    epochCaps: list[str] | None = None
    epochDeposits: list[str] | None = None
    feeDestination: str | None = None
    fillOrTime: bool | None = None
    logoUrl: str | None = None
    migrator: str | None = None
    name: str | None = None
    newToken: str | None = None
    official: bool | None = None
    oldToken: str | None = None
    recoveredQuote: str | None = None
    schedule: MigrationSchedule | None = None
    seeded: bool | None = None
    seededAt: int | None = None
    soldOldTokens: str | None = None
    surplusQuote: str | None = None
    symbol: str | None = None
    totalCredits: str | None = None
    totalDeposits: str | None = None
    windowClosedAt: int | None = None


class DeveloperTradeEvent(BaseModel):
    blockNumber: int | None = None
    priceUsd: float | None = None
    timestamp: int | None = None
    toAddress: str | None = None
    tokenAmount: str | None = None
    tokenAmountDecimal: float | None = None
    transactionHash: str | None = None
    type: str | None = None
    valueUsd: float | None = None


class DistributorEpoch(BaseModel):
    coinClaimed: str | None = None
    coinTotal: str | None = None
    expiresAt: int | None = None
    id: int | None = None
    quoteClaimed: str | None = None
    quoteTotal: str | None = None
    rolledOver: bool | None = None


class ErrorDetail(BaseModel):
    ctx: dict[str, Any] | None = None
    input: Any = None
    loc: list[str | int] | None = None
    msg: str | None = None
    type: str | None = None


class ErrorResponse(BaseModel):
    code: PublicErrorValue
    details: list[ErrorDetail] | None = None
    domain: str | None = None
    message: str
    request_id: str
    upgrade_url: str | None = None


class FeeSharingEntry(BaseModel):
    active: bool | None = None
    token: str | None = None


class ForumBoardRow(BaseModel):
    communityId: str | None = None
    logo: str | None = None
    marketCap: CommunityMarketCap | None = None
    move: float | None = None
    name: str | None = None
    symbol: str | None = None
    tag: str | None = None
    token: str | None = None


class ForumComment(BaseModel):
    body: str | None = None
    createdAtMs: int | None = None
    depth: int | None = None
    downvotes: int | None = None
    editedAtMs: int | None = None
    id: str | None = None
    parentId: str | None = None
    postId: str | None = None
    removed: bool | None = None
    replies: list[ForumComment] | None = None
    score: int | None = None
    upvotes: int | None = None
    viewerVote: int | None = None
    wallet: str | None = None


class ForumCommunity(BaseModel):
    bannerKey: str | None = None
    burnedSupply: str | None = None
    buybackLockedSupply: str | None = None
    createdAtMs: int | None = None
    description: str | None = None
    graduated: bool | None = None
    id: str | None = None
    kind: str | None = None
    latestBuyAt: int | None = None
    latestBuyBlock: int | None = None
    launchVersion: str | None = None
    logo: str | None = None
    marketCap: CommunityMarketCap | None = None
    modWallet: str | None = None
    pairToken: str | None = None
    postCount: int | None = None
    realMcapUsd: float | None = None
    symbol: str | None = None
    title: str | None = None
    tokenAddress: str | None = None
    tokenDecimals: int | None = None
    totalSupply: str | None = None
    volume24hUsd: float | None = None


class ForumEquity(BaseModel):
    address: str | None = None
    assetClass: str | None = None
    logo: str | None = None
    move: float | None = None
    name: str | None = None
    priceUsd: float | None = None
    symbol: str | None = None


class ForumHolding(BaseModel):
    balance: str | None = None
    decimals: int | None = None
    supplyShare: float | None = None
    tier: str | None = None
    token: str | None = None
    totalSupply: str | None = None
    wallet: str | None = None


class ForumPosition(BaseModel):
    balance: str | None = None
    capturedAtMs: int | None = None
    decimals: int | None = None
    entryPriceQuote: float | None = None
    quoteToken: str | None = None
    symbol: str | None = None
    token: str | None = None


class ForumPost(BaseModel):
    body: str | None = None
    commentCount: int | None = None
    communityId: str | None = None
    communityLogo: str | None = None
    communitySymbol: str | None = None
    communityToken: str | None = None
    communityTokenDecimals: int | None = None
    createdAtMs: int | None = None
    downvotes: int | None = None
    editedAtMs: int | None = None
    id: str | None = None
    imageKey: str | None = None
    kind: str | None = None
    locked: bool | None = None
    pinned: bool | None = None
    position: ForumPosition | None = None
    removed: bool | None = None
    score: int | None = None
    title: str | None = None
    upvotes: int | None = None
    viewerVote: int | None = None
    wallet: str | None = None


class ForumSession(BaseModel):
    closeAtMs: int | None = None
    isEarlyClose: bool | None = None
    isTradingDay: bool | None = None
    nextTransitionAtMs: int | None = None
    openAtMs: int | None = None
    phase: str | None = None
    sessionDayKey: str | None = None


class GetAnalyticsResponse(BaseModel):
    generatedAt: int | None = None
    latestDay: int | None = None
    series: list[AnalyticsDay] | None = None
    sourceUrl: str | None = None
    totals: AnalyticsTotals | None = None


class GetCreatorHoldingsResponse(BaseModel):
    holdings: list[CreatorHolding] | None = None


class GetDeveloperTradesParams(BaseModel):
    deployer: Annotated[str, Field(examples=["0xB9F5f4Ea1AF1F5d3678470eb98e8FBdcadEb24b0"])]
    """
    Deployer wallet that launched the token.
    """
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetDeveloperTradesResponse(BaseModel):
    burnCount: int | None = None
    burned: bool | None = None
    buyCount: int | None = None
    deployer: str | None = None
    dumped: bool | None = None
    events: list[DeveloperTradeEvent] | None = None
    moveCount: int | None = None
    movedFunds: bool | None = None
    sellCount: int | None = None
    totalBurnedTokens: float | None = None
    totalMovedTokens: float | None = None
    totalSoldUsd: float | None = None


class GetEthPriceResponse(BaseModel):
    updatedAt: int | None = None
    usd: float | None = None


class GetFeeSharingParams(BaseModel):
    tokens: Annotated[
        list[str],
        Field(examples=[["0x39dBED3a2bd333467115dE45665cC57F813C4571"]], max_length=100),
    ]
    """
    Token contract addresses to resolve, at most 100 per call.
    """


class GetFeeSharingResponse(BaseModel):
    sharing: list[FeeSharingEntry] | None = None


class GetForumCommunityParams(BaseModel):
    slug: Annotated[str, Field(examples=["pons-39db"])]
    """
    Forum community slug.
    """


class GetForumCommunityResponse(BaseModel):
    community: ForumCommunity | None = None


class GetForumHoldingParams(BaseModel):
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """
    wallet: Annotated[str, Field(examples=["0x42e9c498135431a48796B5fFe2CBC3d7A1811927"])]
    """
    Wallet address.
    """


class GetForumHoldingResponse(BaseModel):
    holding: ForumHolding | None = None
    priceQuote: float | None = None


class GetForumMarketResponse(BaseModel):
    bell: str | None = None
    markets: list[ForumEquity] | None = None
    rows: list[ForumBoardRow] | None = None
    session: ForumSession | None = None


class GetForumPostCommentsParams(BaseModel):
    post_id: Annotated[str, Field(examples=["abf85222-da1a-49f9-963b-eded304a41d4"])]
    """
    Forum post UUID.
    """
    sort: PostSort | None = PostSort.HOT
    """
    Comment ranking.
    """


class GetForumPostCommentsResponse(BaseModel):
    comments: list[ForumComment] | None = None


class GetForumPostParams(BaseModel):
    post_id: Annotated[str, Field(examples=["abf85222-da1a-49f9-963b-eded304a41d4"])]
    """
    Forum post UUID.
    """


class GetForumPostResponse(BaseModel):
    post: ForumPost | None = None


class GetMarketAthParams(BaseModel):
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetMarketAthResponse(BaseModel):
    blockNumber: int | None = None
    pool: str | None = None
    priceEth: float | None = None
    timestamp: str | None = None
    token: str | None = None
    updatedAt: int | None = None


class GetMarketBurnedParams(BaseModel):
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetMarketBurnedResponse(BaseModel):
    burnedWei: str | None = None
    token: str | None = None


class GetMarketChartParams(BaseModel):
    range: ChartRange | None = ChartRange.FIELD_1H
    """
    Chart window.
    """
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetMarketChartResponse(BaseModel):
    intervalSeconds: int | None = None
    points: list[MarketChartPoint] | None = None
    range: str | None = None
    source: str | None = None
    token: str | None = None
    updatedAt: int | None = None


class GetMarketHoldersParams(BaseModel):
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetMarketHoldersResponse(BaseModel):
    holders: list[MarketHolder] | None = None
    holdersCount: int | None = None


class GetMarketOrderDepthParams(BaseModel):
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetMarketOrderDepthResponse(BaseModel):
    activeOrderCount: int | None = None
    bands: list[OrderDepthBand] | None = None
    currentPriceEth: float | None = None
    generatedAt: int | None = None
    observedBlockNumber: int | None = None
    pool: str | None = None
    token: str | None = None


class GetMarketParams(BaseModel):
    include_holders: bool | None = False
    """
    Include the holder list in the snapshot.
    """
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetMarketResponse(BaseModel):
    changePct: float | None = None
    holders: list[MarketHolder] | None = None
    holdersCount: int | None = None
    liquidityUsd: float | None = None
    marketCapUsd: float | None = None
    points: list[MarketPricePoint] | None = None
    pool: str | None = None
    priceEth: float | None = None
    priceUsd: float | None = None
    token: str | None = None
    trades: list[MarketTrade] | None = None
    updatedAt: int | None = None
    volume24hUsd: float | None = None


class GetMarketTipParams(BaseModel):
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetMarketTipResponse(BaseModel):
    pool: str | None = None
    priceEth: float | None = None
    token: str | None = None
    updatedAt: int | None = None


class GetMarketTradesParams(BaseModel):
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetPortfolioChartParams(BaseModel):
    address: Annotated[str, Field(examples=["0x42e9c498135431a48796B5fFe2CBC3d7A1811927"])]
    """
    Wallet address.
    """
    range: PortfolioRange | None = PortfolioRange.FIELD_1D
    """
    Chart window.
    """


class GetPortfolioChartResponse(BaseModel):
    address: str | None = None
    changePct: float | None = None
    changeUsd: float | None = None
    currentValueUsd: float | None = None
    points: list[PortfolioChartPoint] | None = None
    range: str | None = None
    tokenCount: int | None = None
    updatedAt: int | None = None


class GetProfileParams(BaseModel):
    address: Annotated[str, Field(examples=["0x42e9c498135431a48796B5fFe2CBC3d7A1811927"])]
    """
    Wallet address.
    """


class GetProfileResponse(BaseModel):
    ethUsd: float | None = None
    launches: list[ProfileLaunch] | None = None


class GetTokenImagesParams(BaseModel):
    tokens: Annotated[
        list[str],
        Field(examples=[["0x39dBED3a2bd333467115dE45665cC57F813C4571"]], max_length=100),
    ]
    """
    Token contract addresses to resolve, at most 100 per call.
    """


class GetTokenImagesResponse(RootModel[dict[str, str]]):
    """
    Logo URL keyed by lower-cased token address.
    """

    root: dict[str, str]


class GetTokenParams(BaseModel):
    token: Annotated[str, Field(examples=["0x39dBED3a2bd333467115dE45665cC57F813C4571"])]
    """
    Token contract address on Robinhood Chain.
    """


class GetTokenResponse(BaseModel):
    deployer: str | None = None
    description: str | None = None
    initialBuyWei: str | None = None
    isToken0: bool | None = None
    locker: str | None = None
    logo: str | None = None
    name: str | None = None
    pairToken: str | None = None
    pool: str | None = None
    poolFee: int | None = None
    positionId: str | None = None
    positionManager: str | None = None
    restrictionEndBlock: str | None = None
    router: str | None = None
    routerRequiresDeadline: bool | None = None
    socials: TokenSocials | None = None
    symbol: str | None = None
    tickSpacing: int | None = None
    token: str | None = None
    totalSupplyWei: str | None = None


class GetV2CreatorFeesParams(BaseModel):
    token: Annotated[str, Field(examples=["0xD5f1afEA47b1A9eab414D2ee740cF1d6d039E725"])]
    """
    Token contract address of a v2 (curve) launch.
    """


class GetV2CreatorFeesResponse(BaseModel):
    claimableForWallet: str | None = None
    earnedForToken: str | None = None
    feeEscrow: str | None = None
    nothingToClaim: bool | None = None
    quoteAsset: QuoteAsset | None = None
    recipient: str | None = None
    sweepCount: int | None = None
    token: str | None = None


class GetV2DistributorParams(BaseModel):
    token: Annotated[str, Field(examples=["0xD5f1afEA47b1A9eab414D2ee740cF1d6d039E725"])]
    """
    Token contract address of a v2 (curve) launch.
    """


class GetV2DistributorResponse(BaseModel):
    distributedCoin: str | None = None
    distributedQuote: str | None = None
    distributor: str | None = None
    epochCount: int | None = None
    latestEpoch: DistributorEpoch | None = None
    state: str | None = None
    unallocatedCoin: str | None = None
    unallocatedQuote: str | None = None


class GetV2MarketChartParams(BaseModel):
    range: ChartRange | None = ChartRange.FIELD_1H
    """
    Chart window.
    """
    token: Annotated[str, Field(examples=["0xD5f1afEA47b1A9eab414D2ee740cF1d6d039E725"])]
    """
    Token contract address of a v2 (curve) launch.
    """


class GetV2MarketChartResponse(BaseModel):
    intervalSeconds: int | None = None
    points: list[V2ChartPoint] | None = None
    quoteSymbol: str | None = None
    quoteUsd: float | None = None
    range: str | None = None
    token: str | None = None
    updatedAt: int | None = None


class GetV2MarketHoldersParams(BaseModel):
    token: Annotated[str, Field(examples=["0xD5f1afEA47b1A9eab414D2ee740cF1d6d039E725"])]
    """
    Token contract address of a v2 (curve) launch.
    """


class GetV2MarketHoldersResponse(BaseModel):
    holders: list[V2Holder] | None = None
    holdersCount: int | None = None


class GetV2MarketTradesParams(BaseModel):
    token: Annotated[str, Field(examples=["0xD5f1afEA47b1A9eab414D2ee740cF1d6d039E725"])]
    """
    Token contract address of a v2 (curve) launch.
    """


class GetV2MarketTradesResponse(BaseModel):
    trades: list[V2Trade] | None = None


class GetWalletIdentitiesParams(BaseModel):
    addresses: Annotated[
        list[str],
        Field(examples=[["0x42e9c498135431a48796B5fFe2CBC3d7A1811927"]], max_length=100),
    ]
    """
    Wallet addresses to resolve, at most 100 per call.
    """


class GetWalletIdentitiesResponse(BaseModel):
    identities: list[WalletIdentity] | None = None


class GetWalletPositionsParams(BaseModel):
    address: Annotated[str, Field(examples=["0x42e9c498135431a48796B5fFe2CBC3d7A1811927"])]
    """
    Wallet address.
    """


class GetWalletPositionsResponse(BaseModel):
    activity: list[WalletActivity] | None = None
    address: str | None = None
    positions: list[WalletPosition] | None = None
    totals: WalletTotals | None = None
    updatedAt: int | None = None


class Graduation(BaseModel):
    graduatedAt: str | None = None
    observedBlockNumber: int | None = None
    token: str | None = None


class Launch(BaseModel):
    blockNumber: int | None = None
    burnedPct: float | None = None
    deployer: str | None = None
    description: str | None = None
    factory: str | None = None
    graduated: bool | None = None
    graduatedAt: str | None = None
    graduatedBlockNumber: int | None = None
    graduationProgressPct: float | None = None
    graduationThresholdEth: float | None = None
    initialBuyWei: str | None = None
    isOriginal: bool | None = None
    latestBuyAt: str | None = None
    latestBuyBlockNumber: int | None = None
    launchedAt: str | None = None
    liquidityUsd: float | None = None
    logo: str | None = None
    marketCapUsd: float | None = None
    name: str | None = None
    pairToken: str | None = None
    pairedPrincipalEth: float | None = None
    pool: str | None = None
    priceUsd: float | None = None
    quoteAsset: QuoteAsset | None = None
    realMcapUsd: float | None = None
    symbol: str | None = None
    token: str | None = None
    transactionHash: str | None = None
    venue: str | None = None
    version: str | None = None
    volume24hUsd: float | None = None


class LaunchPage(BaseModel):
    items: list[Launch] | None = None
    page: int | None = None
    pageSize: int | None = None
    total: int | None = None


class ListCtoMigrationsResponse(BaseModel):
    migrations: list[CtoMigration] | None = None


class ListForumCommunitiesParams(BaseModel):
    limit: Annotated[int | None, Field(ge=1, le=100)] = 10
    """
    Number of communities to return.
    """
    rank: CommunityRank | None = CommunityRank.MARKET_CAP
    """
    Ranking column.
    """


class ListForumCommunitiesResponse(BaseModel):
    communities: list[ForumCommunity] | None = None


class ListForumPostsParams(BaseModel):
    community: Annotated[str | None, Field(examples=["pons-39db"])] = None
    """
    Restrict the feed to one community slug.
    """
    sort: PostSort | None = PostSort.HOT
    """
    Feed ranking.
    """


class ListForumPostsResponse(BaseModel):
    posts: list[ForumPost] | None = None


class ListLaunchesParams(BaseModel):
    age: LaunchAge | None = LaunchAge.ALL
    """
    Only include launches from this window.
    """
    graduated_page: Annotated[int | None, Field(ge=1)] = 1
    """
    Page of graduated launches.
    """
    graduated_page_size: Annotated[int | None, Field(ge=1, le=100)] = 10
    """
    Graduated launches per page.
    """
    include_graduated: bool | None = True
    """
    Include the graduated board in the response.
    """
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    Page of active launches.
    """
    page_size: Annotated[int | None, Field(ge=1, le=500)] = 50
    """
    Active launches per page.
    """
    sort: LaunchSort | None = LaunchSort.RECENT_BUYS
    """
    Ranking column for the active board.
    """
    version: LaunchVersion | None = LaunchVersion.ALL
    """
    Restrict to a launchpad version.
    """


class ListLaunchesResponse(BaseModel):
    active: LaunchPage | None = None
    activeTotal: int | None = None
    generatedAt: int | None = None
    graduated: LaunchPage | None = None
    graduatedTotal: int | None = None
    launchTotal: int | None = None


class ListLiveMarketsParams(BaseModel):
    markets: Annotated[
        list[str] | None,
        Field(examples=[["0x39dBED3a2bd333467115dE45665cC57F813C4571"]], max_length=100),
    ] = None
    """
    Restrict the live-market snapshot to these token addresses, at most 100 per call.
    """


class LiveMarket(BaseModel):
    graduated: bool | None = None
    graduationProgressPct: float | None = None
    graduationThresholdEth: float | None = None
    latestBuyAt: str | None = None
    latestBuyBlockNumber: int | None = None
    latestMarketBlockNumber: int | None = None
    marketCapUsd: float | None = None
    pairedPrincipalEth: float | None = None
    pool: str | None = None
    priceUsd: float | None = None
    token: str | None = None


class MarketChartPoint(BaseModel):
    blockNumber: int | None = None
    priceEth: float | None = None
    t: int | None = None
    tradeCount: int | None = None
    volumeEth: float | None = None


class MarketHolder(BaseModel):
    address: str | None = None
    balance: str | None = None
    entryMcapUsd: float | None = None
    percentage: float | None = None
    pnlPct: float | None = None
    pnlUsd: float | None = None


class MarketPricePoint(BaseModel):
    blockNumber: int | None = None
    priceUsd: float | None = None
    t: int | None = None


class MarketTrade(BaseModel):
    blockNumber: int | None = None
    ethAmount: str | None = None
    priceUsd: float | None = None
    recipient: str | None = None
    side: str | None = None
    timestamp: int | None = None
    tokenAmount: str | None = None
    transactionHash: str | None = None
    valueUsd: float | None = None


class MigrationSchedule(BaseModel):
    claimEnd: int | None = None
    claimStart: int | None = None
    claimVest: int | None = None
    decayStepBps: int | None = None
    depositEnd: int | None = None
    depositStart: int | None = None
    epochCount: int | None = None
    epochCursor: int | None = None
    epochDuration: int | None = None
    epochOpenedAt: int | None = None
    launchAt: int | None = None
    minDeposits: str | None = None
    seedDeadline: int | None = None
    sellEnd: int | None = None
    sellStart: int | None = None
    settleAt: int | None = None
    windowSeconds: int | None = None


class OrderDepthBand(BaseModel):
    depthUsd: float | None = None
    inputRemaining: str | None = None
    orderCount: int | None = None
    priceEth: float | None = None
    side: str | None = None
    targetTick: int | None = None


class PortfolioChartPoint(BaseModel):
    t: int | None = None
    valueUsd: float | None = None


class ProfileLaunch(BaseModel):
    claimable: bool | None = None
    claimableTokenWei: str | None = None
    claimableWethWei: str | None = None
    claimedTokenWei: str | None = None
    claimedWethWei: str | None = None
    isDeployer: bool | None = None
    isFeeRecipient: bool | None = None
    locker: str | None = None
    logo: str | None = None
    name: str | None = None
    symbol: str | None = None
    token: str | None = None


class QuoteAsset(BaseModel):
    address: str | None = None
    assetClass: str | None = None
    decimals: int | None = None
    isNative: bool | None = None
    name: str | None = None
    symbol: str | None = None


class SearchLaunchesParams(BaseModel):
    age: LaunchAge | None = LaunchAge.ALL
    """
    Only include launches from this window.
    """
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    Result page.
    """
    q: Annotated[str | None, Field(examples=["pons"])] = ""
    """
    Free-text query matched against token name, symbol and address.
    """
    sort: LaunchSearchSort | None = LaunchSearchSort.RELEVANCE
    """
    Ranking column for the result set.
    """


class SearchLaunchesResponse(BaseModel):
    items: list[Launch] | None = None
    page: int | None = None
    pageSize: int | None = None
    total: int | None = None


class TokenSocials(BaseModel):
    discord: str | None = None
    farcaster: str | None = None
    telegram: str | None = None
    twitter: str | None = None


class V2ChartPoint(BaseModel):
    blockNumber: int | None = None
    price: float | None = None
    t: int | None = None
    tradeCount: int | None = None
    volumeQuote: float | None = None


class V2Holder(BaseModel):
    address: str | None = None
    balance: str | None = None
    percentage: float | None = None


class V2Trade(BaseModel):
    account: str | None = None
    blockNumber: int | None = None
    id: str | None = None
    quoteAmount: str | None = None
    side: str | None = None
    timestamp: int | None = None
    tokenAmount: str | None = None
    transactionHash: str | None = None
    venue: str | None = None


class WalletActivity(BaseModel):
    blockNumber: int | None = None
    ethAmount: str | None = None
    logo: str | None = None
    name: str | None = None
    priceUsd: float | None = None
    side: str | None = None
    symbol: str | None = None
    timestamp: int | None = None
    token: str | None = None
    tokenAmount: str | None = None
    transactionHash: str | None = None
    valueUsd: float | None = None


class WalletIdentity(BaseModel):
    avatarKey: str | None = None
    avatarUrl: str | None = None
    bannerKey: str | None = None
    bannerUrl: str | None = None
    createdAtMs: int | None = None
    description: str | None = None
    displayName: str | None = None
    joinedAtMs: int | None = None
    updatedAtMs: int | None = None
    username: str | None = None
    wallet: str | None = None


class WalletPosition(BaseModel):
    amountTokens: float | None = None
    balance: str | None = None
    buys: int | None = None
    currentMcapUsd: float | None = None
    currentPriceUsd: float | None = None
    decimals: int | None = None
    entryMcapUsd: float | None = None
    entryPriceUsd: float | None = None
    firstTradeAt: int | None = None
    investedUsd: float | None = None
    lastTradeAt: int | None = None
    logo: str | None = None
    name: str | None = None
    pnlReliable: bool | None = None
    pool: str | None = None
    realizedPnlUsd: float | None = None
    sells: int | None = None
    state: str | None = None
    supplyTokens: float | None = None
    symbol: str | None = None
    token: str | None = None
    totalPnlPct: float | None = None
    totalPnlUsd: float | None = None
    unrealizedPnlUsd: float | None = None
    valueUsd: float | None = None
    version: str | None = None


class WalletTotals(BaseModel):
    investedUsd: float | None = None
    openPositions: int | None = None
    pnlTrackedPositions: int | None = None
    portfolioValueUsd: float | None = None
    realizedPnlUsd: float | None = None
    tokensTraded: int | None = None
    totalPnlPct: float | None = None
    totalPnlUsd: float | None = None
    unrealizedPnlUsd: float | None = None
    winRate: float | None = None


ForumComment.model_rebuild()


ChartRangeParam: TypeAlias = ChartRange | Literal["5m", "1h", "6h", "1d", "all"]
CommunityRankParam: TypeAlias = CommunityRank | Literal["marketCap", "burnPct", "realMcap"]
LaunchAgeParam: TypeAlias = LaunchAge | Literal["all", "24h", "7d"]
LaunchSearchSortParam: TypeAlias = (
    LaunchSearchSort | Literal["relevance", "marketCap", "volume", "newest", "oldest"]
)
LaunchSortParam: TypeAlias = (
    LaunchSort | Literal["recentBuys", "newest", "oldest", "marketCap", "volume"]
)
LaunchVersionParam: TypeAlias = LaunchVersion | Literal["all", "v1", "v2"]
PortfolioRangeParam: TypeAlias = PortfolioRange | Literal["1d", "7d", "30d"]
PostSortParam: TypeAlias = PostSort | Literal["hot", "new", "top"]
PublicErrorValue: TypeAlias = Annotated[PublicError | str, PREFER_ENUM]
