# Generated by generate-client from spec/openapi.json. Do not edit.
# ruff: noqa: E501, E741, RUF012
"""Every type the gmgn endpoints send and accept."""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, TypeAlias

from pydantic import Field

from tapline._models import PREFER_ENUM, BaseModel


class AggedTradePeriod(str, Enum):
    FIELD_1M = "1m"
    FIELD_5M = "5m"
    FIELD_1H = "1h"
    FIELD_4H = "4h"


class AggedTradeTag(str, Enum):
    DEV_TEAM = "dev_team"
    SMART_DEGEN = "smart_degen"
    INSIDER = "insider"
    SNIPER = "sniper"
    BUNDLER = "bundler"
    FRESH_WALLET = "fresh_wallet"
    BLUECHIP_OWNER = "bluechip_owner"
    RENOWNED = "renowned"
    RAT_TRADER = "rat_trader"


class Chain(str, Enum):
    SOL = "sol"
    ETH = "eth"
    BSC = "bsc"
    BASE = "base"
    TRON = "tron"
    MONAD = "monad"
    MEGAETH = "megaeth"
    HYPEREVM = "hyperevm"
    ROBINHOOD = "robinhood"
    ARBITRUM = "arbitrum"
    ARC = "arc"
    STABLE = "stable"
    XLAYER = "xlayer"


class HolderOrderBy(str, Enum):
    AMOUNT_PERCENTAGE = "amount_percentage"
    LAST_ACTIVE_TIMESTAMP = "last_active_timestamp"
    NETFLOW_USD = "netflow_usd"
    PROFIT = "profit"
    REALIZED_PROFIT = "realized_profit"
    UNREALIZED_PROFIT = "unrealized_profit"
    BUY_VOLUME_CUR = "buy_volume_cur"
    SELL_VOLUME_CUR = "sell_volume_cur"


class HolderTag(str, Enum):
    SMART_DEGEN = "smart_degen"
    FRESH_WALLET = "fresh_wallet"
    RENOWNED = "renowned"
    BUNDLER = "bundler"
    BLUECHIP_OWNER = "bluechip_owner"
    SNIPER = "sniper"
    RAT_TRADER = "rat_trader"
    DEV = "dev"
    TRANSFER_IN = "transfer_in"
    DEX_BOT = "dex_bot"


class NewPairsOrderBy(str, Enum):
    OPEN_TIMESTAMP = "open_timestamp"
    CREATION_TIMESTAMP = "creation_timestamp"
    MARKET_CAP = "market_cap"
    HOLDER_COUNT = "holder_count"
    LIQUIDITY = "liquidity"
    VOLUME = "volume"
    SWAPS = "swaps"
    PROGRESS = "progress"
    PRICE_CHANGE_PERCENT1H = "price_change_percent1h"


class PublicError(str, Enum):
    BLOCKED = "blocked"
    CONCURRENCY_EXCEEDED = "concurrency_exceeded"
    TIMEOUT = "timeout"
    EXTRACTION_FAILED = "extraction_failed"
    UPSTREAM_BLOCKED = "upstream_blocked"
    UPSTREAM_UNAVAILABLE = "upstream_unavailable"
    UPSTREAM_RESPONSE_INVALID = "upstream_response_invalid"
    INVALID_URL_SCHEME = "invalid_url_scheme"
    INVALID_URL_HOST = "invalid_url_host"
    UNAUTHENTICATED = "unauthenticated"
    FORBIDDEN = "forbidden"
    RESOURCE_FORBIDDEN = "resource_forbidden"
    NOT_FOUND = "not_found"
    RATE_LIMITED = "rate_limited"
    INVALID_REQUEST = "invalid_request"
    INVALID_CURSOR = "invalid_cursor"
    INSUFFICIENT_CREDITS = "insufficient_credits"
    INTERNAL_ERROR = "internal_error"


class Resolution(str, Enum):
    FIELD_1S = "1s"
    FIELD_15S = "15s"
    FIELD_30S = "30s"
    FIELD_1M = "1m"
    FIELD_3M = "3m"
    FIELD_5M = "5m"
    FIELD_15M = "15m"
    FIELD_30M = "30m"
    FIELD_1H = "1h"
    FIELD_4H = "4h"
    FIELD_12H = "12h"
    FIELD_1D = "1d"
    FIELD_1W = "1w"
    FIELD_1MO = "1mo"


class SimilarCoinsOrderBy(str, Enum):
    MCP = "mcp"
    OPEN_OR_CREATE_TIME = "open_or_create_time"


class SortDirection(str, Enum):
    DESC = "desc"


class TimeWindow(str, Enum):
    FIELD_1H = "1h"
    FIELD_24H = "24h"


class TokenFilter(str, Enum):
    NOT_HONEYPOT = "not_honeypot"
    VERIFIED = "verified"
    RENOUNCED = "renounced"
    FROZEN = "frozen"
    HAS_SOCIAL = "has_social"
    BURN = "burn"


class TokenTrendsType(str, Enum):
    AVG_HOLDING_BALANCE = "avg_holding_balance"
    HOLDER_COUNT = "holder_count"
    TOP10_HOLDER_PERCENT = "top10_holder_percent"
    TOP100_HOLDER_PERCENT = "top100_holder_percent"
    BUNDLER_PERCENT = "bundler_percent"
    INSIDER_PERCENT = "insider_percent"
    BOT_DEGEN_PERCENT = "bot_degen_percent"
    ENTRAPMENT_PERCENT = "entrapment_percent"


class TraderOrderBy(str, Enum):
    PROFIT = "profit"
    REALIZED_PROFIT = "realized_profit"
    UNREALIZED_PROFIT = "unrealized_profit"
    AMOUNT_PERCENTAGE = "amount_percentage"
    LAST_ACTIVE_TIMESTAMP = "last_active_timestamp"
    NETFLOW_USD = "netflow_usd"
    BUY_VOLUME_CUR = "buy_volume_cur"
    SELL_VOLUME_CUR = "sell_volume_cur"


class TrendingInterval(str, Enum):
    FIELD_1M = "1m"
    FIELD_5M = "5m"
    FIELD_1H = "1h"
    FIELD_6H = "6h"
    FIELD_24H = "24h"


class WalletRankOrderBy(str, Enum):
    PNL_1D = "pnl_1d"
    PNL_7D = "pnl_7d"
    PNL_30D = "pnl_30d"
    WINRATE_1D = "winrate_1d"
    WINRATE_7D = "winrate_7d"
    WINRATE_30D = "winrate_30d"


class WalletRankPeriod(str, Enum):
    FIELD_1D = "1d"
    FIELD_7D = "7d"
    FIELD_30D = "30d"


class WalletStatPeriod(str, Enum):
    FIELD_1D = "1d"
    FIELD_7D = "7d"
    ALL = "all"


class ActivityRankInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]


class AddressListRequest(BaseModel):
    addresses: list[str]


class AggedTokenTradesParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    period: AggedTradePeriod | None = AggedTradePeriod.FIELD_1H
    """
    Bucket size.
    """
    tag: AggedTradeTag | None = None
    """
    Wallet cohort to filter on. Omit for all wallets.
    """
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class AggedTokenTransfersParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    period: AggedTradePeriod | None = AggedTradePeriod.FIELD_1H
    """
    Bucket size.
    """
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]
    wallet_address: Annotated[str, Field(examples=["354zHMonLVarpvVHXvPgtJwkNXriana7RdEsBq7bCxGN"])]
    """
    Wallet whose transfers are aggregated.
    """


class AggedTrade(BaseModel):
    avatar: str
    buy_amount: str
    buy_count: int
    buy_quote_address: str
    buy_quote_amount: str
    buy_usd_amount: str
    claim_count: int
    claim_quote_address: str
    claim_quote_amount: str
    ens: str
    is_boost: bool
    is_close: bool
    is_open: bool
    max_seq_index: str
    name: str
    nickname: str
    platform: str
    platform_avatar: str
    platform_username: str
    pump_social_claim_count: int
    pump_social_claim_quote_address: str
    pump_social_claim_quote_amount: str
    sell_amount: str
    sell_count: int
    sell_quote_address: str
    sell_quote_amount: str
    sell_usd_amount: str
    twitter_name: str
    twitter_username: str
    wallet_address: str


class AggedTradeBucket(BaseModel):
    timestamp: int
    trades: list[AggedTrade]


class AggedTransfer(BaseModel):
    max_seq_index: str
    transfer_in_amount: str
    transfer_in_avg_price: str
    transfer_in_count: int
    transfer_in_usd_amount: str
    transfer_out_amount: str
    transfer_out_avg_price: str
    transfer_out_count: int
    transfer_out_usd_amount: str
    wallet_address: str


class AggedTransferBucket(BaseModel):
    timestamp: int
    transfers: list[AggedTransfer]


class BluechipRankParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    filters: list[TokenFilter] | None = None
    """
    Security screens applied before ranking.
    """
    interval: TrendingInterval | None = TrendingInterval.FIELD_1H
    """
    Ranking window.
    """
    limit: Annotated[int | None, Field(ge=1, le=500)] = 100
    """
    Maximum tokens to return.
    """


class BluechipSecurityInfo(BaseModel):
    burn_ratio: str
    burn_status: str
    dev_token_burn_amount: str
    dev_token_burn_ratio: str
    is_show_alert: bool
    renounced_freeze_account: int | None = None
    renounced_mint: int | None = None
    top_10_holder_rate: str


class BluechipToken(BaseModel):
    address: str
    at_least_one_link: bool
    bluechip_rate: str
    bot_degen_count: int
    bot_degen_rate: float
    bundler_rate: str
    buys: int
    chain: str
    creator: str
    creator_token_status: str
    cto_flag: int
    dev_team_hold_rate: float
    dexscr_ad: int
    dexscr_ad_ts: int
    dexscr_boost_fee: int
    dexscr_boost_ts: int
    dexscr_trending_bar: int
    dexscr_trending_bar_ts: int
    dexscr_update_link: int
    dexscr_update_link_ts: int
    entrapment_ratio: str
    history_highest_market_cap: int
    holder_count: int
    hot_level: int
    image_dup: str
    is_show_alert: bool
    is_wash_trading: bool
    launchpad: str
    launchpad_platform: str
    launchpad_status: int
    liquidity: str
    logo: str
    market_cap: str
    open_timestamp: int
    price: str
    price_change_percent_1h: str
    price_change_percent_1m: str
    price_change_percent_5m: str
    rat_trader_amount_rate: str
    security_info: BluechipSecurityInfo
    sells: int
    smart_buys_24h: int
    smart_sells_24h: int
    swaps: int
    symbol: str
    telegram_dup: int
    token_links: BluechipTokenLinks
    top70_sniper_hold_rate: float
    twitter_change_flag: int
    twitter_dup: int
    twitter_rename_count: int
    volume: str
    website_dup: int


class BluechipTokenLinks(BaseModel):
    address: str
    bitbucket: str
    description: str
    discord: str
    facebook: str
    fracaster: Any
    geckoterminal: str
    github: str
    gmgn: str
    instagram: str
    linkedin: str
    medium: str
    reddit: str
    telegram: str
    tiktok: str
    twitter_username: str
    verify_status: int
    website: str
    youtube: str


class DevCreatedToken(BaseModel):
    biggest_pool: str
    bundler_rate: float
    chain: str
    coin_creator_fee: float
    coin_creator_fee_token_address: str
    create_timestamp: int
    cto_flag: bool
    dexscr_ad: bool
    dexscr_update_link: bool
    holders: int
    is_open: bool
    is_pump: bool
    launchpad_platform: str
    liquidity_less_4k: bool
    logo: str
    marcket_cap: str
    market_cap: str
    pool_liquidity: str
    swap_1h: int
    symbol: str
    token_address: str
    token_ath_mc: str
    total_fee: str
    twitter_name_change_history: list[str]
    volume_1h: str


class DevCreatedTokensParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    wallet_address: Annotated[str, Field(examples=["suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"])]


class DevCreatorAthInfo(BaseModel):
    ath_mc: str
    ath_token: str
    creator: str
    token_logo: str
    token_name: str
    token_symbol: str


class DexAggregationResult(BaseModel):
    buyCount: int
    buyCountChangeRate: float
    buyVolume: float
    buyVolumeChangeRate: float
    chain: str
    dexName: str
    sellCount: int
    sellCountChangeRate: float
    sellVolume: float
    sellVolumeChangeRate: float
    tokenStatsCreated: int
    tokenStatsCreatedChangeRate: float
    tokenStatsMigrations: int
    tokenStatsMigrationsChangeRate: float
    tradeCount: int
    tradeCountChangeRate: float
    tradeVolume: float
    tradeVolumeChangeRate: float
    traderCount: int
    traderCountChangeRate: float


class DexTradesPollingParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    window: TimeWindow | None = TimeWindow.FIELD_24H


class ErrorDetail(BaseModel):
    ctx: dict[str, Any] | None = None
    input: Any = None
    loc: list[str | int] | None = None
    msg: str | None = None
    type: str | None = None


class ErrorResponse(BaseModel):
    code: PublicErrorValue
    details: list[ErrorDetail] | None = None
    domain: str | None = None
    message: str
    request_id: str
    upgrade_url: str | None = None


class FeeDistributionCharity(BaseModel):
    id: str
    logo: str
    name: str
    slug: str
    website: str
    weight: str


class FeeDistributionPlatform(BaseModel):
    bonus_category: list[str]
    fee_authority: str
    is_charity: bool
    is_locked: bool
    list_: Annotated[list[FeeDistributionRecipient], Field(alias="list")]
    show: bool


class FeeDistributionRecipient(BaseModel):
    charities: list[FeeDistributionCharity] | None = None
    has_claimed_fee: bool
    is_charity: bool
    is_creator: bool
    pfp: str
    royalty_bps: int
    twitter_username: str
    username: str
    wallet: str


class FullTokenAthInfo(BaseModel):
    ath_mc: str | None = None
    ath_token: str | None = None
    token: FullTokenAthToken


class FullTokenAthToken(BaseModel):
    address: str | None = None
    avatar: str | None = None
    name: str | None = None
    symbol: str | None = None


class FullTokenCreatorStat(BaseModel):
    amount: str
    follow_count: int
    from_address: str
    fund_from: str
    fund_tx_hash: str
    inner_token_count: int
    nickname: str
    open_token_count: int
    remark_count: int
    transfer_ts: int
    twitter_username: str
    wallet_create_at: int


class FullTokenInfo(BaseModel):
    address: str
    ath_info: FullTokenAthInfo
    ath_market_cap: str
    ath_price: float
    ath_ts: int
    banner: str
    biggest_pool_address: str
    bluechip_owner_count: int
    bluechip_owner_percentage: str
    bot_degen_count: int
    bot_degen_rate: str
    callout_declaration: bool
    chain: str
    creation_timestamp: int
    creation_tool: str | None = None
    creator_address: str
    creator_created_count: int
    creator_hold_rate: str
    creator_open_count: int | None = None
    creator_stat: FullTokenCreatorStat | None = None
    creator_token_balance: str
    creator_token_status: str
    cto_flag: int
    decimals: int
    dev_team_hold_rate: str
    dexscr_boost_fee: int | None = None
    dexscr_update_link: int
    dexscr_update_link_ts: int
    fresh_wallet_rate: str
    holder_count: int
    image_dup_count: int | None = None
    is_hidden: bool
    launch_quote_address: str
    launchpad: str
    launchpad_platform: str
    launchpad_progress: int
    launchpad_status: int
    link: FullTokenLinks
    liquidity: float
    live_preview: FullTokenLivePreview | None = None
    locked_ratio: int
    logo: str
    migrated_pool: str
    migrated_pool_exchange: str
    migrated_timestamp: int
    migration_market_cap: float
    migration_market_cap_quote: str
    name: str
    og: bool | None = None
    open_timestamp: int | None = None
    priority_fee: str
    private_vault_hold_rate: str
    rug: FullTokenRug
    rug_ratio: str
    security: FullTokenSecurity
    standard: str
    symbol: str
    tcid: str | None = None
    tip_fee: str
    top70_sniper_hold_rate: str
    top_10_holder_rate: str
    top_bot_degen_percentage: str
    top_bundler_trader_percentage: str
    top_entrapment_trader_percentage: str
    top_rat_trader_percentage: str
    total_fee: str
    total_supply: int
    tpool: Tpool
    trade_fee: str
    trade_stat: FullTokenTradeStat
    trans_name: str
    trans_name_zhcn: str
    trans_symbol: str
    trans_symbol_zhcn: str
    twitter_create_token_count: int | None = None
    twitter_created_count: int | None = None
    twitter_del_post_count: int | None = None
    twitter_del_post_token_count: int | None = None
    twitter_rename_count: int | None = None
    visiting_count: int | None = None


class FullTokenLinks(BaseModel):
    geckoterminal: str
    gmgn: str
    telegram: str | None = None
    twitter_username: str
    website: str


class FullTokenLivePreview(BaseModel):
    detail_url_pump: str
    end_live_timestamp: int
    is_token_live: bool
    reply_count: int
    start_live_timestamp: int
    thumbnail: str


class FullTokenRug(BaseModel):
    rug_ratio: str


class FullTokenSecurity(BaseModel):
    average_tax: str
    burn_ratio: str
    burn_status: str
    buy_tax: str
    can_not_sell: int
    can_sell: int
    dev_token_burn_amount: str
    dev_token_burn_ratio: str
    flags: list[str]
    hide_risk: bool
    high_tax: str
    is_blacklist: bool | None
    is_honeypot: bool | None
    is_open_source: bool | None
    is_renounced: bool | None
    is_show_alert: bool
    lock_info: Any
    lock_summary: TokenFeeLockSummary
    privileges: list[str]
    renounced_freeze_account: bool
    renounced_mint: bool
    sell_tax: str
    top_10_holder_rate: str
    total_buy_tax: str
    total_sell_tax: str


class FullTokenTradeStat(BaseModel):
    bundler_wallets: int
    creator_wallets: int
    following_wallets: int
    fresh_wallets: int
    rat_trader_wallets: int
    renowned_wallets: int
    smart_wallets: int
    sniper_wallets: int
    top_wallets: int
    updated_at: int
    whale_wallets: int


class GasPrice(BaseModel):
    auto: str
    auto_mev: str
    average: str
    average_estimate_time: int
    average_orign: str
    average_prio_fee: str
    average_prio_fee_mixed: str
    base_fee: str | None = None
    block_number: int | None = None
    block_timestamp: int | None = None
    chain: str
    eth_usd_price: float
    high: str
    high_estimate_time: int
    high_orign: str
    high_prio_fee: str
    high_prio_fee_mixed: str
    last_block: int
    low: str
    low_estimate_time: int
    low_orign: str
    low_prio_fee: str
    low_prio_fee_mixed: str
    native_token_usd_price: float
    prio: str
    prio_mev: str
    suggest_base_fee: str
    tip: str
    tip_mev: str


class GetActivityRankInfoData(BaseModel):
    activity_begin: int
    activity_end: int
    list_: Annotated[list[Any], Field(alias="list")]


class GetActivityRankInfoResponse(BaseModel):
    code: int
    data: GetActivityRankInfoData
    message: str
    reason: str


class GetAggedTokenTradesData(BaseModel):
    trades: list[AggedTradeBucket]


class GetAggedTokenTradesResponse(BaseModel):
    code: int
    data: GetAggedTokenTradesData
    message: str
    reason: str


class GetAggedTokenTransfersData(BaseModel):
    transfers: list[AggedTransferBucket]


class GetAggedTokenTransfersResponse(BaseModel):
    code: int
    data: GetAggedTokenTransfersData
    message: str
    reason: str


class GetBluechipRankResponse(BaseModel):
    code: int
    data: list[BluechipToken]
    message: str
    reason: str


class GetDevCreatedTokensData(BaseModel):
    creator_ath_info: DevCreatorAthInfo
    inner_count: int
    last_create_timestamp: int
    open_count: int
    open_ratio: str
    tokens: list[DevCreatedToken]


class GetDevCreatedTokensResponse(BaseModel):
    code: int
    data: GetDevCreatedTokensData
    message: str
    reason: str


class GetDexTradesPollingData(BaseModel):
    allAggregationResult: DexAggregationResult
    source: str
    topLaunchpads: list[DexAggregationResult]
    topProtocols: list[DexAggregationResult]


class GetDexTradesPollingResponse(BaseModel):
    code: int
    data: GetDexTradesPollingData
    message: str
    reason: str


class GetGasPriceListData(BaseModel):
    gas_prices: list[GasPrice]


class GetGasPriceListResponse(BaseModel):
    code: int
    data: GetGasPriceListData
    message: str
    reason: str


class GetHotSearchesResponse(BaseModel):
    code: int
    data: list[TrendingChainBucket]
    message: str


class GetLaunchpadTaxPolicyData(BaseModel):
    platforms: dict[str, LaunchpadTaxPlatform]
    revision: str
    tipsConfigs: LaunchpadTaxTipsConfigs


class GetLaunchpadTaxPolicyResponse(BaseModel):
    code: int
    data: GetLaunchpadTaxPolicyData
    message: str
    reason: str


class GetLiveTokenPreviewData(BaseModel):
    address: str
    create_timestamp: int
    creator: str
    description: str
    detail_url_gmgn: str
    detail_url_pump: str
    end_live_timestamp: int | None
    is_token_live: bool
    logo: str
    mc: str
    name: str
    price_24_change: str
    reply_count: int
    start_live_timestamp: int
    symbol: str
    telegram: str
    thumbnail: str
    twitter: str
    website: str


class GetLiveTokenPreviewResponse(BaseModel):
    code: int
    data: GetLiveTokenPreviewData
    message: str
    reason: str


class GetLiveTwitchKolData(BaseModel):
    base: dict[str, TwitchKolChannel]
    bsc: dict[str, TwitchKolChannel]
    sol: dict[str, TwitchKolChannel]


class GetLiveTwitchKolResponse(BaseModel):
    code: int
    data: GetLiveTwitchKolData
    message: str
    reason: str


class GetMajorCoinPricesData(BaseModel):
    prices: list[MajorCoinPrice]


class GetMajorCoinPricesResponse(BaseModel):
    code: int
    data: GetMajorCoinPricesData
    message: str
    reason: str


class GetMultiTokenFullInfoResponse(BaseModel):
    code: int
    data: list[FullTokenInfo]
    message: str
    reason: str


class GetMultiTokenInfoResponse(BaseModel):
    code: int
    data: list[MultiTokenInfo]
    message: str
    reason: str


class GetMultiWindowTokenInfoResponse(BaseModel):
    code: int
    data: list[MultiWindowTokenInfo]
    message: str
    reason: str


class GetNativeTransferData(BaseModel):
    address: str
    amount: str
    from_address: str
    fund_tx_hash: str
    nickname: str
    transfer_ts: int
    twitter_username: str


class GetNativeTransferResponse(BaseModel):
    code: int
    data: GetNativeTransferData
    message: str
    reason: str


class GetNewPairsData(BaseModel):
    pairs: list[NewPair]


class GetNewPairsResponse(BaseModel):
    code: int
    data: GetNewPairsData
    message: str
    reason: str


class GetRecommendSlippageData(BaseModel):
    display_slippage: str
    has_tax: bool
    recommend_sell_slippage: str
    recommend_slippage: str
    volatility: int


class GetRecommendSlippageResponse(BaseModel):
    code: int
    data: GetRecommendSlippageData
    message: str
    reason: str


class GetSimilarCoinExtremesData(BaseModel):
    earliest: SimilarCoinExtreme | None
    max_mcp: SimilarCoinExtreme | None


class GetSimilarCoinExtremesResponse(BaseModel):
    code: int
    data: GetSimilarCoinExtremesData
    message: str
    reason: str


class GetSimilarCoinsResponse(BaseModel):
    code: int
    data: list[SimilarCoin]
    message: str
    reason: str


class GetSmartMoneyWalletData(BaseModel):
    all_pnl: float
    avatar: str | None
    avg_holding_peroid: Any
    balance: str
    bnb_balance: str
    buy: int
    buy_1d: int
    buy_30d: int
    buy_7d: int
    ens: Any = None
    eth_balance: str
    followers_count: int
    history_bought_cost: Any
    is_contract: bool
    last_active_timestamp: int
    name: str | None
    pnl: float
    pnl_1d: int
    pnl_2x_5x_num: Any
    pnl_30d: float
    pnl_7d: float
    pnl_gt_5x_num: Any
    pnl_lt_2x_num: Any
    pnl_lt_minus_dot5_num: Any
    pnl_minus_dot5_0x_num: Any
    profit_num: Any
    realized_profit: float
    realized_profit_1d: int
    realized_profit_30d: float
    realized_profit_7d: float
    refresh_requested_at: Any
    risk: WalletRiskProfile | None = None
    sell: int
    sell_1d: int
    sell_30d: int
    sell_7d: int
    sol_balance: str
    tag_rank: WalletTagRank
    tags: list[str]
    token_avg_cost: Any
    token_num: Any
    token_sold_avg_profit: Any
    total_profit: float
    total_profit_pnl: float
    total_value: int
    trx_balance: str
    twitter_bind: bool
    twitter_fans_num: int
    twitter_name: str | None
    twitter_username: str | None = None
    unrealized_pnl: int
    unrealized_profit: int
    updated_at: int | None
    winrate: Any


class GetSmartMoneyWalletInfoData(BaseModel):
    all_pnl: float
    avatar: str | None
    avg_holding_peroid: float | None
    balance: str
    bnb_balance: str
    buy: int
    buy_1d: int
    buy_30d: int
    buy_7d: int
    ens: str | None
    eth_balance: str
    followers_count: int
    history_bought_cost: float | None
    is_contract: bool
    last_active_timestamp: int
    name: str | None
    pnl: float
    pnl_1d: float
    pnl_2x_5x_num: int | None
    pnl_30d: float
    pnl_7d: float
    pnl_gt_5x_num: int | None
    pnl_lt_2x_num: int | None
    pnl_lt_minus_dot5_num: int | None
    pnl_minus_dot5_0x_num: int | None
    profit_num: int | None
    realized_profit: float
    realized_profit_1d: float
    realized_profit_30d: float
    realized_profit_7d: float
    refresh_requested_at: int | None
    risk: SmartMoneyRisk
    sell: int
    sell_1d: int
    sell_30d: int
    sell_7d: int
    sol_balance: str
    tag_rank: dict[str, int | None]
    tags: list[str]
    token_avg_cost: float | None
    token_num: int | None
    token_sold_avg_profit: float | None
    total_profit: float
    total_profit_pnl: float
    total_value: float
    trx_balance: str
    twitter_bind: bool
    twitter_fans_num: int
    twitter_name: str | None
    twitter_username: str | None
    unrealized_pnl: float
    unrealized_profit: float
    updated_at: int
    winrate: float | None


class GetSmartMoneyWalletInfoResponse(BaseModel):
    code: int
    data: GetSmartMoneyWalletInfoData
    msg: str


class GetSmartMoneyWalletResponse(BaseModel):
    code: int
    data: GetSmartMoneyWalletData
    msg: str


class GetSwapRankingsData(BaseModel):
    rank: list[SwapRankToken]


class GetSwapRankingsResponse(BaseModel):
    code: int
    data: GetSwapRankingsData
    message: str
    reason: str


class GetTokenAiNarrativeData(BaseModel):
    en: str
    source: int
    zh_cn: str
    zh_tw: str


class GetTokenAiNarrativeResponse(BaseModel):
    code: int
    data: GetTokenAiNarrativeData
    message: str
    reason: str


class GetTokenBundlerStatData(BaseModel):
    bundler_count: int
    bundler_hold_ratio: str
    bundler_max_hold_ratio: str
    bundler_swap_quote_amount: str
    bundler_swap_ratio: str
    bundler_swaps: int


class GetTokenBundlerStatResponse(BaseModel):
    code: int
    data: GetTokenBundlerStatData
    message: str
    reason: str


class GetTokenCandlesData(BaseModel):
    field_debug_tpool: Annotated[Tpool | None, Field(alias="_debug_tpool")]
    field_debug_tpool_desc: Annotated[str, Field(alias="_debug_tpool_desc")]
    list_: Annotated[list[McapCandle], Field(alias="list")]


class GetTokenCandlesResponse(BaseModel):
    code: int
    data: GetTokenCandlesData
    message: str
    reason: str


class GetTokenCommunityMessagesData(BaseModel):
    chain: str
    community: TokenCommunity
    declaration_level: str
    has_more: bool
    messages: list[TokenCommunityMessage]
    top_message: TokenCommunityMessage | None = None


class GetTokenCommunityMessagesResponse(BaseModel):
    code: int
    data: GetTokenCommunityMessagesData
    message: str
    reason: str


class GetTokenDevInfoData(BaseModel):
    address: str
    creator_address: str
    creator_open_count: int
    creator_token_balance: str
    creator_token_status: str
    cto_flag: int
    dexscr_ad: int
    dexscr_ad_ts: int
    dexscr_boost_fee: int
    dexscr_boost_ts: int
    dexscr_trending_bar: int
    dexscr_trending_bar_ts: int
    dexscr_update_link: int
    dexscr_update_link_ts: int
    fund_from: str
    fund_from_ts: int
    offchain: bool
    top_10_holder_rate: str
    twitter_change_flag: bool
    twitter_create_token_count: int
    twitter_created_count: int
    twitter_del_post_count: int
    twitter_del_post_token_count: int
    twitter_name_change_history: list[Any]
    twitter_rename_count: int


class GetTokenDevInfoResponse(BaseModel):
    code: int
    data: GetTokenDevInfoData
    message: str
    reason: str


class GetTokenFeeDistributionData(BaseModel):
    launchpad: str
    platform_data: FeeDistributionPlatform | None


class GetTokenFeeDistributionResponse(BaseModel):
    code: int
    data: GetTokenFeeDistributionData
    message: str
    reason: str


class GetTokenFeeInfoData(BaseModel):
    address: str
    launchpad: TokenLaunchpad
    pool_fee_info_list: list[TokenFeePool]
    security: TokenFeeSecurity


class GetTokenFeeInfoResponse(BaseModel):
    code: int
    data: GetTokenFeeInfoData
    message: str
    reason: str


class GetTokenHolderExtraInfoData(BaseModel):
    list_: Annotated[list[HolderExtraInfo], Field(alias="list")]


class GetTokenHolderExtraInfoResponse(BaseModel):
    code: int
    data: GetTokenHolderExtraInfoData
    message: str
    reason: str


class GetTokenHolderStatResponse(BaseModel):
    code: int
    data: TagCounts
    message: str
    reason: str


class GetTokenHoldersData(BaseModel):
    list_: Annotated[list[TokenHolder], Field(alias="list")]
    next: str


class GetTokenHoldersResponse(BaseModel):
    code: int
    data: GetTokenHoldersData
    message: str
    reason: str


class GetTokenInfoBriefData(BaseModel):
    tokens: list[TokenBrief]


class GetTokenInfoBriefResponse(BaseModel):
    code: int
    data: GetTokenInfoBriefData
    message: str
    reason: str


class GetTokenLiquidityData(BaseModel):
    history: list[LiquidityHistory]
    next: str


class GetTokenLiquidityResponse(BaseModel):
    code: int
    data: GetTokenLiquidityData
    message: str
    reason: str


class GetTokenLiquidityStatsData(BaseModel):
    bundler_wallets: int
    chain: str
    creator_wallets: int
    following_wallets: int
    fresh_wallets: int
    rat_trader_wallets: int
    renowned_wallets: int
    smart_wallets: int
    sniper_wallets: int
    token_address: str
    top_wallets: int
    whale_wallets: int


class GetTokenLiquidityStatsResponse(BaseModel):
    code: int
    data: GetTokenLiquidityStatsData
    message: str
    reason: str


class GetTokenLiquidityTrendData(BaseModel):
    pool_size: str
    pools: str


class GetTokenLiquidityTrendResponse(BaseModel):
    code: int
    data: GetTokenLiquidityTrendData
    message: str
    reason: str


class GetTokenLogoHistoryResponse(BaseModel):
    code: int
    data: list[TokenLogoHistoryEntry]
    message: str
    reason: str


class GetTokenMcapCandlesData(BaseModel):
    field_debug_tpool: Annotated[Any, Field(alias="_debug_tpool")]
    list_: Annotated[list[McapCandle], Field(alias="list")]


class GetTokenMcapCandlesResponse(BaseModel):
    code: int
    data: GetTokenMcapCandlesData
    message: str
    reason: str


class GetTokenPoolFeeInfoData(BaseModel):
    list_: Annotated[list[PoolFeeInfo], Field(alias="list")]


class GetTokenPoolFeeInfoResponse(BaseModel):
    code: int
    data: GetTokenPoolFeeInfoData
    message: str
    reason: str


class GetTokenPricesData(BaseModel):
    list_: Annotated[list[TokenPrice], Field(alias="list")]


class GetTokenPricesResponse(BaseModel):
    code: int
    data: GetTokenPricesData
    message: str
    reason: str


class GetTokenSecurityData(BaseModel):
    address: str
    launchpad: TokenLaunchpad
    security: TokenSecurity


class GetTokenSecurityResponse(BaseModel):
    code: int
    data: GetTokenSecurityData
    message: str
    reason: str


class GetTokenSignalsResponse(BaseModel):
    code: int
    data: list[TokenSignal]
    message: str
    reason: str


class GetTokenSocialsData(BaseModel):
    address: str
    link: TokenSocialLink
    rug: TokenRug
    vote: TokenVote


class GetTokenSocialsResponse(BaseModel):
    code: int
    data: GetTokenSocialsData
    message: str
    reason: str


class GetTokenStatsData(BaseModel):
    bluechip_owner_count: int
    bluechip_owner_percentage: str
    bot_degen_count: int
    bot_degen_rate: str
    creator_created_count: int
    creator_hold_rate: str
    creator_token_balance: str
    degen_call_count: int
    dev_team_hold_rate: str
    fresh_wallet_rate: str
    holder_count: int
    private_vault_hold_rate: str
    signal_count: int
    top70_sniper_hold_rate: str
    top_10_holder_rate: str
    top_bot_degen_percentage: str
    top_bundler_trader_percentage: str
    top_entrapment_trader_percentage: str
    top_rat_trader_percentage: str


class GetTokenStatsResponse(BaseModel):
    code: int
    data: GetTokenStatsData
    message: str
    reason: str


class GetTokenTraderStatResponse(BaseModel):
    code: int
    data: TagCounts
    message: str
    reason: str


class GetTokenTradersData(BaseModel):
    list_: Annotated[list[TokenHolder], Field(alias="list")]
    next: str


class GetTokenTradersResponse(BaseModel):
    code: int
    data: GetTokenTradersData
    message: str
    reason: str


class GetTokenTradesData(BaseModel):
    history: list[TradeHistory]
    next: str


class GetTokenTradesResponse(BaseModel):
    code: int
    data: GetTokenTradesData
    message: str
    reason: str


class GetTokenTradesV2Data(BaseModel):
    history: list[TradeHistory]
    next: str


class GetTokenTradesV2Response(BaseModel):
    code: int
    data: GetTokenTradesV2Data
    message: str
    reason: str


class GetTokenTrendsData(BaseModel):
    trends: TokenTrendSeries


class GetTokenTrendsResponse(BaseModel):
    code: int
    data: GetTokenTrendsData
    message: str
    reason: str


class GetTokenWalletTagsStatData(BaseModel):
    bundler_wallets: int
    chain: str
    creator_wallets: int
    following_wallets: int
    fresh_wallets: int
    rat_trader_wallets: int
    renowned_wallets: int
    smart_wallets: int
    sniper_wallets: int
    token_address: str
    top_wallets: int
    whale_wallets: int


class GetTokenWalletTagsStatResponse(BaseModel):
    code: int
    data: GetTokenWalletTagsStatData
    message: str
    reason: str


class GetTopBuyersData(BaseModel):
    holders: TopBuyerHolders


class GetTopBuyersResponse(BaseModel):
    code: int
    data: GetTopBuyersData
    msg: str


class GetTopCallersData(BaseModel):
    current_user: TopCaller | None
    list_: Annotated[list[TopCaller], Field(alias="list")]


class GetTopCallersResponse(BaseModel):
    code: int
    data: GetTopCallersData
    message: str
    reason: str


class GetTrendingTokensResponse(BaseModel):
    code: int
    data: list[TrendingChainBucket]
    message: str


class GetWalletActivityData(BaseModel):
    activities: list[WalletActivityEvent]
    next: str


class GetWalletActivityResponse(BaseModel):
    code: int
    data: GetWalletActivityData
    message: str
    reason: str


class GetWalletChainBalancesResponse(BaseModel):
    code: int
    data: list[WalletChainBalance]
    message: str
    reason: str


class GetWalletCommonStatData(BaseModel):
    avatar: str
    bind_status: str
    created_at: int
    created_token_count: int
    ens: str
    follow_count: int
    followers_count: int
    fund_amount: str
    fund_from: str
    fund_from_address: str
    fund_from_ts: int
    fund_tx_hash: str
    is_blue_verified: bool
    name: str
    nick_name: str
    remark_count: int
    tag: str
    tag_rank: WalletTagRank
    tags: list[str]
    twitter_bind: bool
    twitter_description: str
    twitter_fans_num: int
    twitter_id: str
    twitter_name: str
    twitter_username: str
    verified: bool
    wallet_address: str


class GetWalletCommonStatResponse(BaseModel):
    code: int
    data: GetWalletCommonStatData
    message: str
    reason: str


class GetWalletRankingsData(BaseModel):
    rank: list[RankedWallet]


class GetWalletRankingsResponse(BaseModel):
    code: int
    data: GetWalletRankingsData
    message: str
    reason: str


class GetWalletStatData(BaseModel):
    bought_cost: str
    buy: int
    last_timestamp: int
    native_balance: str
    pnl_stat: WalletPnlStat
    realized_profit: str
    realized_profit_pnl: str
    sell: int
    sold_fee: str
    sold_income: str
    total_cost: str
    wallet_address: str


class GetWalletStatResponse(BaseModel):
    code: int
    data: GetWalletStatData
    message: str
    reason: str


class GetWebsiteInfoData(BaseModel):
    address: str
    created_at: int
    ip: str
    website: str


class GetWebsiteInfoResponse(BaseModel):
    code: int
    data: GetWebsiteInfoData
    message: str
    reason: str


class GmgnSearchCoin(BaseModel):
    address: str
    ath_market_cap: str
    buy_tax: str
    chain: str
    created_at: int
    creation_tool: str
    creator: str
    cto_flag: int
    dexscr_ad: int
    dexscr_boost_fee: int
    dexscr_trending_bar_ts: int
    dexscr_update_link: int
    exchange: str
    follow_state: bool
    holder_count: int
    hot_level: int
    is_honeypot: bool | None
    is_og: bool
    is_show_alert: bool
    kol_count: int
    launch_quote_address: str
    launchpad: str
    launchpad_platform: str
    launchpad_status: int
    liquidity: str
    logo: str
    mcp: str
    migrated_pool_exchange: str
    name: str
    offchain: bool
    price: str
    price_24h: str
    progress: float
    quote_address: str
    remark_name: str
    renounced_freeze_account: bool | None
    sell_tax: str
    standard: str
    swaps_1h: int
    swaps_24h: int
    swaps_5m: int
    swaps_6h: int
    symbol: str
    tax_allocation: dict[str, Any] | None = None
    token_link: GmgnSearchTokenLink
    total_buy_tax: float
    total_fee: str
    total_sell_tax: float
    trans_name: str
    trans_name_zhcn: str
    trans_symbol: str
    trans_symbol_zhcn: str
    twitter_change_flag: int
    twitter_rename_count: int
    visiting_count: int
    volume_1h: float
    volume_24h: float


class GmgnSearchTokenLink(BaseModel):
    address: str
    bitbucket: str
    description: str
    discord: str
    facebook: str
    fracaster: Any
    geckoterminal: str
    github: str
    gmgn: str
    instagram: str
    linkedin: str
    medium: str
    reddit: str
    telegram: str
    tiktok: str
    twitter_username: str
    verify_status: int
    website: str
    youtube: str


class GmgnSearchWallet(BaseModel):
    address: str
    avatar: str
    balance: str
    chain: str
    ens: str
    follow_count: int
    follow_state: bool
    fund_from: str
    fund_from_ts: int
    last_active_time: int
    pnl_7d: str
    realized_profit_7d: str
    remark_count: int
    remark_name: str
    twitter_fans_num: int
    twitter_name: str
    twitter_username: str
    wallet_tags: list[str]
    win_rate_7d: float


class HolderExtraInfo(BaseModel):
    addr_type: int
    address: str
    avatar: str | None
    created_at: int
    exchange: str
    is_new: bool
    is_on_curve: bool
    maker_token_tags: list[str] | None
    name: str | None
    native_balance: str
    native_transfer: HolderNativeTransfer | None
    tags: list[str] | None
    token_transfer_in: HolderExtraTokenTransfer | None
    token_transfer_out: HolderTokenTransfer | None
    transfer_in: bool
    twitter_name: str | None
    twitter_username: str | None


class HolderExtraTokenTransfer(BaseModel):
    address: str
    name: str | None
    timestamp: int
    tx_hash: str
    type: str


class HolderNativeTransfer(BaseModel):
    amount: str
    from_address: str
    name: str | None
    timestamp: int
    tx_hash: str


class HolderStatParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class HolderTokenTransfer(BaseModel):
    address: str
    name: str | None
    timestamp: int
    tx_hash: str
    type: str


class HoldersParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    cost: Annotated[int | None, Field(ge=1, le=1000)] = 20
    cursor: str | None = None
    direction: SortDirection | None = SortDirection.DESC
    limit: Annotated[int | None, Field(ge=1, le=1000)] = 100
    order_by: HolderOrderBy | None = HolderOrderBy.AMOUNT_PERCENTAGE
    tag: HolderTag | None = None
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class LaunchpadTaxPlatform(BaseModel):
    launchpad_platform_tax_policy: str


class LaunchpadTaxPolicyParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]


class LaunchpadTaxTip(BaseModel):
    en: str
    zhCN: str
    zhTW: str


class LaunchpadTaxTipsConfigs(BaseModel):
    icons: list[Any]
    tips: list[LaunchpadTaxTip]


class LiquidityHistory(BaseModel):
    amount_usd: str
    balance: str
    base_amount: str
    contract_address: str
    event: str
    history_base: str
    history_bought_amount: str
    history_quote: str
    history_sold_amount: str
    history_sold_income: str
    id: str
    is_open_or_close: int
    is_single: bool
    maker: str
    maker_avatar: str
    maker_ens: str
    maker_name: str
    maker_tags: list[str]
    maker_token_tags: list[str]
    maker_twitter_name: str
    maker_twitter_username: str
    max_price: str
    min_price: str
    price_usd: str
    quote_address: str
    quote_amount: str
    quote_symbol: str
    realized_profit: str
    timestamp: int
    token_address: str
    total_trade: int
    tx_hash: str
    unrealized_profit: str


class LiquidityParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    cursor: str | None = None
    limit: Annotated[int | None, Field(ge=1, le=1000)] = 100
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class LivePreviewParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class LockSummary(BaseModel):
    is_locked: bool
    left_lock_percent: str
    lock_detail: Any
    lock_percent: str
    lock_tags: list[str] | None


class MajorCoinPrice(BaseModel):
    price: str
    symbol: str


class McapCandle(BaseModel):
    amount: str
    close: str
    high: str
    low: str
    open: str
    source: str
    time: int
    volume: str


class McapCandlesParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    limit: Annotated[int | None, Field(ge=1, le=1000)] = 501
    resolution: Resolution | None = Resolution.FIELD_1D
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class MultiTokenFullInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]


class MultiTokenInfo(BaseModel):
    address: str
    ath_price: float
    biggest_pool_address: str
    chain: str
    creation_timestamp: int
    creator_address: str
    decimals: int
    holder_count: int
    is_hidden: bool | None = None
    launchpad: str
    launchpad_platform: str
    launchpad_progress: float
    launchpad_status: int
    liquidity: float
    locked_ratio: float
    logo: str
    migrated_pool: str
    migrated_timestamp: int
    migration_market_cap: float
    migration_market_cap_quote: str
    name: str
    route_info_init: dict[str, RouteInfoInitMember] | None = None
    standard: str
    symbol: str
    total_supply: int
    tpool: Tpool
    trans_name: str
    trans_name_zhcn: str
    trans_symbol: str
    trans_symbol_zhcn: str


class MultiTokenInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]


class MultiWindowTokenDev(BaseModel):
    address: str
    creator_address: str
    creator_open_count: int
    creator_token_balance: str
    creator_token_status: str
    cto_flag: int
    dexscr_ad: int
    dexscr_ad_ts: int
    dexscr_boost_fee: int
    dexscr_boost_ts: int
    dexscr_trending_bar: int
    dexscr_trending_bar_ts: int
    dexscr_update_link: int
    dexscr_update_link_ts: int
    fund_from: str
    fund_from_ts: int
    offchain: bool
    top_10_holder_rate: str
    twitter_change_flag: bool
    twitter_create_token_count: int
    twitter_created_count: int
    twitter_del_post_count: int
    twitter_del_post_token_count: int
    twitter_name_change_history: list[Any]
    twitter_rename_count: int


class MultiWindowTokenInfo(BaseModel):
    address: str
    banner: str
    biggest_pool_address: str
    callout_declaration: bool | None = None
    circulating_supply: str
    creation_timestamp: int
    creation_tool: str
    decimals: int
    dev: MultiWindowTokenDev
    holder_count: int
    image_dup_count: int
    is_hidden: bool | None = None
    liquidity: str
    logo: str
    max_supply: str
    migrated_timestamp: int
    name: str
    offchain: bool
    og: bool
    open_timestamp: int
    pool: MultiWindowTokenPool
    price: MultiWindowTokenPrice
    priority_fee: str
    standard: str
    symbol: str
    tcid: str
    tip_fee: str
    total_fee: str
    total_supply: str
    tpool: Tpool
    trade_fee: str
    trans_name: str
    trans_name_zhcn: str
    trans_symbol: str
    trans_symbol_zhcn: str
    visiting_count: int


class MultiWindowTokenInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]


class MultiWindowTokenPool(BaseModel):
    address: str
    base_address: str
    base_reserve: str
    base_reserve_value: str
    base_symbol: str | None = None
    base_vault_address: str
    creation_timestamp: int
    creator: str
    exchange: str
    factory: str | None = None
    fee_ratio: str
    initial_base_reserve: str
    initial_liquidity: str
    initial_quote_reserve: str
    liquidity: str
    pool_address: str
    quote_address: str
    quote_reserve: str
    quote_reserve_value: str
    quote_symbol: str
    quote_vault_address: str
    token0_address: str
    token1_address: str


class MultiWindowTokenPrice(BaseModel):
    address: str
    buy_volume_1h: str
    buy_volume_1m: str
    buy_volume_24h: str
    buy_volume_5m: str
    buy_volume_6h: str
    buys_1h: int
    buys_1m: int
    buys_24h: int
    buys_5m: int
    buys_6h: int
    hot_level: int
    price: str
    price_1h: str
    price_1m: str
    price_24h: str
    price_5m: str
    price_6h: str
    sell_volume_1h: str
    sell_volume_1m: str
    sell_volume_24h: str
    sell_volume_5m: str
    sell_volume_6h: str
    sells_1h: int
    sells_1m: int
    sells_24h: int
    sells_5m: int
    sells_6h: int
    swaps_1h: int
    swaps_1m: int
    swaps_24h: int
    swaps_5m: int
    swaps_6h: int
    volume_1h: str
    volume_1m: str
    volume_24h: str
    volume_5m: str
    volume_6h: str


class NativeTransferParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    wallet_address: Annotated[str, Field(examples=["suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"])]


class NewPair(BaseModel):
    address: str
    base_address: str
    base_token_info: NewPairBaseToken
    bot_degen_count: int | None = None
    bot_degen_rate: float | None = None
    chain: str
    dev_team_hold_rate: float | None = None
    dexscr_ad_ts: int | None = None
    dexscr_boost_fee: int | None = None
    dexscr_boost_ts: int | None = None
    dexscr_update_link_ts: int | None = None
    exchange: str
    history_highest_market_cap: float | None = None
    image_dup: str
    initial_liquidity: str
    initial_quote_reserve: str
    launch_quote_address: str | None = None
    launchpad: str | None = None
    launchpad_platform: str | None = None
    migrated_pool_exchange: str | None = None
    open_timestamp: int
    quote_address: str
    quote_reserve: str | None = None
    quote_reserve_usd: str | None = None
    quote_symbol: str
    seq_index: str
    telegram_dup: int | None = None
    top70_sniper_hold_rate: float | None = None
    total_fee: float | None = None
    twitter_dup: int | None = None
    visiting_count: int | None = None
    website_dup: int | None = None


class NewPairBaseToken(BaseModel):
    address: str
    bundler_rate: float | None = None
    bundler_trader_amount_rate: str | None = None
    burn_ratio: str | None = None
    burn_status: str
    buy_tax: str | None = None
    buy_volume_1h: str
    buy_volume_1m: str
    buy_volume_24h: str
    buy_volume_5m: str
    buy_volume_6h: str
    buys: int | None = None
    creation_timestamp: int
    creator: str
    creator_balance_rate: str | None = None
    creator_created_inner_count: int | None = None
    creator_created_open_ratio: float | None = None
    creator_token_status: str | None = None
    cto_flag: int
    dev_token_burn_ratio: float | None = None
    dexscr_ad: int
    dexscr_update_link: int
    entrapment_ratio: str | None = None
    fund_from_address: str | None = None
    holder_count: int | None = None
    hot_level: int | None = None
    insider_ratio: float | None = None
    is_honeypot: str
    is_og: bool | None = None
    is_token_live: bool | None = None
    launchpad_status: int
    liquidity: str
    logo: str
    market_cap: str
    name: str
    price: str
    price_1h: str
    price_1m: str
    price_24h: str
    price_5m: str
    price_6h: str
    price_change_percent1h: str
    price_change_percent1m: str
    price_change_percent5m: str
    progress: float
    rat_trader_amount_rate: float | None = None
    renounced: int
    renounced_freeze_account: int
    renounced_mint: int
    renowned_count: int | None = None
    rug_ratio: float | None = None
    sell_tax: str | None = None
    sell_volume_1h: str
    sell_volume_1m: str
    sell_volume_24h: str
    sell_volume_5m: str
    sell_volume_6h: str
    sells: int | None = None
    smart_degen_count: int | None = None
    sniper_count: int | None = None
    social_links: NewPairSocialLinks
    standard: str | None = None
    swaps: int | None = None
    symbol: str
    top_10_holder_rate: float | None = None
    total_supply: int
    twitter_change_flag: int
    twitter_create_token_count: int | None = None
    twitter_del_post_token_count: int | None = None
    twitter_rename_count: int | None = None
    volume: str


class NewPairSocialLinks(BaseModel):
    telegram: str | None = None
    twitter_username: str | None = None
    website: str | None = None


class NewPairsParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    filters: list[TokenFilter] | None = None
    """
    Security screens applied before sorting.
    """
    interval: TrendingInterval | None = TrendingInterval.FIELD_1H
    """
    Age window — only pairs opened inside it are returned.
    """
    launchpad_platforms: list[str] | None = None
    """
    Restrict to these launchpads, e.g. `Pump.fun`, `letsbonk`, `fourmeme`.
    """
    limit: Annotated[int | None, Field(ge=1, le=500)] = 100
    """
    Maximum pairs to return.
    """
    order_by: NewPairsOrderBy | None = NewPairsOrderBy.OPEN_TIMESTAMP
    """
    Column to sort on.
    """


class PoolFeeInfo(BaseModel):
    address: str
    exchange: str
    fee_params: Any
    fee_ratio: float
    is_dynamic_fee: bool
    liquidity: float
    meteora_damm_v2_base_fee_config: Any
    meteora_virtual_curve_fee_config: Any
    pool_type: str


class PoolFeeInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class RankedWallet(BaseModel):
    address: str
    arc_balance: str
    avatar: str
    avg_cost_1d: str
    avg_cost_30d: str
    avg_cost_7d: str
    avg_holding_period_1d: float
    avg_holding_period_30d: float
    avg_holding_period_7d: float
    balance: str
    buy: int
    buy_1d: int
    buy_30d: int
    buy_7d: int
    daily_profit_7d: list[WalletDailyProfit] | None
    eth_balance: str
    follow_count: int
    hyperevm_balance: str
    last_active: int
    monad_balance: str
    name: str
    net_inflow_1d: str
    net_inflow_30d: str
    net_inflow_7d: str
    nickname: str
    pnl_1d: str
    pnl_2x_5x_num_7d: int
    pnl_30d: str
    pnl_7d: str
    pnl_gt_5x_num_7d: int
    pnl_lt_2x_num_7d: int
    pnl_lt_minus_dot5_num_7d: int
    pnl_minus_dot5_0x_num_7d: int
    realized_profit_1d: str
    realized_profit_30d: str
    realized_profit_7d: str
    remark_count: int
    robinhood_balance: str
    sell: int
    sell_1d: int
    sell_30d: int
    sell_7d: int
    sol_balance: str
    tags: list[str]
    trx_balance: str
    twitch_channel_name: str
    twitter_description: str
    twitter_name: str
    twitter_username: str
    txs: int
    txs_1d: int
    txs_30d: int
    txs_7d: int
    volume_1d: str
    volume_30d: str
    volume_7d: str
    wallet_address: str
    winrate_1d: float
    winrate_30d: float
    winrate_7d: float
    xlayer_balance: str


class RecommendSlippageParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class RouteInfoInitMember(BaseModel):
    a: str | None = None
    b: str | None = None
    ma: str | None = None
    maa: str | None = None
    mb: str | None = None
    mba: str | None = None
    p: str | None = None
    p_c: Annotated[str | None, Field(alias="p:c")] = None
    p_fc: Annotated[str | None, Field(alias="p:fc")] = None
    pa_c: Annotated[str | None, Field(alias="pa:c")] = None
    pa_fc: Annotated[str | None, Field(alias="pa:fc")] = None
    rbh: str | None = None
    rs: str | None = None
    s: dict[str, str] | None = None
    sc: str | None = None


class RuggedToken(BaseModel):
    address: str
    logo: str
    name: str
    symbol: str


class SearchParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    q: str
    """
    Name, symbol, contract address or wallet address.
    """


class SearchTokensData(BaseModel):
    coins: list[GmgnSearchCoin]
    wallets: list[GmgnSearchWallet]


class SearchTokensResponse(BaseModel):
    code: int
    data: SearchTokensData
    message: str
    reason: str


class SecurityParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class SimilarCoin(BaseModel):
    address: str
    chain: str
    is_og: bool
    last_trade_time: int
    liquidity: float
    logo: str
    mcp: float
    name: str
    open_or_create_time: int
    symbol: str


class SimilarCoinExtreme(BaseModel):
    address: str
    chain: str
    is_og: bool
    last_trade_time: int
    liquidity: float
    logo: str
    mcp: float
    name: str
    open_or_create_time: int
    symbol: str


class SimilarCoinExtremesParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    name: Annotated[str, Field(examples=["Bonk"])]
    symbol: Annotated[str, Field(examples=["Bonk"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class SimilarCoinsParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    name: Annotated[str, Field(examples=["Bonk"])]
    order_by: SimilarCoinsOrderBy | None = SimilarCoinsOrderBy.MCP
    symbol: Annotated[str, Field(examples=["Bonk"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class SmartMoneyRisk(BaseModel):
    fast_tx: str
    fast_tx_ratio: float
    no_buy_hold: str
    no_buy_hold_ratio: float
    sell_pass_buy: str
    sell_pass_buy_ratio: float
    token_active: str
    token_honeypot: str
    token_honeypot_ratio: float


class SmartMoneyWalletInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    wallet_address: Annotated[str, Field(examples=["suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"])]


class SocialsParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class StatsParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class SwapRankToken(BaseModel):
    address: str
    bluechip_owner_percentage: float
    bot_degen_count: int
    bot_degen_rate: float
    bundler_rate: float
    burn_ratio: float
    burn_status: str
    buy_tax: str
    buys: int
    chain: str
    creation_timestamp: int
    creator: str
    creator_close: bool
    creator_token_status: str
    cto_flag: int
    dev_team_hold_rate: float
    dev_token_burn_amount: float
    dev_token_burn_ratio: float
    dexscr_ad: int
    dexscr_ad_ts: int
    dexscr_boost_fee: int
    dexscr_boost_ts: int
    dexscr_trending_bar: int
    dexscr_trending_bar_ts: int
    dexscr_update_link: int
    dexscr_update_link_ts: int
    end_live_timestamp: int
    entrapment_ratio: float
    exchange: str
    fund_from_address: str | None = None
    gas_fee: float
    history_highest_market_cap: int
    holder_count: int
    hot_level: int
    id: int
    image_dup: str
    initial_liquidity: float
    is_honeypot: int
    is_og: bool
    is_open_source: int
    is_renounced: int
    is_show_alert: bool
    is_token_live: bool
    is_wash_trading: bool
    launch_quote_address: str
    launchpad: str
    launchpad_platform: str
    launchpad_status: str
    liquidity: float
    lock_percent: int
    logo: str
    market_cap: float
    migrated_pool_exchange: str
    name: str
    open_timestamp: int
    pool_type: int
    pool_type_str: str
    price: float
    price_change_percent: float
    price_change_percent1h: float
    price_change_percent1m: float
    price_change_percent5m: float
    rank: int
    rat_trader_amount_rate: float
    renounced_freeze_account: int
    renounced_mint: int
    renowned_count: int
    rug_ratio: float
    score: float
    sell_tax: str
    sells: int
    smart_degen_count: int
    sniper_count: int
    square_mentions: int
    start_live_timestamp: int
    swaps: int
    symbol: str
    tcid: str
    telegram: str
    telegram_dup: int
    top70_sniper_hold_rate: float
    top_10_holder_rate: float
    total_supply: int
    trans_name: str
    trans_name_zhcn: str
    trans_symbol: str
    trans_symbol_zhcn: str
    twitter_change_flag: int
    twitter_create_token_count: int
    twitter_del_post_token_count: int
    twitter_dup: int
    twitter_rename_count: int
    twitter_username: str
    visiting_count: int
    volume: float
    website: str
    website_dup: int


class SwapRankingsParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    platforms: list[str] | None = None
    """
    Restrict to these exchanges/launchpads, e.g. `pump`, `raydium`, `meteora`.
    """
    timeframe: TimeWindow | None = TimeWindow.FIELD_24H
    """
    Activity window to rank over.
    """


class SymbolListRequest(BaseModel):
    symbols: list[str]


class TagCounts(BaseModel):
    bluechip_owner_count: int
    bundler_count: int
    dev_count: int
    dex_bot_count: int
    following_count: int
    fresh_wallet_count: int
    insider_count: int
    renowned_count: int
    smart_degen_count: int
    sniper_count: int


class TokenAiNarrativeParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenBrief(BaseModel):
    address: str
    chain: str
    decimals: int
    is_honeypot: bool
    is_show_alert: bool
    launchpad: str
    launchpad_platform: str
    liqudity: str
    logo: str
    migrated_pool_exchange: str
    renounced_freeze_account: bool | None
    symbol: str
    total_supply: str | None = None


class TokenBundlerStatParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenCandlesParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    from_timestamp: Annotated[int | None, Field(ge=0)] = 0
    """
    Unix milliseconds lower bound, inclusive.
    """
    limit: Annotated[int | None, Field(ge=1, le=1000)] = 1000
    """
    Maximum candles.
    """
    resolution: Resolution | None = Resolution.FIELD_1H
    """
    Candle width.
    """
    to_timestamp: Annotated[int | None, Field(ge=0)] = None
    """
    Unix milliseconds upper bound. Defaults to now.
    """
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenCommunity(BaseModel):
    token_address: str


class TokenCommunityMessage(BaseModel):
    accu_cost: str
    accu_fee: str
    balance: str
    content: str
    created_at: str
    current_holding_usd: str
    current_pnl_usd: str
    display_content: str | None = None
    display_name: str
    follower_count: int
    id: str
    is_blue_verified: bool
    is_kol: bool
    is_safe: str
    like_count: int
    media_url: str | None
    multiplier: str
    profile_image_url: str
    reply_count: int
    source: str
    ulid: str
    user_twitter_url: str
    username: str
    wallet_address: str


class TokenCommunityMessagesParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    limit: Annotated[int | None, Field(ge=1, le=100)] = 50
    """
    Maximum messages.
    """
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenDevInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenFeeDistributionParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenFeeInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenFeeLockDetail(BaseModel):
    is_blackhole: bool
    percent: str
    pool: str


class TokenFeeLockSummary(BaseModel):
    is_locked: bool
    left_lock_percent: str
    lock_detail: list[TokenFeeLockDetail] | None
    lock_percent: str
    lock_tags: Any


class TokenFeePool(BaseModel):
    address: str
    exchange: str
    fee_params: list[str] | None
    fee_ratio: float
    is_dynamic_fee: bool
    liquidity: float
    meteora_damm_v2_base_fee_config: Any
    meteora_virtual_curve_fee_config: Any
    pool_type: str


class TokenFeeSecurity(BaseModel):
    address: str
    audit: TokenFeeSecurityAudit | None = None
    average_tax: str
    blacklist: int
    burn_ratio: str
    burn_status: str
    buy_tax: str
    can_not_sell: int
    can_sell: int
    dev_token_burn_amount: str
    dev_token_burn_ratio: str
    flags: list[str]
    hide_risk: bool
    high_tax: str
    honeypot: int
    is_blacklist: bool | None
    is_honeypot: bool | None
    is_open_source: bool | None
    is_renounced: bool | None
    is_show_alert: bool
    lockInfo: Any
    lock_summary: TokenFeeLockSummary
    open_source: int
    privileges: Any
    renounced: int | None
    renounced_freeze_account: bool | None = None
    renounced_mint: bool | None = None
    sell_tax: str
    top_10_holder_rate: str
    total_buy_tax: str
    total_sell_tax: str


class TokenFeeSecurityAudit(BaseModel):
    description: str
    description_zh: str
    security_engine: str


class TokenHolder(BaseModel):
    account_address: str
    accu_amount: float
    accu_cost: float
    addr_type: int
    address: str
    amount_cur: float
    amount_percentage: float
    avatar: str | None
    avg_cost: float | None
    avg_sold: float | None
    balance: float
    bluechip_holding_info: list[TokenHolderBluechipHolding] | None = None
    buy_amount_cur: float
    buy_tx_count_cur: int
    buy_volume_cur: float
    cost: float
    cost_cur: float
    created_at: int
    current_buy_amount: float
    current_sell_amount: float
    current_transfer_in_amount: float
    current_transfer_out_amount: float
    end_holding_at: int | None
    exchange: str
    history_bought_cost: float
    history_bought_fee: float
    history_sold_fee: float
    history_sold_income: float
    history_transfer_in_amount: float
    history_transfer_in_cost: float
    history_transfer_out_amount: float
    history_transfer_out_fee: float
    history_transfer_out_income: float
    is_new: bool
    is_on_curve: bool
    is_suspicious: bool
    last_active_timestamp: int
    last_block: int
    maker_token_tags: list[str]
    name: str | None
    native_balance: str
    native_transfer: HolderNativeTransfer | None
    netflow_amount: float
    netflow_usd: float
    profit: float
    profit_change: float | None
    realized_pnl: float | None
    realized_profit: float
    sell_amount_cur: float
    sell_amount_percentage: float
    sell_tx_count_cur: int
    sell_volume_cur: float
    start_holding_at: int | None
    tags: list[str]
    token_transfer: HolderTokenTransfer
    token_transfer_in: HolderTokenTransfer
    token_transfer_out: HolderTokenTransfer
    total_bc_value: float | None = None
    total_cost: float
    transfer_in: bool
    transfer_in_count: int
    transfer_out_count: int
    twitter_name: str | None
    twitter_username: str | None
    unrealized_pnl: float | None
    unrealized_profit: float
    usd_value: float
    wallet_tag_v2: str


class TokenHolderBluechipHolding(BaseModel):
    balance: str
    logo: str
    symbol: str
    token_address: str
    value: str


class TokenHolderExtraInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]
    wallet_addresses: Annotated[
        list[str],
        Field(examples=[["5YX6eJBcWacJFR3W99CbFoSMPbtKamBJNcjunswCcVp7"]], min_length=1),
    ]
    """
    Holders to enrich. Repeat the param for more than one.
    """


class TokenInfoBriefParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]


class TokenLaunchpad(BaseModel):
    address: str
    description: str
    launch_quote_address: str
    launchpad: str
    launchpad_platform: str
    launchpad_progress: str
    launchpad_status: int
    migrated_pool_exchange: str


class TokenLiquidityStatsParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenLiquidityTrendParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenLogoHistoryEntry(BaseModel):
    logo: str
    timestamp: int


class TokenLogoHistoryParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenPrice(BaseModel):
    address: str
    price: str


class TokenPricesParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]


class TokenRug(BaseModel):
    address: str
    holder_rugged_num: int
    holder_token_num: int
    rug_ratio: str
    rugged_tokens: list[RuggedToken] | None


class TokenSecurity(BaseModel):
    address: str
    average_tax: str
    blacklist: int
    burn_ratio: str
    burn_status: str
    buy_tax: str
    can_not_sell: int
    can_sell: int
    dev_token_burn_amount: str
    dev_token_burn_ratio: str
    flags: list[str]
    hide_risk: bool
    high_tax: str
    honeypot: int
    is_blacklist: bool | None
    is_honeypot: bool | None
    is_open_source: bool | None
    is_renounced: bool | None
    is_show_alert: bool
    lockInfo: Any
    lock_summary: LockSummary
    open_source: int
    privileges: Any
    renounced: int | None
    renounced_freeze_account: bool
    renounced_mint: bool
    sell_tax: str
    top_10_holder_rate: str
    total_buy_tax: str | None = None
    total_sell_tax: str | None = None


class TokenSignal(BaseModel):
    ath: float
    cur_data: TokenSignalCurrentStats
    data: TokenSignalTokenInfo
    first_trigger_mc: float
    id: str
    market_cap: float
    signal_times: int
    signal_times_by_type: dict[str, int]
    signal_type: int
    token_address: str
    trigger_at: int
    trigger_mc: float


class TokenSignalCurrentStats(BaseModel):
    holder_count: int
    liquidity: float
    top_10_holder_rate: float


class TokenSignalGroupRequest(BaseModel):
    launchpad_platforms: list[str] | None = None
    """
    Restrict to tokens launched on these platforms.
    """
    signal_types: Annotated[list[int], Field(min_length=1)]
    """
    GMGN signal ids to match, e.g. `1` for a surge.
    """
    total_fee_min: int | None = None
    """
    Drop tokens whose lifetime launchpad fees are below this.
    """


class TokenSignalTokenInfo(BaseModel):
    address: str
    binance_charity_tax: int
    bonus_category: Any
    bot_degen_count: int
    bot_degen_rate: float
    bundler_mhr: int
    bundler_trader_amount_rate: float
    burn_status: str
    burn_tax: int
    buy_tax: int
    buys_1h: int
    buys_1m: int
    buys_24h: int
    buys_6h: int
    callout_count: int
    callout_declaration: bool
    chain: str
    claim_avatar: str
    claim_fee_is_first: bool
    claim_fee_sol_amount: str
    claim_platform: str
    claim_platform_avatar: str
    claim_platform_username: str
    claim_twitter_user_name: str
    claim_wallet_address: str
    complete_cost_time: int
    complete_timestamp: int
    created_timestamp: int
    created_timestamp_us: int
    creation_tool: str
    creator: str
    creator_balance_rate: float
    creator_created_count: int
    creator_created_open_count: int
    creator_created_open_ratio: float
    creator_token_status: str
    cto_flag: bool
    decimals: int
    dev_tax: int
    dev_team_hold_rate: float
    dev_token_burn_amount: int
    dev_token_burn_ratio: int
    dexscr_ad: bool
    dexscr_boost_fee: int
    dexscr_trending_bar: bool
    dexscr_update_link: bool
    dividend_tax: int
    end_live_timestamp: int
    entrapment_ratio: float
    exchange: str
    fee_params: Any
    fracaster: Any
    fresh_wallet_rate: float
    fund_from: str
    fund_from_address: str
    fund_from_ts: int
    giggle_charity_tax: int
    has_at_least_one_social: bool
    holder_count: int
    image_dup: int
    instagram: str
    is_honeypot: str
    is_og: bool
    is_token_live: bool
    is_wash_trading: bool
    launchpad: str
    launchpad_platform: str
    liquidity: float
    liquidity_tax: int
    logo: str
    market_cap: float
    max_amount: int
    migrated_pool_exchange: str | None = None
    min_amount: int
    name: str
    net_buy_1h: int
    net_buy_1m: int
    net_buy_24h: int
    net_buy_6h: int
    offchain: bool
    open_source: str
    open_timestamp: int
    open_timestamp_us: int
    other_tax: int
    owner_renounced: str
    pool_address: str
    priority_fee: float
    private_vault_hold_rate: int
    progress: float
    quote_address: str
    rat_trader_amount_rate: float
    renounced_freeze_account: bool
    renounced_mint: bool
    renowned_count: int
    rug_ratio: float
    sell_tax: int
    sells_1h: int
    sells_1m: int
    sells_24h: int
    sells_6h: int
    seq_index: str
    show_sharing_fee: bool
    smart_degen_count: int
    sniper_count: int
    standard: str
    start_live_timestamp: int
    status: int
    suspected_insider_hold_rate: float
    swaps_1h: int
    swaps_1m: int
    swaps_24h: int
    swaps_6h: int
    symbol: str
    tc_name: str
    tcid: str
    telegram: str
    telegram_dup: int
    tg_call_count: int
    tiktok: str
    tip_fee: float
    top70_sniper_hold_rate: float
    top_10_holder_rate: float
    top_10_holder_rate_snp: float
    total_buy_tax: int
    total_fee: float
    total_sell_tax: int
    total_supply: int
    trade_fee: float
    trans_name: str
    trans_name_zhcn: str
    trans_symbol: str
    trans_symbol_zhcn: str
    trigger_count: int
    tweet_publish_time: int
    twitter: str
    twitter_create_token_count: int
    twitter_del_post_token_count: int
    twitter_dup: int
    twitter_handle: str
    twitter_is_tweet: bool
    twitter_rename_count: int
    usd_market_cap: float
    vault_tax: int
    visiting_count: int
    volume_1h: int
    volume_1m: int
    volume_24h: int
    volume_6h: int
    website: str
    website_dup: int
    x_user_follower: int
    x_user_following: int
    zora_social_info: Any


class TokenSignalsParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]


class TokenSignalsRequest(BaseModel):
    groups: Annotated[list[TokenSignalGroupRequest], Field(min_length=1)]
    """
    Signal groups evaluated together; a token matching any group is returned.
    """


class TokenSocialLink(BaseModel):
    address: str
    bitbucket: str
    description: str
    discord: str
    facebook: str
    fracaster: str | None
    geckoterminal: str
    github: str
    gmgn: str
    instagram: str
    linkedin: str
    medium: str
    reddit: str
    telegram: str
    tiktok: str
    twitter_username: str
    verify_status: int
    website: str
    youtube: str


class TokenTradesV2Params(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    cursor: str | None = None
    """
    Pagination token from the previous page's `data.next`.
    """
    maker: str | None = ""
    """
    Restrict to a single maker wallet.
    """
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TokenTrendPoint(BaseModel):
    timestamp: int
    value: str


class TokenTrendSeries(BaseModel):
    avg_holding_balance: list[TokenTrendPoint] | None = None
    bot_degen_percent: list[TokenTrendPoint] | None = None
    bundler_percent: list[TokenTrendPoint] | None = None
    entrapment_percent: list[TokenTrendPoint] | None = None
    holder_count: list[TokenTrendPoint] | None = None
    insider_percent: list[TokenTrendPoint] | None = None
    top100_holder_percent: list[TokenTrendPoint] | None = None
    top10_holder_percent: list[TokenTrendPoint] | None = None


class TokenTrendsParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]
    trends_types: list[TokenTrendsType] | None = [TokenTrendsType.HOLDER_COUNT]
    """
    Series to return. Repeat the param for more than one.
    """


class TokenVote(BaseModel):
    like: int
    unlike: int


class TopBuyerHolderInfo(BaseModel):
    maker_token_tags: list[str]
    status: str | None = None
    tags: list[str] | None
    wallet_address: str


class TopBuyerHolders(BaseModel):
    bought_more: int
    chain: str
    hold_diff: int
    holderInfo: list[TopBuyerHolderInfo]
    holder_count: int
    sold_diff: int
    sold_part_diff: int
    statusNow: TopBuyerStatusNow
    top70_sniper_hold_rate: str


class TopBuyerStatusNow(BaseModel):
    bought_more: int
    bought_rate: str
    hold: int
    holding_rate: str
    smart_count_bought_more: int | None
    smart_count_hold: int | None
    smart_count_sold: int | None
    smart_count_sold_part: int | None
    smart_count_transfered: int | None
    smart_pos: list[int]
    sold: int
    sold_part: int
    top_10_holder_rate: float
    transfered: int


class TopBuyersParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TopCaller(BaseModel):
    avg_multiplier: str
    display_name: str | None = None
    encrypted_user_id: str | None = None
    follower_count: int
    hit_2x_count: int
    is_blue: bool
    prev_rank: int
    profile_image_url: str | None = None
    rank: int
    tier: str
    top_tokens: list[TopCallerToken]
    total_calls: int
    twitter_avatar: str
    twitter_name: str
    twitter_username: str
    username: str | None = None
    wallet: str


class TopCallerToken(BaseModel):
    chain: str
    launchpad: str
    launchpad_platform: str
    multiplier: str
    token: str
    token_logo: str
    token_symbol: str


class TopCallersParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    window: TimeWindow | None = TimeWindow.FIELD_24H
    """
    Window the call multiples are scored over.
    """


class Tpool(BaseModel):
    base_address: str
    exchange: str
    launch_type: str
    pool_address: str
    quote_address: str


class TradeHistory(BaseModel):
    amount_usd: str
    balance: str
    base_amount: str
    dex_native: str
    dex_usd: str
    event: str
    gas_native: str
    gas_usd: str
    history_bought_amount: str
    history_sold_amount: str
    history_sold_income: str
    id: str
    is_open_or_close: int
    maker: str
    maker_avatar: str
    maker_ens: str
    maker_event_tags: list[str]
    maker_name: str
    maker_tags: list[str]
    maker_token_tags: list[str]
    maker_twitter_name: str
    maker_twitter_username: str
    price_usd: str
    priority_fee: str
    quote_address: str
    quote_amount: str
    quote_symbol: str
    realized_profit: str
    timestamp: int
    tip_fee: str
    token_address: str
    total_trade: int
    tx_hash: str
    unrealized_profit: str


class TraderStatParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TradersParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    cursor: str | None = None
    direction: SortDirection | None = SortDirection.DESC
    limit: Annotated[int | None, Field(ge=1, le=1000)] = 100
    order_by: TraderOrderBy | None = TraderOrderBy.PROFIT
    tag: HolderTag | None = None
    """
    Wallet cohort to filter on. Omit for all traders.
    """
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TradesParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    cursor: str | None = None
    """
    Opaque pagination token. trades returns a fixed page (~50) with no page-size control; paginate by passing the previous response's `data.next` token here.
    """
    maker: str | None = ""
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class TrendingChainBucket(BaseModel):
    chain: str
    filter_id: str
    interval: str
    tokens: list[TrendingToken]
    version: str


class TrendingChainRequest(BaseModel):
    chain: Chain | None = None
    """
    Chain to rank tokens on.
    """
    filters: list[TokenFilter] | None = None
    """
    Security screens applied before ranking.
    """
    interval: TrendingInterval | None = None
    """
    Ranking window — GMGN recomputes the leaderboard per window.
    """
    launchpad_platforms: list[str] | None = None
    """
    Restrict to tokens launched on these platforms, e.g. `Pump.fun`, `letsbonk`, `fourmeme`.
    """
    limit: Annotated[int | None, Field(ge=1, le=500)] = None
    """
    Maximum tokens in this chain's bucket. Omit to take GMGN's own default, which is the whole leaderboard it has for that chain.
    """


class TrendingToken(BaseModel):
    a: str
    bdc: int
    bdr: float
    bdrr: float
    bop: float
    br: float
    btax: str
    bu: int
    c: str
    cc: bool
    co_d: bool
    ct: int
    cto: int
    d_br: float
    d_ct: str
    d_ffa: str | None = None
    d_ts: str
    dhr: float
    dtba: float
    dtbr: float
    dx_ad: int
    dx_adts: int
    dx_bf: int
    dx_bts: int
    dx_tb: int
    dx_tbts: int
    dx_ul: int
    dx_ults: int
    elt: int
    etpr: float
    ex: str
    gf: float
    hd: int
    hhmc: int
    hl: int
    ilq: float
    img_dup: str
    isa: bool
    isog: bool
    itl: bool
    itv: str
    iwt: bool
    kol: int
    l: str
    lkp: float | None = None
    lp: str
    lpp: str
    lpst: str
    lq: float
    lqa: str
    m_t: str
    m_w: str
    m_x: str
    m_xctc: int
    m_xdpc: int
    mc: float
    mpe: str
    nm: str
    nt: int
    ntg: int
    nws: int
    ot: int
    p: float
    pcp: float
    pcp1h: float
    pcp1m: float
    pcp5m: float
    rat: float
    rug: float
    s: str
    s_blk: int | None = None
    s_brs: str
    s_ihp: int | None
    s_nm: int | None = None
    s_or: int | None = None
    s_os: int
    s_qsafe: str | None = None
    sc: float
    se: int
    slt: int
    smt: int
    snp: int
    ssf: bool
    stax: str
    std: str | None = None
    sw: int
    t10: float
    t70_shr: float
    tcid: str
    ts_n: str
    ts_nzh: str
    ts_s: str
    ts_szh: str
    tsp: int
    v: float
    v_c: int
    xcc: int
    xcf: int


class TrendingTokensRequest(BaseModel):
    requests: Annotated[list[TrendingChainRequest], Field(min_length=1)]
    """
    One entry per chain. GMGN ranks every entry in a single upstream call and returns the buckets in the same order.
    """


class TwitchKolChannel(BaseModel):
    channel_name: str


class WalletActivityEvent(BaseModel):
    buy_cost_usd: str | None
    chain: str
    cost_usd: str
    dex_native: str
    dex_usd: str
    event_type: str
    from_address: str
    gas_native: str
    gas_usd: str
    is_open_or_close: int
    launchpad: str
    launchpad_platform: str
    price: str
    price_usd: str
    priority_fee: str
    quote_address: str
    quote_amount: str
    quote_token: WalletActivityQuoteToken
    timestamp: int
    tip_fee: str
    to_address: str
    token: WalletActivityToken
    token_amount: str
    tx_hash: str
    wallet: str


class WalletActivityParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    cursor: str | None = None
    """
    Opaque cursor from a previous `next`.
    """
    limit: Annotated[int | None, Field(ge=1, le=100)] = 10
    type: list[str] | None = None
    """
    Event types to include; defaults to buy and sell.
    """
    wallet_address: Annotated[str, Field(examples=["suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"])]


class WalletActivityQuoteToken(BaseModel):
    decimals: int
    logo: str
    name: str
    symbol: str
    token_address: str


class WalletActivityToken(BaseModel):
    address: str
    logo: str
    symbol: str
    total_supply: str


class WalletChainBalance(BaseModel):
    address: str
    balance: str
    chain: str
    token_num: int
    total_volume: str | None


class WalletChainBalancesParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    wallet_address: Annotated[str, Field(examples=["suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"])]


class WalletCommonStatParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    wallet_address: Annotated[str, Field(examples=["suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"])]


class WalletDailyProfit(BaseModel):
    profit: str
    timestamp: int


class WalletPnlParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    period: WalletRankPeriod | None = WalletRankPeriod.FIELD_7D
    """
    Window the P&L is computed over.
    """
    wallet_address: Annotated[str, Field(examples=["suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"])]


class WalletPnlStat(BaseModel):
    avg_holding_period: float | None
    pnl_0x_2x_num: int
    pnl_2x_5x_num: int
    pnl_gt_5x_num: int
    pnl_lt_nd5_num: int
    pnl_nd5_0x_num: int
    token_num: int
    winrate: float | None


class WalletRankingsParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    order_by: WalletRankOrderBy | None = WalletRankOrderBy.PNL_7D
    """
    Metric to sort on. Its window is independent of `period`.
    """
    period: WalletRankPeriod | None = WalletRankPeriod.FIELD_7D
    """
    Leaderboard window GMGN computes the rank over.
    """


class WalletRiskProfile(BaseModel):
    fast_tx: str
    fast_tx_ratio: int
    no_buy_hold: str
    no_buy_hold_ratio: float
    sell_pass_buy: str
    sell_pass_buy_ratio: int
    token_active: str
    token_honeypot: str
    token_honeypot_ratio: int


class WalletStatParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    period: WalletStatPeriod | None = None
    """
    P&L window. Omit for all-time.
    """
    wallet_address: Annotated[str, Field(examples=["suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"])]


class WalletTagRank(BaseModel):
    arbitrager: int | None = None
    axiom: int | None = None
    kol: int | None = None
    photon: int | None = None
    top_followed: int | None = None
    top_renamed: int | None = None
    trojan: int | None = None
    wash_trader: int | None = None


class WalletTagsStatParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


class WebsiteInfoParams(BaseModel):
    chain: Annotated[Chain, Field(examples=["sol"])]
    token_address: Annotated[str, Field(examples=["DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"])]


AggedTradePeriodParam: TypeAlias = AggedTradePeriod | Literal["1m", "5m", "1h", "4h"]
AggedTradeTagParam: TypeAlias = (
    AggedTradeTag
    | Literal[
        "dev_team",
        "smart_degen",
        "insider",
        "sniper",
        "bundler",
        "fresh_wallet",
        "bluechip_owner",
        "renowned",
        "rat_trader",
    ]
)
ChainParam: TypeAlias = (
    Chain
    | Literal[
        "sol",
        "eth",
        "bsc",
        "base",
        "tron",
        "monad",
        "megaeth",
        "hyperevm",
        "robinhood",
        "arbitrum",
        "arc",
        "stable",
        "xlayer",
    ]
)
HolderOrderByParam: TypeAlias = (
    HolderOrderBy
    | Literal[
        "amount_percentage",
        "last_active_timestamp",
        "netflow_usd",
        "profit",
        "realized_profit",
        "unrealized_profit",
        "buy_volume_cur",
        "sell_volume_cur",
    ]
)
HolderTagParam: TypeAlias = (
    HolderTag
    | Literal[
        "smart_degen",
        "fresh_wallet",
        "renowned",
        "bundler",
        "bluechip_owner",
        "sniper",
        "rat_trader",
        "dev",
        "transfer_in",
        "dex_bot",
    ]
)
NewPairsOrderByParam: TypeAlias = (
    NewPairsOrderBy
    | Literal[
        "open_timestamp",
        "creation_timestamp",
        "market_cap",
        "holder_count",
        "liquidity",
        "volume",
        "swaps",
        "progress",
        "price_change_percent1h",
    ]
)
ResolutionParam: TypeAlias = (
    Resolution
    | Literal[
        "1s", "15s", "30s", "1m", "3m", "5m", "15m", "30m", "1h", "4h", "12h", "1d", "1w", "1mo"
    ]
)
SimilarCoinsOrderByParam: TypeAlias = SimilarCoinsOrderBy | Literal["mcp", "open_or_create_time"]
SortDirectionParam: TypeAlias = SortDirection | Literal["desc"]
TimeWindowParam: TypeAlias = TimeWindow | Literal["1h", "24h"]
TokenFilterParam: TypeAlias = (
    TokenFilter | Literal["not_honeypot", "verified", "renounced", "frozen", "has_social", "burn"]
)
TokenTrendsTypeParam: TypeAlias = (
    TokenTrendsType
    | Literal[
        "avg_holding_balance",
        "holder_count",
        "top10_holder_percent",
        "top100_holder_percent",
        "bundler_percent",
        "insider_percent",
        "bot_degen_percent",
        "entrapment_percent",
    ]
)
TraderOrderByParam: TypeAlias = (
    TraderOrderBy
    | Literal[
        "profit",
        "realized_profit",
        "unrealized_profit",
        "amount_percentage",
        "last_active_timestamp",
        "netflow_usd",
        "buy_volume_cur",
        "sell_volume_cur",
    ]
)
TrendingIntervalParam: TypeAlias = TrendingInterval | Literal["1m", "5m", "1h", "6h", "24h"]
WalletRankOrderByParam: TypeAlias = (
    WalletRankOrderBy
    | Literal["pnl_1d", "pnl_7d", "pnl_30d", "winrate_1d", "winrate_7d", "winrate_30d"]
)
WalletRankPeriodParam: TypeAlias = WalletRankPeriod | Literal["1d", "7d", "30d"]
WalletStatPeriodParam: TypeAlias = WalletStatPeriod | Literal["1d", "7d", "all"]
PublicErrorValue: TypeAlias = Annotated[PublicError | str, PREFER_ENUM]
