# Generated by generate-client from spec/openapi.json. Do not edit.
"""Every type the goplus endpoints send and accept."""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, TypeAlias

from pydantic import Field

from tapline._models import PREFER_ENUM, BaseModel


class GoplusChainId(str, Enum):
    FIELD_1 = "1"
    FIELD_56 = "56"
    FIELD_8453 = "8453"
    FIELD_4663 = "4663"


class PublicError(str, Enum):
    BLOCKED = "blocked"
    CONCURRENCY_EXCEEDED = "concurrency_exceeded"
    TIMEOUT = "timeout"
    EXTRACTION_FAILED = "extraction_failed"
    UPSTREAM_BLOCKED = "upstream_blocked"
    UPSTREAM_UNAVAILABLE = "upstream_unavailable"
    UPSTREAM_RESPONSE_INVALID = "upstream_response_invalid"
    INVALID_URL_SCHEME = "invalid_url_scheme"
    INVALID_URL_HOST = "invalid_url_host"
    UNAUTHENTICATED = "unauthenticated"
    FORBIDDEN = "forbidden"
    RESOURCE_FORBIDDEN = "resource_forbidden"
    NOT_FOUND = "not_found"
    RATE_LIMITED = "rate_limited"
    INVALID_REQUEST = "invalid_request"
    INVALID_CURSOR = "invalid_cursor"
    INSUFFICIENT_CREDITS = "insufficient_credits"
    INTERNAL_ERROR = "internal_error"


class ErrorDetail(BaseModel):
    ctx: dict[str, Any] | None = None
    input: Any = None
    loc: list[str | int] | None = None
    msg: str | None = None
    type: str | None = None


class ErrorResponse(BaseModel):
    code: PublicErrorValue
    details: list[ErrorDetail] | None = None
    domain: str | None = None
    message: str
    request_id: str
    upgrade_url: str | None = None


class GetEvmTokenSecurityParams(BaseModel):
    address: Annotated[
        str,
        Field(
            examples=["0x9c39e4b2c74bdc4454f6397f0ae3771c0b12ffff"],
            pattern="^0x[0-9a-fA-F]{40}$",
        ),
    ]
    """
    Token contract address: 0x plus 40 hex characters, any case.
    """
    chain_id: GoplusChainId
    """
    EVM chain id: 1 Ethereum, 56 BNB Chain, 8453 Base, 4663 Robinhood Chain.
    """


class GetEvmTokenSecurityResponse(BaseModel):
    code: int | None = None
    message: str | None = None
    result: dict[str, GoplusEvmTokenSecurity] | None = None


class GetSolanaTokenSecurityParams(BaseModel):
    mint: Annotated[
        str,
        Field(
            examples=["66UokDvAUWuT8DiX1JxAyisx3uo4nErZYQocXTowQm2G"],
            pattern="^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        ),
    ]
    """
    Token mint address, base58.
    """


class GetSolanaTokenSecurityResponse(BaseModel):
    code: int | None = None
    message: str | None = None
    result: dict[str, GoplusSolanaTokenSecurity] | None = None


class GoplusEvmCexListing(BaseModel):
    cex_list: list[str] | None = None
    listed: str | None = None


class GoplusEvmDex(BaseModel):
    liquidity: str | None = None
    liquidity_type: str | None = None
    name: str | None = None
    pair: str | None = None
    pool_fee: str | None = None
    pool_manager: str | None = None


class GoplusEvmHolder(BaseModel):
    address: str | None = None
    balance: str | None = None
    is_contract: int | None = None
    is_locked: int | None = None
    percent: str | None = None
    tag: str | None = None


class GoplusEvmLpHolder(BaseModel):
    NFT_list: list[GoplusEvmLpNft] | None = None
    address: str | None = None
    balance: str | None = None
    is_contract: int | None = None
    is_locked: int | None = None
    percent: str | None = None
    tag: str | None = None
    value: str | None = None


class GoplusEvmLpNft(BaseModel):
    NFT_id: str | None = None
    NFT_percentage: str | None = None
    amount: str | None = None
    in_effect: str | None = None
    value: str | None = None


class GoplusEvmTokenSecurity(BaseModel):
    anti_whale_modifiable: str | None = None
    buy_tax: str | None = None
    can_take_back_ownership: str | None = None
    cannot_buy: str | None = None
    cannot_sell_all: str | None = None
    creator_address: str | None = None
    creator_balance: str | None = None
    creator_percent: str | None = None
    dex: list[GoplusEvmDex] | None = None
    external_call: str | None = None
    hidden_owner: str | None = None
    holder_count: str | None = None
    holders: list[GoplusEvmHolder] | None = None
    honeypot_with_same_creator: str | None = None
    is_anti_whale: str | None = None
    is_blacklisted: str | None = None
    is_honeypot: str | None = None
    is_in_cex: GoplusEvmCexListing | None = None
    is_in_dex: str | None = None
    is_mintable: str | None = None
    is_open_source: str | None = None
    is_proxy: str | None = None
    is_whitelisted: str | None = None
    lp_holder_count: str | None = None
    lp_holders: list[GoplusEvmLpHolder] | None = None
    lp_total_supply: str | None = None
    owner_address: str | None = None
    owner_balance: str | None = None
    owner_change_balance: str | None = None
    owner_percent: str | None = None
    personal_slippage_modifiable: str | None = None
    selfdestruct: str | None = None
    sell_tax: str | None = None
    slippage_modifiable: str | None = None
    token_name: str | None = None
    token_symbol: str | None = None
    total_supply: str | None = None
    trading_cooldown: str | None = None
    transfer_pausable: str | None = None
    transfer_tax: str | None = None


class GoplusSolanaAddress(BaseModel):
    address: str | None = None
    malicious_address: int | None = None


class GoplusSolanaAuthorityStatus(BaseModel):
    authority: list[GoplusSolanaAddress] | None = None
    status: str | None = None


class GoplusSolanaDex(BaseModel):
    burn_percent: float | None = None
    day: GoplusSolanaDexWindow | None = None
    dex_name: str | None = None
    fee_rate: str | None = None
    id: str | None = None
    lp_amount: str | None = None
    month: GoplusSolanaDexWindow | None = None
    open_time: str | None = None
    price: str | None = None
    tvl: str | None = None
    type: str | None = None
    week: GoplusSolanaDexWindow | None = None


class GoplusSolanaDexWindow(BaseModel):
    price_max: str | None = None
    price_min: str | None = None
    volume: str | None = None


class GoplusSolanaFeeRate(BaseModel):
    fee_rate: str | None = None
    maximum_fee: str | None = None


class GoplusSolanaHolder(BaseModel):
    account: str | None = None
    balance: str | None = None
    is_locked: int | None = None
    locked_detail: list[Any] | None = None
    percent: str | None = None
    tag: str | None = None
    token_account: str | None = None


class GoplusSolanaMetadata(BaseModel):
    description: str | None = None
    name: str | None = None
    symbol: str | None = None
    uri: str | None = None


class GoplusSolanaMetadataMutable(BaseModel):
    metadata_upgrade_authority: list[GoplusSolanaAddress] | None = None
    status: str | None = None


class GoplusSolanaScheduledFeeRate(BaseModel):
    epoch: str | None = None
    fee_rate: str | None = None
    maximum_fee: str | None = None


class GoplusSolanaTokenSecurity(BaseModel):
    balance_mutable_authority: GoplusSolanaAuthorityStatus | None = None
    closable: GoplusSolanaAuthorityStatus | None = None
    creators: list[Any] | None = None
    default_account_state: str | None = None
    default_account_state_upgradable: GoplusSolanaAuthorityStatus | None = None
    dex: list[GoplusSolanaDex] | None = None
    freezable: GoplusSolanaAuthorityStatus | None = None
    holder_count: str | None = None
    holders: list[GoplusSolanaHolder] | None = None
    lp_holders: list[GoplusSolanaHolder] | None = None
    metadata: GoplusSolanaMetadata | None = None
    metadata_mutable: GoplusSolanaMetadataMutable | None = None
    mintable: GoplusSolanaAuthorityStatus | None = None
    non_transferable: str | None = None
    total_supply: str | None = None
    transfer_fee: GoplusSolanaTransferFee | None = None
    transfer_fee_upgradable: GoplusSolanaAuthorityStatus | None = None
    transfer_hook: list[GoplusSolanaAddress] | None = None
    transfer_hook_upgradable: GoplusSolanaAuthorityStatus | None = None
    trusted_token: int | None = None


class GoplusSolanaTransferFee(BaseModel):
    current_fee_rate: GoplusSolanaFeeRate | None = None
    scheduled_fee_rate: list[GoplusSolanaScheduledFeeRate] | None = None


GoplusChainIdParam: TypeAlias = GoplusChainId | Literal["1", "56", "8453", "4663"]
PublicErrorValue: TypeAlias = Annotated[PublicError | str, PREFER_ENUM]
