# Generated by generate-client from spec/openapi.json. Do not edit.
# ruff: noqa: E741
"""Every type the geckoterminal endpoints send and accept."""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, TypeAlias

from pydantic import Field

from tapline._models import PREFER_ENUM, BaseModel


class CandlestickCurrency(str, Enum):
    USD = "usd"
    TOKEN = "token"


class CandlestickResolution(str, Enum):
    FIELD_1 = "1"
    FIELD_5 = "5"
    FIELD_15 = "15"
    FIELD_60 = "60"
    FIELD_120 = "120"
    FIELD_240 = "240"
    FIELD_720 = "720"
    FIELD_1_D = "1D"


class HolderHistoryPeriod(str, Enum):
    FIELD_1_W = "1W"
    FIELD_1_M = "1M"
    ALL = "all"


class PoolFilterTimeframe(str, Enum):
    FIELD_5M = "5m"
    FIELD_1H = "1h"
    FIELD_6H = "6h"
    FIELD_24H = "24h"


class PoolSort(str, Enum):
    FIELD_5M_TREND_SCORE = "-5m_trend_score"
    FIELD_1H_TREND_SCORE = "-1h_trend_score"
    FIELD_6H_TREND_SCORE = "-6h_trend_score"
    FIELD_24H_TREND_SCORE = "-24h_trend_score"
    FIELD_24H_TRANSACTIONS = "-24h_transactions"
    FIELD_24H_VOLUME = "-24h_volume"
    FIELD_POOL_CREATION_DATE = "-pool_creation_date"
    FIELD_24H_PRICE_PERCENT_CHANGE = "-24h_price_percent_change"
    FIELD_6H_PRICE_PERCENT_CHANGE = "-6h_price_percent_change"
    FIELD_1H_PRICE_PERCENT_CHANGE = "-1h_price_percent_change"
    FIELD_5M_PRICE_PERCENT_CHANGE = "-5m_price_percent_change"
    FDV = "fdv"
    FIELD_FDV = "-fdv"
    LIQUIDITY = "liquidity"
    FIELD_LIQUIDITY = "-liquidity"
    MC = "mc"
    FIELD_MC = "-mc"


class PublicError(str, Enum):
    BLOCKED = "blocked"
    CONCURRENCY_EXCEEDED = "concurrency_exceeded"
    TIMEOUT = "timeout"
    EXTRACTION_FAILED = "extraction_failed"
    UPSTREAM_BLOCKED = "upstream_blocked"
    UPSTREAM_UNAVAILABLE = "upstream_unavailable"
    UPSTREAM_RESPONSE_INVALID = "upstream_response_invalid"
    INVALID_URL_SCHEME = "invalid_url_scheme"
    INVALID_URL_HOST = "invalid_url_host"
    UNAUTHENTICATED = "unauthenticated"
    FORBIDDEN = "forbidden"
    RESOURCE_FORBIDDEN = "resource_forbidden"
    NOT_FOUND = "not_found"
    RATE_LIMITED = "rate_limited"
    INVALID_REQUEST = "invalid_request"
    INVALID_CURSOR = "invalid_cursor"
    INSUFFICIENT_CREDITS = "insufficient_credits"
    INTERNAL_ERROR = "internal_error"


class CandlesticksParams(BaseModel):
    currency: CandlestickCurrency | None = CandlestickCurrency.USD
    """
    Denomination of the bar prices.
    """
    from_timestamp: Annotated[int, Field(ge=0)]
    """
    Unix timestamp for the start of the window.
    """
    is_inverted: bool | None = False
    """
    Quote bars in the other token of the pair.
    """
    pair_id: Annotated[str, Field(examples=["1770231"])]
    """
    GeckoTerminal numeric pair id, from the pool's `pairs` relationship.
    """
    pool_id: Annotated[str, Field(examples=["162714737"])]
    """
    GeckoTerminal numeric pool id, as returned in a pool resource's `id`.
    """
    resolution: CandlestickResolution | None = CandlestickResolution.FIELD_15
    """
    Bar width in minutes, or `1D`.
    """
    to_timestamp: Annotated[int, Field(ge=0)]
    """
    Unix timestamp for the end of the window.
    """


class CandlesticksResponse(BaseModel):
    data: list[CandlesticksResponseData]
    meta: dict[str, str]


class CandlesticksResponseData(BaseModel):
    c: float
    dt: str
    h: float
    l: float
    o: float
    v: float


class DexAttributes(BaseModel):
    analytics_pool_page_url: str | None = None
    analytics_token_page_url: str | None = None
    identifier: str | None = None
    image_url: str
    is_bonding_curve: bool | None = None
    is_launchpad: bool | None = None
    name: str
    no_reserves: bool | None = None
    url: str | None = None


class DexLinkServiceAttributes(BaseModel):
    category: str
    image_url: str
    name: str
    priority: int | None
    sub_category: str
    url: str


class DexLinkServiceResource(BaseModel):
    attributes: DexLinkServiceAttributes
    id: str
    type: str


class DexMetricAttributes(BaseModel):
    pools_count: int
    rank_by_volume: int | None
    reserve_in_usd: str
    swap_count_24h: int
    swap_volume_percent_change_24h: float | int | str
    swap_volume_usd_24h: str
    swap_volume_usd_48h_24h: str
    tokens_count: int


class DexMetricResource(BaseModel):
    attributes: DexMetricAttributes
    id: str
    type: str


class DexRelationships(BaseModel):
    dex_metric: ResourceLinkage | None = None
    network: ResourceLinkage


class DexResource(BaseModel):
    attributes: DexAttributes
    id: str
    relationships: DexRelationships
    type: str


class DexesParams(BaseModel):
    network: Annotated[str | None, Field(examples=["solana"])] = None
    """
    Restrict results to one network identifier.
    """
    page: Annotated[int | None, Field(ge=1)] = None
    """
    1-based result page.
    """


class DexesResponse(BaseModel):
    data: list[DexResource]
    included: list[DexMetricResource | NetworkResource]
    links: DexesResponseLinks


class DexesResponseLinks(BaseModel):
    first: str
    last: DexesResponseLinksLast
    next: str | None
    prev: str | None


class DexesResponseLinksLast(BaseModel):
    href: str
    meta: DexesResponseLinksLastMeta


class DexesResponseLinksLastMeta(BaseModel):
    series: list[str]


class ErrorDetail(BaseModel):
    ctx: dict[str, Any] | None = None
    input: Any = None
    loc: list[str | int] | None = None
    msg: str | None = None
    type: str | None = None


class ErrorResponse(BaseModel):
    code: PublicErrorValue
    details: list[ErrorDetail] | None = None
    domain: str | None = None
    message: str
    request_id: str


class ExplorerAttributes(BaseModel):
    coin_url: str
    holders_url: str
    logo_url: str
    name: str
    rank: int | None
    tx_url: str
    url: str


class ExplorerResource(BaseModel):
    attributes: ExplorerAttributes
    id: str
    type: str


class GlobalStatAttributes(BaseModel):
    dexes_count: int
    eth_gas_oracle: GlobalStatAttributesEthGasOracle
    fng_stats: GlobalStatAttributesFngStats
    networks_count: int
    pools_count: int
    tokens_count: int


class GlobalStatAttributesEthGasOracle(BaseModel):
    fast_gas_price: float
    gas_used_ratio: str
    last_block: int
    propose_gas_price: float
    safe_gas_price: float
    suggest_base_fee: float
    updated_at: str


class GlobalStatAttributesFngStats(BaseModel):
    next_update_at: str
    value: int
    value_classification: str


class GlobalStatResource(BaseModel):
    attributes: GlobalStatAttributes
    id: str
    type: str


class GlobalStatsResponse(BaseModel):
    data: GlobalStatResource


class LatestPoolsParams(BaseModel):
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    1-based result page.
    """
    pool_creation_hours_ago_lte: Annotated[int | None, Field(ge=1)] = 72
    """
    Only include pools created within this many hours.
    """


class LatestPoolsResponse(BaseModel):
    data: list[PoolResource]
    included: list[DexResource | NetworkResource | PoolMetricResource | TokenResource]
    links: LatestPoolsResponseLinks
    meta: LatestPoolsResponseMeta


class LatestPoolsResponseLinks(BaseModel):
    first: str
    last: LatestPoolsResponseLinksLast
    next: str | None
    prev: str | None


class LatestPoolsResponseLinksLast(BaseModel):
    meta: LatestPoolsResponseLinksLastMeta


class LatestPoolsResponseLinksLastMeta(BaseModel):
    series: list[int | str]


class LatestPoolsResponseMeta(BaseModel):
    sort: str


class NetworkAttributes(BaseModel):
    cg_network_id: str | None = None
    chain_id: int | None = None
    explorer_coin_url: str | None = None
    explorer_logo_url: str | None = None
    explorer_tx_url: str | None = None
    explorer_url: str | None = None
    identifier: str
    image_url: str | None = None
    is_new: bool | None = None
    name: str | None = None
    native_currency_address: str | None = None
    native_currency_symbol: str | None = None
    pool_reserve_threshold: str | None = None
    supports_top_holders: bool | None = None


class NetworkLatestPoolsParams(BaseModel):
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    1-based result page.
    """
    pool_creation_hours_ago_lte: Annotated[int | None, Field(ge=1)] = 72
    """
    Only include pools created within this many hours.
    """


class NetworkLatestPoolsResponse(BaseModel):
    data: list[PoolResource]
    included: list[DexResource | NetworkResource | PoolMetricResource | TokenResource]
    links: LatestPoolsResponseLinks
    meta: NetworkLatestPoolsResponseMeta


class NetworkLatestPoolsResponseMeta(BaseModel):
    network: str
    sort: str


class NetworkLinkServiceAttributes(BaseModel):
    category: str
    image_url: str
    name: str
    priority: int | None
    sub_category: str | None
    url: str


class NetworkLinkServiceResource(BaseModel):
    attributes: NetworkLinkServiceAttributes
    id: str
    type: str


class NetworkMetricAttributes(BaseModel):
    dexes_count: int | None = None
    latest_pools_count: int
    pools_count: int | None = None
    rank_by_liquidity: int | None = None
    reserve_in_usd: str | None = None
    swap_count_24h: int | None = None
    swap_volume_percent_change_24h: str | None = None
    swap_volume_usd_24h: str | None = None
    swap_volume_usd_48h_24h: str | None = None
    tokens_count: int | None = None
    trending_pools_count: int | None = None


class NetworkMetricResource(BaseModel):
    attributes: NetworkMetricAttributes
    id: str
    type: str


class NetworkPoolScreenerRequest(BaseModel):
    buy_tax: RangeFilter | None = None
    """
    Buy tax percentage.
    """
    buys: TimeframedRangeFilter | None = None
    """
    Buy count over the chosen window.
    """
    dex: str | None = None
    """
    Restrict to a single DEX on this network, by identifier.
    """
    dexes: list[str] | None = None
    """
    Restrict to these DEX identifiers.
    """
    fdv_in_usd: RangeFilter | None = None
    """
    Fully diluted valuation in USD.
    """
    good_gt_score: bool | None = None
    """
    Only pools above GeckoTerminal's GT score threshold.
    """
    has_social: bool | None = None
    """
    Only pools whose token declares social links.
    """
    holder_count: RangeFilter | None = None
    """
    Number of token holders.
    """
    liquidity: RangeFilter | None = None
    """
    Pool liquidity in USD.
    """
    mc_in_usd: RangeFilter | None = None
    """
    Market cap in USD.
    """
    networks: list[str] | None = None
    """
    Restrict to these network identifiers.
    """
    no_honeypot: bool | None = None
    """
    Exclude tokens flagged as honeypots.
    """
    on_coingecko: bool | None = None
    """
    Only pools whose token is listed on CoinGecko.
    """
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    1-based result page.
    """
    pool_creation_hours_ago: RangeFilter | None = None
    """
    Pool age in hours.
    """
    sell_tax: RangeFilter | None = None
    """
    Sell tax percentage.
    """
    sells: TimeframedRangeFilter | None = None
    """
    Sell count over the chosen window.
    """
    sort: PoolSort | None = None
    """
    Ranking applied before pagination. Omit for GeckoTerminal's default.
    """
    top_10_holders_percentage: RangeFilter | None = None
    """
    Share of supply held by the ten largest holders.
    """
    tx_count: TimeframedRangeFilter | None = None
    """
    Transaction count over the chosen window.
    """
    volume_24h: RangeFilter | None = None
    """
    24h traded volume in USD.
    """


class NetworkPoolsParams(BaseModel):
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """


class NetworkPoolsResponse(BaseModel):
    data: list[PoolResource]
    included: list[DexMetricResource | DexResource | NetworkResource | TokenResource]
    links: LatestPoolsResponseLinks
    meta: LatestPoolsResponseMeta


class NetworkRankingsParams(BaseModel):
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    1-based result page.
    """


class NetworkRankingsResponse(BaseModel):
    data: list[NetworkResource]
    included: list[NetworkMetricResource]
    links: LatestPoolsResponseLinks


class NetworkRelationships(BaseModel):
    explorers: ResourceLinkageList | None = None
    network_metric: ResourceLinkage | None = None


class NetworkResource(BaseModel):
    attributes: NetworkAttributes
    id: str
    relationships: NetworkRelationships
    type: str


class NetworksParams(BaseModel):
    sort: Annotated[str | None, Field(examples=["-24h_volume"])] = None
    """
    Ordering applied to the chain list, e.g. `-24h_volume`.
    """


class NetworksResponse(BaseModel):
    data: list[NetworkResource]


class PairAttributes(BaseModel):
    base_address: str
    base_name: str
    base_price_in_currency: str
    base_price_in_quote: str
    base_price_in_usd: str
    base_price_in_usd_percent_change: float
    base_symbol: str
    base_token_id: str
    data_24h: PairAttributesData24h
    name: str
    price_change_data: PairAttributesPriceChangeData
    quote_address: str
    quote_name: str
    quote_price_in_base: str
    quote_price_in_currency: str
    quote_price_in_usd: str
    quote_price_in_usd_percent_change: float
    quote_symbol: str
    quote_token_id: str
    swap_count: int
    transaction_data: PairAttributesTransactionData
    volume_data: PairAttributesVolumeData
    volume_in_currency: str
    volume_in_usd: str


class PairAttributesData24h(BaseModel):
    buys: int
    sells: int
    total_in_usd: float


class PairAttributesPriceChangeData(BaseModel):
    last_172800_s: PairAttributesPriceChangeDataEntry
    last_1800_s: PairAttributesPriceChangeDataEntry
    last_21600_s: PairAttributesPriceChangeDataEntry
    last_300_s: PairAttributesPriceChangeDataEntry
    last_3600_s: PairAttributesPriceChangeDataEntry
    last_43200_s: PairAttributesPriceChangeDataEntry
    last_7200_s: PairAttributesPriceChangeDataEntry
    last_86400_s: PairAttributesPriceChangeDataEntry
    last_900_s: PairAttributesPriceChangeDataEntry


class PairAttributesPriceChangeDataEntry(BaseModel):
    base_token_percentage: float
    base_token_usd: float
    prices: PairAttributesPriceChangeDataEntryPrices
    quote_token_percentage: float
    quote_token_usd: float


class PairAttributesPriceChangeDataEntryPrices(BaseModel):
    base_token_high_price_in_usd: float | None = None
    base_token_high_price_timestamp: str | None = None
    base_token_last_price_in_usd: float | None = None
    base_token_low_price_in_usd: float | None = None
    base_token_low_price_timestamp: str | None = None
    base_token_start_price_in_usd: float | None = None
    quote_token_high_price_in_usd: float | None = None
    quote_token_high_price_timestamp: str | None = None
    quote_token_last_price_in_usd: float | None = None
    quote_token_low_price_in_usd: float | None = None
    quote_token_low_price_timestamp: str | None = None
    quote_token_start_price_in_usd: float | None = None


class PairAttributesTransactionData(BaseModel):
    last_172800_s: PairAttributesTransactionDataEntry
    last_1800_s: PairAttributesTransactionDataEntry
    last_21600_s: PairAttributesTransactionDataEntry
    last_300_s: PairAttributesTransactionDataEntry
    last_3600_s: PairAttributesTransactionDataEntry
    last_43200_s: PairAttributesTransactionDataEntry
    last_7200_s: PairAttributesTransactionDataEntry
    last_86400_s: PairAttributesTransactionDataEntry
    last_900_s: PairAttributesTransactionDataEntry


class PairAttributesTransactionDataEntry(BaseModel):
    buys: int
    sells: int


class PairAttributesVolumeData(BaseModel):
    last_172800_s: PairAttributesVolumeDataEntry
    last_1800_s: PairAttributesVolumeDataEntry
    last_21600_s: PairAttributesVolumeDataEntry
    last_300_s: PairAttributesVolumeDataEntry
    last_3600_s: PairAttributesVolumeDataEntry
    last_43200_s: PairAttributesVolumeDataEntry
    last_7200_s: PairAttributesVolumeDataEntry
    last_86400_s: PairAttributesVolumeDataEntry
    last_900_s: PairAttributesVolumeDataEntry


class PairAttributesVolumeDataEntry(BaseModel):
    buys_in_currency_token: float
    buys_in_usd: float
    sells_in_currency_token: float
    sells_in_usd: float
    total_in_base_token: float
    total_in_currency_token: float
    total_in_quote_token: float
    total_in_usd: float


class PairRelationships(BaseModel):
    pool: ResourceLinkage


class PairResource(BaseModel):
    attributes: PairAttributes
    id: str
    relationships: PairRelationships
    type: str


class PastTokensDeveloperDetailAttributes(BaseModel):
    past_tokens: list[PastTokensDeveloperDetailAttributesPastTokens] | list[str]
    past_tokens_count: int


class PastTokensDeveloperDetailAttributesPastTokens(BaseModel):
    address: str
    fdv_in_usd: float
    market_cap_in_usd: float | None
    name: str
    symbol: str
    token_image_url: str
    top_pool_address: str


class PastTokensDeveloperDetailResource(BaseModel):
    attributes: PastTokensDeveloperDetailAttributes
    id: str
    type: str


class PoolAttributes(BaseModel):
    address: str
    aggregated_network_metrics: PoolAttributesAggregatedNetworkMetrics | None = None
    api_address: str | None = None
    balancer_pool_id: str | None = None
    base_token_id: str
    from_volume_in_usd: str | None = None
    fully_diluted_valuation: str | None = None
    graduated_pool_address: str | None = None
    graduation_percentage: float | None = None
    gt_score: float | None = None
    gt_score_details: PoolAttributesGtScoreDetails | None = None
    high_low_price_data_by_token_id: (
        dict[str, PoolAttributesHighLowPriceDataByTokenIdEntry] | None
    ) = None
    historical_data: PoolAttributesHistoricalData | None = None
    holder_count: int | None = None
    is_nsfw: bool | None = None
    is_pool_address_explorable: bool | None = None
    is_stale_pool: bool | None = None
    is_suspicious_chart: bool | None = None
    latest_swap_timestamp: str | None = None
    name: str | None = None
    net_volume_data_24h: PoolAttributesNetVolumeData24h | None = None
    pool_created_at: str
    pool_fee: str | None = None
    pool_reports_count: int | None = None
    price_in_target_token: str | None = None
    price_in_usd: str | None = None
    price_percent_change: str | None
    price_percent_changes: PoolAttributesPricePercentChanges | None = None
    price_sparkline_7d: list[float] | None = None
    reserve_in_usd: str | None = None
    reserve_threshold_met: bool | None = None
    risk_flags: list[str] | None = None
    security_indicators: list[str] | None = None
    security_indicators_data: PoolAttributesSecurityIndicatorsData | None = None
    sentiment_votes: PoolAttributesSentimentVotes | None = None
    suggested_pools_by_liquidity: PoolAttributesSuggestedPoolsByLiquidity | None = None
    swap_count_24h: int | None = None
    swap_url: str | None = None
    tagged_token_id: str | None = None
    to_volume_in_usd: str | None = None
    token_reserves: dict[str, PoolAttributesTokenReservesEntry] | None = None
    token_value_data: dict[str, PoolAttributesTokenValueDataEntry] | None = None
    token_weightages: dict[str, Any] | None = None
    trending_narrative: str | None = None


class PoolAttributesAggregatedNetworkMetrics(BaseModel):
    total_swap_count_24h: int
    total_swap_volume_percent_change_24h: str
    total_swap_volume_usd_24h: str
    total_swap_volume_usd_48h_24h: str


class PoolAttributesGtScoreDetails(BaseModel):
    creation: float
    holders: float
    info: float
    pool: float
    transactions: float


class PoolAttributesHighLowPriceDataByTokenIdEntry(BaseModel):
    high_price_in_usd_24h: float
    high_price_timestamp_24h: str
    low_price_in_usd_24h: float
    low_price_timestamp_24h: str


class PoolAttributesHistoricalData(BaseModel):
    last_15m: PoolAttributesHistoricalDataEntry
    last_1h: PoolAttributesHistoricalDataEntry
    last_24h: PoolAttributesHistoricalDataEntry
    last_30m: PoolAttributesHistoricalDataEntry
    last_5m: PoolAttributesHistoricalDataEntry
    last_6h: PoolAttributesHistoricalDataEntry


class PoolAttributesHistoricalDataEntry(BaseModel):
    buy_swaps_count: int
    buy_volume_in_usd: str | None = None
    buyers_count: int
    net_volume_in_usd: str | None = None
    price_in_usd: str | None
    sell_swaps_count: int
    sell_volume_in_usd: str | None = None
    sellers_count: int
    swaps_count: int
    volume_in_usd: str


class PoolAttributesNetVolumeData24h(BaseModel):
    buy_volume_in_usd: str
    net_volume_in_usd: str
    sell_volume_in_usd: str


class PoolAttributesPricePercentChanges(BaseModel):
    last_15m: str | None
    last_1h: str | None
    last_24h: str | None
    last_30m: str | None
    last_5m: str | None
    last_6h: str | None


class PoolAttributesSecurityIndicatorsData(BaseModel):
    bundler_percentage: float | None
    buy_tax: float | None
    cluster_percentage: float | None
    developer_holding_percentage: float | None
    early_buyers_percentage: float | None
    freezable: bool | None
    gt_score: float | None
    holder_count: int | None
    honeypot: bool | None
    is_liquidity_locked: bool | None
    mintable: bool | None
    pool_created_at: str
    sell_tax: float | None
    top_10_holders_percentage: float | None


class PoolAttributesSentimentVotes(BaseModel):
    down_percentage: float
    total: float
    up_percentage: float


class PoolAttributesSuggestedPoolsByLiquidity(BaseModel):
    by_base_token_address: list[str]
    by_base_token_symbol: list[PoolAttributesSuggestedPoolsByLiquidityByBaseTokenSymbol]


class PoolAttributesSuggestedPoolsByLiquidityByBaseTokenSymbol(BaseModel):
    address: str
    dex_identifier: str
    dex_name: str
    name: str
    network_identifier: str


class PoolAttributesTokenReservesEntry(BaseModel):
    reserves: str
    reserves_in_usd: float


class PoolAttributesTokenValueDataEntry(BaseModel):
    fdv_in_usd: float | None
    market_cap_in_usd: float | None
    market_cap_to_holders_ratio: float | None


class PoolLockedLiquidityAttributes(BaseModel):
    final_unlock_timestamp: str | None
    locked_percent: float
    next_unlock_percent: float | None
    next_unlock_timestamp: str | None
    source: str
    url: str


class PoolLockedLiquidityResource(BaseModel):
    attributes: PoolLockedLiquidityAttributes
    id: str
    type: str


class PoolMetricAttributes(BaseModel):
    currency_token_id: int
    currency_token_symbol: str
    dex_id: int
    from_token_address: str
    from_token_id: int
    from_token_name: str
    from_token_symbol: str
    from_volume: str
    from_volume_in_currency_token: str
    from_volume_in_usd: str
    historical_data: dict[str, PoolMetricAttributesHistoricalDataEntry]
    pool_id: int
    price: str
    reserve_in_currency_token: str
    reserve_in_usd: str
    swap_count_24h: int
    to_token_address: str
    to_token_id: int
    to_token_name: str
    to_token_symbol: str
    to_volume: str
    to_volume_in_currency_token: str
    to_volume_in_usd: str


class PoolMetricAttributesHistoricalDataEntry(BaseModel):
    last_172800_s: PoolMetricAttributesHistoricalDataEntryEntry
    last_1800_s: PoolMetricAttributesHistoricalDataEntryEntry
    last_21600_s: PoolMetricAttributesHistoricalDataEntryEntry
    last_300_s: PoolMetricAttributesHistoricalDataEntryEntry
    last_3600_s: PoolMetricAttributesHistoricalDataEntryEntry
    last_43200_s: PoolMetricAttributesHistoricalDataEntryEntry
    last_7200_s: PoolMetricAttributesHistoricalDataEntryEntry
    last_86400_s: PoolMetricAttributesHistoricalDataEntryEntry
    last_900_s: PoolMetricAttributesHistoricalDataEntryEntry


class PoolMetricAttributesHistoricalDataEntryEntry(BaseModel):
    buy_swaps_count: int
    buy_volume_in_usd: str
    buyers_count: int
    net_volume_in_usd: str
    price_in_usd: str | None
    sell_swaps_count: int
    sell_volume_in_usd: str
    sellers_count: int
    swaps_count: int
    volume_in_usd: str


class PoolMetricResource(BaseModel):
    attributes: PoolMetricAttributes
    id: str
    type: str


class PoolParams(BaseModel):
    address: Annotated[str, Field(examples=["Czfq3xZZDmsdGdUyrNLtRhGc47cXcZtLG4crryfu44zE"])]
    """
    On-chain pool address.
    """
    base_token: Annotated[int | None, Field(ge=0, le=1)] = 0
    """
    Index of the token to quote the pool in.
    """
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """


class PoolRelatedPoolsParams(BaseModel):
    address: Annotated[str, Field(examples=["Czfq3xZZDmsdGdUyrNLtRhGc47cXcZtLG4crryfu44zE"])]
    """
    On-chain pool address.
    """
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """


class PoolRelatedPoolsResponse(BaseModel):
    data: list[RelatedPoolResource]
    included: list[DexResource | NetworkResource | TokenResource]


class PoolRelationships(BaseModel):
    dex: ResourceLinkage | None = None
    pairs: ResourceLinkageList | None = None
    pool_metric: ResourceLinkage | None = None
    tokens: ResourceLinkageList


class PoolResource(BaseModel):
    attributes: PoolAttributes
    id: str
    relationships: PoolRelationships
    type: str


class PoolResponse(BaseModel):
    data: PoolResource
    included: list[
        DexLinkServiceResource
        | DexResource
        | ExplorerResource
        | NetworkLinkServiceResource
        | NetworkResource
        | PairResource
        | PoolLockedLiquidityResource
        | TagResource
        | TokenDeveloperDetailResource
        | TokenResource
        | TokenSecurityMetricResource
    ]


class PoolScreenerRequest(BaseModel):
    buy_tax: RangeFilter | None = None
    """
    Buy tax percentage.
    """
    buys: TimeframedRangeFilter | None = None
    """
    Buy count over the chosen window.
    """
    dexes: list[str] | None = None
    """
    Restrict to these DEX identifiers.
    """
    fdv_in_usd: RangeFilter | None = None
    """
    Fully diluted valuation in USD.
    """
    good_gt_score: bool | None = None
    """
    Only pools above GeckoTerminal's GT score threshold.
    """
    has_social: bool | None = None
    """
    Only pools whose token declares social links.
    """
    holder_count: RangeFilter | None = None
    """
    Number of token holders.
    """
    liquidity: RangeFilter | None = None
    """
    Pool liquidity in USD.
    """
    mc_in_usd: RangeFilter | None = None
    """
    Market cap in USD.
    """
    networks: list[str] | None = None
    """
    Restrict to these network identifiers.
    """
    no_honeypot: bool | None = None
    """
    Exclude tokens flagged as honeypots.
    """
    on_coingecko: bool | None = None
    """
    Only pools whose token is listed on CoinGecko.
    """
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    1-based result page.
    """
    pool_creation_hours_ago: RangeFilter | None = None
    """
    Pool age in hours.
    """
    sell_tax: RangeFilter | None = None
    """
    Sell tax percentage.
    """
    sells: TimeframedRangeFilter | None = None
    """
    Sell count over the chosen window.
    """
    sort: PoolSort | None = None
    """
    Ranking applied before pagination. Omit for GeckoTerminal's default.
    """
    top_10_holders_percentage: RangeFilter | None = None
    """
    Share of supply held by the ten largest holders.
    """
    tx_count: TimeframedRangeFilter | None = None
    """
    Transaction count over the chosen window.
    """
    volume_24h: RangeFilter | None = None
    """
    24h traded volume in USD.
    """


class PoolSenderSwapsParams(BaseModel):
    address: Annotated[str, Field(examples=["Czfq3xZZDmsdGdUyrNLtRhGc47cXcZtLG4crryfu44zE"])]
    """
    On-chain pool address.
    """
    from_timestamp: Annotated[int, Field(ge=0)]
    """
    Unix timestamp for the start of the window.
    """
    include_developer: bool | None = True
    """
    Tag swaps made by the token's developer wallet.
    """
    inverted: bool | None = False
    """
    Quote prices in the other token of the pair.
    """
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """
    pair_id: Annotated[str, Field(examples=["1770231"])]
    """
    Pair id from the pool's `pairs` relationship.
    """
    sender: str | None = None
    """
    Restrict swaps to one sender wallet address.
    """
    to_timestamp: Annotated[int, Field(ge=0)]
    """
    Unix timestamp for the end of the window.
    """


class PoolSenderSwapsResponse(BaseModel):
    data: list[SenderSwapResource]


class PoolSwapsParams(BaseModel):
    address: Annotated[str, Field(examples=["Czfq3xZZDmsdGdUyrNLtRhGc47cXcZtLG4crryfu44zE"])]
    """
    On-chain pool address.
    """
    inverted: bool | None = False
    """
    Quote prices in the other token of the pair.
    """
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """
    page_after: Annotated[str | None, Field(examples=["1788131488"])] = None
    """
    Return swaps older than this cursor.
    """
    page_before: str | None = None
    """
    Return swaps newer than this cursor.
    """
    pair_id: Annotated[str, Field(examples=["1770231"])]
    """
    Pair id from the pool's `pairs` relationship.
    """
    sender: str | None = None
    """
    Restrict swaps to one sender wallet address.
    """


class PoolSwapsResponse(BaseModel):
    data: list[SwapResource]
    included: list[TokenResource]
    links: PoolSwapsResponseLinks
    meta: PoolSwapsResponseMeta | None = None


class PoolSwapsResponseLinks(BaseModel):
    next: str
    prev: str


class PoolSwapsResponseMeta(BaseModel):
    next_limit: int


class PoolTokenInfoSnapshotsParams(BaseModel):
    address: Annotated[str, Field(examples=["Czfq3xZZDmsdGdUyrNLtRhGc47cXcZtLG4crryfu44zE"])]
    """
    On-chain pool address.
    """
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """


class PoolTokenInfoSnapshotsResponse(BaseModel):
    data: list[TokenResource]


class PoolsResponse(BaseModel):
    data: list[PoolResource]
    included: list[DexResource | NetworkResource | TokenResource]
    links: LatestPoolsResponseLinks
    meta: LatestPoolsResponseMeta


class RangeFilter(BaseModel):
    gte: float | None = None
    """
    Inclusive lower bound.
    """
    lte: float | None = None
    """
    Inclusive upper bound.
    """


class RelatedPoolAttributes(BaseModel):
    address: str
    liquidity: str
    pool_fee: str | None
    token_id: str
    volume_in_usd_24h: str


class RelatedPoolRelationships(BaseModel):
    dex: ResourceLinkage
    tokens: ResourceLinkageList


class RelatedPoolResource(BaseModel):
    attributes: RelatedPoolAttributes
    id: str
    relationships: RelatedPoolRelationships
    type: str


class ResourceIdentifier(BaseModel):
    id: str
    type: str


class ResourceLinkage(BaseModel):
    data: ResourceIdentifier | None


class ResourceLinkageList(BaseModel):
    data: list[ResourceIdentifier]


class RevivalRadarPoolsResponse(BaseModel):
    data: list[PoolResource]
    included: list[DexResource | NetworkResource | TokenResource]
    meta: RevivalRadarPoolsResponseMeta


class RevivalRadarPoolsResponseMeta(BaseModel):
    sections: RevivalRadarPoolsResponseMetaSections


class RevivalRadarPoolsResponseMetaSections(BaseModel):
    revived: list[str]
    reviving: list[str]
    sunsetting: list[str]


class SearchAttributes(BaseModel):
    dexes: list[str]
    networks: list[SearchAttributesNetworks] | list[str]
    pairs: list[str]
    pools: list[SearchAttributesPools] | list[str]
    tags: list[SearchAttributesTags] | list[str]


class SearchAttributesNetworks(BaseModel):
    identifier: str
    image_url: str
    name: str
    pools_count: int
    rank_by_volume_usd_24h: int
    swap_count_24h: int
    swap_volume_usd_24h: str
    type: str


class SearchAttributesPools(BaseModel):
    address: str
    api_address: str
    dex: TrendAttributesNewPoolsDex
    fdv_in_usd: str
    from_volume_in_usd: str
    gt_score: float
    market_cap_in_usd: str
    network: TrendAttributesNewPoolsNetwork
    on_coingecko: bool
    pool_creation_date: str
    pool_id: int
    price_in_usd: str
    price_percent_change: str
    reserve_in_usd: str
    to_volume_in_usd: str
    tokens: list[SearchAttributesPoolsTokens]
    type: str
    volume_percent_change_24h: str


class SearchAttributesPoolsTokens(BaseModel):
    address: str
    holder_count: int
    image_url: str
    is_base_token: bool
    is_verified: bool
    name: str
    symbol: str


class SearchAttributesTags(BaseModel):
    identifier: str
    name: str
    type: str


class SearchParams(BaseModel):
    query: Annotated[str, Field(examples=["bonk"], min_length=1)]
    """
    Free-text query matched against tokens, pools, categories, chains and DEXes.
    """


class SearchResource(BaseModel):
    attributes: SearchAttributes
    id: str
    type: str


class SearchResponse(BaseModel):
    data: SearchResource


class SearchTrendAttributes(BaseModel):
    search_items: list[SearchTrendAttributesSearchItems]


class SearchTrendAttributesSearchItems(BaseModel):
    base_token_image_url: str
    base_token_name: str
    base_token_symbol: str
    dex_identifier: str
    dex_image_url: str
    is_verified: bool
    name: str
    network_identifier: str
    network_image_url: str
    on_coingecko: bool
    pool_address: str
    pool_api_address: str
    price_percent_change: str
    reserve_in_usd: str
    type: str
    volume_in_usd_24h: str


class SearchTrendResource(BaseModel):
    attributes: SearchTrendAttributes
    id: str
    type: str


class SearchTrendsResponse(BaseModel):
    data: SearchTrendResource


class SenderSwapAttributes(BaseModel):
    action: str
    by: str
    swap_total_in_usd: str
    timestamp: str


class SenderSwapResource(BaseModel):
    attributes: SenderSwapAttributes
    id: str
    type: str


class SwapAttributes(BaseModel):
    from_token_amount: str
    from_token_total_in_usd: str
    price_from: str
    price_from_in_currency_token: str
    price_from_in_usd: str
    price_to: str
    price_to_in_currency_token: str
    price_to_in_usd: str
    timestamp: str
    to_token_amount: str
    to_token_total_in_usd: str
    tx_from_address: str
    tx_hash: str


class SwapRelationships(BaseModel):
    from_token: ResourceLinkage
    to_token: ResourceLinkage


class SwapResource(BaseModel):
    attributes: SwapAttributes
    id: str
    relationships: SwapRelationships
    type: str


class TagAttributes(BaseModel):
    buy_count_24h: int | None = None
    description: str | None = None
    fdv_in_usd: str | None = None
    icon_url: str | None
    identifier: str
    name: str
    pool_trend_rank: int | None
    reserve_in_usd: str | None = None
    sell_count_24h: int | None = None
    swap_count_24h: int | None = None
    swap_volume_usd_24h: float | None = None
    volume_percent_changes: TagAttributesVolumePercentChanges | None = None


class TagAttributesVolumePercentChanges(BaseModel):
    last_12h: str
    last_1h: str
    last_24h: str
    last_6h: str


class TagNetworkPoolsParams(BaseModel):
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    1-based result page.
    """
    tag: Annotated[str, Field(examples=["meme"])]
    """
    Category slug, as returned by the tags endpoint.
    """


class TagNetworkPoolsResponse(BaseModel):
    data: list[PoolResource]
    included: list[DexResource | NetworkResource | TokenResource]
    links: LatestPoolsResponseLinks
    meta: LatestPoolsResponseMeta


class TagPoolsParams(BaseModel):
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    1-based result page.
    """
    tag: Annotated[str, Field(examples=["meme"])]
    """
    Category slug, as returned by the tags endpoint.
    """


class TagPoolsResponse(BaseModel):
    data: list[PoolResource]
    included: list[DexResource | NetworkResource | TokenResource]
    links: LatestPoolsResponseLinks
    meta: LatestPoolsResponseMeta


class TagRelationships(BaseModel):
    top_tokens: ResourceLinkageList | None = None


class TagResource(BaseModel):
    attributes: TagAttributes
    id: str
    relationships: TagRelationships
    type: str


class TagsParams(BaseModel):
    page: Annotated[int | None, Field(ge=1)] = 1
    """
    1-based result page.
    """


class TagsResponse(BaseModel):
    data: list[TagResource]
    included: list[TokenResource]
    links: TagsResponseLinks


class TagsResponseLinks(BaseModel):
    first: str
    last: TagsResponseLinksLast
    next: str
    prev: str | None


class TagsResponseLinksLast(BaseModel):
    href: str
    meta: LatestPoolsResponseLinksLastMeta


class ThemeAttributes(BaseModel):
    pools: list[ThemeAttributesPools]
    pools_count: int
    tag: ThemeAttributesTag


class ThemeAttributesPools(BaseModel):
    base_token_id: str
    network_identifier: str
    pool_address: str
    tagged_token_id: str
    tokens: list[ThemeAttributesPoolsTokens]


class ThemeAttributesPoolsTokens(BaseModel):
    id: str
    image_url: str
    symbol: str


class ThemeAttributesTag(BaseModel):
    description: str | None = None
    id: str
    identifier: str
    name: str
    swap_count_24h: int
    swap_volume_usd_24h: float | None = None


class ThemeResource(BaseModel):
    attributes: ThemeAttributes
    id: str
    type: str


class TimeframedRangeFilter(BaseModel):
    gte: float | None = None
    """
    Inclusive lower bound.
    """
    lte: float | None = None
    """
    Inclusive upper bound.
    """
    timeframe: PoolFilterTimeframe | None = PoolFilterTimeframe.FIELD_24H
    """
    Window the trade counts are measured over.
    """


class TokenAttributes(BaseModel):
    address: str | None = None
    banner_image_url: str | None = None
    cg_coin_id: str | None = None
    circulating_supply: float | None = None
    cto: str | None = None
    decimals: int | None = None
    description: TokenAttributesDescription | None = None
    image_url: str | None = None
    is_verified: bool | None = None
    links: TokenAttributesLinks | None = None
    market_cap_in_usd: float | None = None
    metadata_updated_at: str | None = None
    name: str | None = None
    on_coingecko: bool | None = None
    on_pump_fun: bool | None = None
    supports_bubblemaps: bool | None = None
    supports_bubblemaps_v2: bool | None = None
    symbol: str | None = None
    token_info_snapshots: list[TokenAttributesTokenInfoSnapshots] | None = None
    top_traders_enabled: bool | None = None
    verified_at: str | None = None


class TokenAttributesDescription(BaseModel):
    en: str | None = None


class TokenAttributesLinks(BaseModel):
    discord_url: str | None = None
    facebook_handle: str | None = None
    github_repo_name: str | None = None
    instagram_handle: str | None = None
    medium_handle: str | None = None
    subreddit_handle: str | None = None
    telegram_handle: str | None = None
    tiktok_handle: str | None = None
    twitter_handle: str | None = None
    warpcast_url: str | None = None
    websites: list[str] | None = None
    youtube_handle: str | None = None
    zora_url: str | None = None


class TokenAttributesTokenInfoSnapshots(BaseModel):
    description: TokenAttributesDescription
    links: TokenAttributesTokenInfoSnapshotsLinks
    timestamp: str | None
    type: str


class TokenAttributesTokenInfoSnapshotsLinks(BaseModel):
    discord_url: str | None = None
    facebook_handle: str | None = None
    github_repo_name: str | None = None
    instagram_handle: str | None = None
    medium_handle: str | None = None
    subreddit_handle: str | None = None
    telegram_handle: str | None = None
    tiktok_handle: str | None = None
    twitter_handle: str | None = None
    warpcast_url: str | None = None
    websites: list[str] | None = None
    youtube_handle: str | None = None
    zora_url: str | None = None


class TokenDeveloperDetailAttributes(BaseModel):
    address: str
    holding_amount: str
    holding_percentage: float
    label: str | None
    realized_pnl_amount: str | None
    realized_pnl_percentage: float | None
    unrealized_pnl_amount: str | None
    unrealized_pnl_percentage: float | None


class TokenDeveloperDetailResource(BaseModel):
    attributes: TokenDeveloperDetailAttributes
    id: str
    relationships: TokenSecurityMetricRelationships
    type: str


class TokenDeveloperPastTokensParams(BaseModel):
    developer_detail_id: Annotated[str, Field(examples=["13236719"])]
    """
    Id of a `token_developer_detail` resource embedded in a pool response.
    """


class TokenDeveloperPastTokensResponse(BaseModel):
    data: PastTokensDeveloperDetailResource


class TokenHistoricalHoldersParams(BaseModel):
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """
    period: HolderHistoryPeriod | None = HolderHistoryPeriod.FIELD_1_W
    """
    Look-back window for the snapshot series.
    """
    token_address: Annotated[str, Field(examples=["AfGdjAp9djSaqJxzYo3t6jy8tJA3o2aDPHoZ57Egpump"])]
    """
    On-chain token address.
    """


class TokenHistoricalHoldersResponse(BaseModel):
    data: list[TokenHoldersSnapshotResource]


class TokenHoldersDetailAttributes(BaseModel):
    explorer_coin_url: str
    explorer_holder_url: str
    source: str | None
    top_holders: list[TokenHoldersDetailAttributesTopHolders]


class TokenHoldersDetailAttributesTopHolders(BaseModel):
    amount: float
    average_buy_in_usd: float | None
    entity_name: str | None
    entity_type: str | None
    is_liquidity_pool: bool | None
    label: str | None
    owner_percent: float
    realized_pnl: float | None
    realized_pnl_percentage: float | None
    total_buy_count: int | None
    total_sell_count: int | None
    unrealized_pnl: float | None
    unrealized_pnl_percentage: float | None
    value_in_usd: float
    wallet_address: str


class TokenHoldersDetailResource(BaseModel):
    attributes: TokenHoldersDetailAttributes
    id: str
    type: str


class TokenHoldersSnapshotAttributes(BaseModel):
    holder_count: int
    timestamp: str


class TokenHoldersSnapshotResource(BaseModel):
    attributes: TokenHoldersSnapshotAttributes
    id: str
    type: str


class TokenRelationships(BaseModel):
    tags: ResourceLinkageList | None = None


class TokenResource(BaseModel):
    attributes: TokenAttributes
    id: str
    relationships: TokenRelationships
    type: str


class TokenSecurityMetricAttributes(BaseModel):
    defi_scanner_data: dict[str, str | None]
    defi_scanner_updated_at: str | None
    go_plus_token_security_data: TokenSecurityMetricAttributesGoPlusTokenSecurityData
    go_plus_token_security_updated_at: str | None
    holder_count: int
    honeypot_scanner_data: TokenSecurityMetricAttributesHoneypotScannerData
    honeypot_scanner_updated_at: str | None
    insightx_security_data: TokenSecurityMetricAttributesInsightxSecurityData
    insightx_updated_at: str | None
    soul_scanner_data: TokenSecurityMetricAttributesSoulScannerData
    soul_scanner_updated_at: str | None


class TokenSecurityMetricAttributesGoPlusTokenSecurityData(BaseModel):
    anti_whale_modifiable: str | None = None
    buy_tax: str | None = None
    can_take_back_ownership: str | None = None
    cannot_buy: str | None = None
    cannot_sell_all: str | None = None
    creator_address: str | None = None
    creator_balance: str | None = None
    creator_percent: str | None = None
    external_call: str | None = None
    hidden_owner: str | None = None
    holder_count: str | None = None
    is_anti_whale: str | None = None
    is_blacklisted: str | None = None
    is_honeypot: str | None = None
    is_in_dex: str | None = None
    is_mintable: str | None = None
    is_open_source: str | None = None
    is_proxy: str | None = None
    is_whitelisted: str | None = None
    owner_address: str | None = None
    owner_balance: str | None = None
    owner_change_balance: str | None = None
    owner_percent: str | None = None
    personal_slippage_modifiable: str | None = None
    selfdestruct: str | None = None
    sell_tax: str | None = None
    slippage_modifiable: str | None = None
    top_10_holders_percent: str | None = None
    trading_cooldown: str | None = None
    transfer_pausable: str | None = None
    trust_list: str | None = None


class TokenSecurityMetricAttributesHoneypotScannerData(BaseModel):
    holder_count: int | None = None
    honeypot: str | None = None


class TokenSecurityMetricAttributesInsightxSecurityData(BaseModel):
    bundlers_pct: float | None = None
    cluster_pct: float | None = None
    dev_pct: float | None = None
    insiders_pct: float | None = None
    snipers_pct: float | None = None
    top10_pct: float | None = None


class TokenSecurityMetricAttributesSoulScannerData(BaseModel):
    freezeable: str | None = None
    mintable: str | None = None


class TokenSecurityMetricRelationships(BaseModel):
    token: ResourceLinkage


class TokenSecurityMetricResource(BaseModel):
    attributes: TokenSecurityMetricAttributes
    id: str
    relationships: TokenSecurityMetricRelationships
    type: str


class TokenTopHoldersParams(BaseModel):
    network: Annotated[str, Field(examples=["solana"])]
    """
    GeckoTerminal network identifier.
    """
    token_address: Annotated[str, Field(examples=["AfGdjAp9djSaqJxzYo3t6jy8tJA3o2aDPHoZ57Egpump"])]
    """
    On-chain token address.
    """


class TokenTopHoldersResponse(BaseModel):
    data: TokenHoldersDetailResource


class TokenTopTradersParams(BaseModel):
    token_id: Annotated[str, Field(examples=["124704000"])]
    """
    GeckoTerminal numeric token id, as returned in a token resource's `id`.
    """


class TokenTopTradersResponse(BaseModel):
    data: list[WalletTokenResource]
    included: list[str]


class TrendAttributes(BaseModel):
    new_pools: list[TrendAttributesNewPools]
    top_gainers_pairs: list[TrendAttributesTopGainersPairs]


class TrendAttributesNewPools(BaseModel):
    address: str
    api_address: str
    dex: TrendAttributesNewPoolsDex
    network: TrendAttributesNewPoolsNetwork
    pair_id: str | None
    pool: TrendAttributesNewPoolsPool
    pool_created_at: str
    price_change: str
    price_in_usd: str
    price_percent_change: str
    token_id: str | None
    tokens: list[TrendAttributesNewPoolsTokens]
    type: str


class TrendAttributesNewPoolsDex(BaseModel):
    identifier: str
    image_url: str
    name: str


class TrendAttributesNewPoolsNetwork(BaseModel):
    identifier: str
    image_url: str
    name: str


class TrendAttributesNewPoolsPool(BaseModel):
    pairs_count: int


class TrendAttributesNewPoolsTokens(BaseModel):
    image_url: str
    is_base_token: bool
    name: str
    symbol: str


class TrendAttributesTopGainersPairs(BaseModel):
    address: str
    api_address: str
    dex: TrendAttributesNewPoolsDex
    network: TrendAttributesNewPoolsNetwork
    pair_id: int
    pool: TrendAttributesNewPoolsPool
    price_change: float
    price_in_usd: str
    price_percent_change: float
    token_id: str | None
    tokens: list[TrendAttributesNewPoolsTokens]
    type: str


class TrendResource(BaseModel):
    attributes: TrendAttributes
    id: str
    type: str


class TrendingLinkAttributes(BaseModel):
    name: str
    path: str


class TrendingLinkResource(BaseModel):
    attributes: TrendingLinkAttributes
    id: str
    type: str


class TrendingLinksResponse(BaseModel):
    data: list[TrendingLinkResource]


class TrendingThemesParams(BaseModel):
    dex: Annotated[str | None, Field(examples=["pumpswap"])] = None
    """
    Restrict results to one DEX identifier.
    """
    more_themes: bool | None = False
    """
    Return GeckoTerminal's extended theme list rather than the top few.
    """
    network: Annotated[str | None, Field(examples=["solana"])] = None
    """
    Restrict results to one network identifier.
    """


class TrendingThemesResponse(BaseModel):
    data: list[ThemeResource]


class TrendsParams(BaseModel):
    dex: Annotated[str | None, Field(examples=["pumpswap"])] = None
    """
    Restrict results to one DEX identifier.
    """
    network: Annotated[str | None, Field(examples=["solana"])] = None
    """
    Restrict results to one network identifier.
    """


class TrendsResponse(BaseModel):
    data: TrendResource


class WalletTokenAttributes(BaseModel):
    average_buy_in_usd: str
    average_sell_in_usd: str
    balance: str | None
    explorer_holder_url: str
    realized_pnl: str
    realized_pnl_percentage: float | None
    total_buy_amount: str
    total_buy_count: int
    total_buy_in_usd: str
    total_buys: int
    total_sell_amount: str
    total_sell_count: int
    total_sell_in_usd: str
    total_sells: int
    unrealized_pnl: str | None
    unrealized_pnl_percentage: float | None
    wallet_address: str


class WalletTokenParams(BaseModel):
    token_id: Annotated[str, Field(examples=["124704000"])]
    """
    GeckoTerminal numeric token id, as returned in a token resource's `id`.
    """
    wallet_address: Annotated[str, Field(examples=["8RhxpPr1e84qvhYgtoYNRYPK2nPvh8ZdDHcdWWK9J53z"])]
    """
    Wallet address to scope the token position to.
    """


class WalletTokenRelationships(BaseModel):
    address_label: ResourceLinkage


class WalletTokenResource(BaseModel):
    attributes: WalletTokenAttributes
    id: str
    relationships: WalletTokenRelationships
    type: str


class WalletTokenResponse(BaseModel):
    data: list[WalletTokenResource]
    included: list[str]


CandlestickCurrencyParam: TypeAlias = CandlestickCurrency | Literal["usd", "token"]
CandlestickResolutionParam: TypeAlias = (
    CandlestickResolution | Literal["1", "5", "15", "60", "120", "240", "720", "1D"]
)
HolderHistoryPeriodParam: TypeAlias = HolderHistoryPeriod | Literal["1W", "1M", "all"]
PoolFilterTimeframeParam: TypeAlias = PoolFilterTimeframe | Literal["5m", "1h", "6h", "24h"]
PoolSortParam: TypeAlias = (
    PoolSort
    | Literal[
        "-5m_trend_score",
        "-1h_trend_score",
        "-6h_trend_score",
        "-24h_trend_score",
        "-24h_transactions",
        "-24h_volume",
        "-pool_creation_date",
        "-24h_price_percent_change",
        "-6h_price_percent_change",
        "-1h_price_percent_change",
        "-5m_price_percent_change",
        "fdv",
        "-fdv",
        "liquidity",
        "-liquidity",
        "mc",
        "-mc",
    ]
)
PublicErrorValue: TypeAlias = Annotated[PublicError | str, PREFER_ENUM]
